import {
  createHash,
} from "node:crypto";
import {
  assertEnergyOperationKey,
  type EnergyOperationKey,
} from "../energy/model";

export const LISTING_AI_ENERGY_CONTRACT_VERSION =
  "v2-energy-1";

export const LISTING_AI_FEATURE =
  "listing_ai_analysis";

export const LISTING_AI_MODEL =
  "gpt-4.1-mini-2025-04-14";

export const LISTING_AI_IMAGE_DETAIL =
  "low";

export const LISTING_AI_STALE_RESERVATION_MS =
  5 * 60 * 1000;

export const LISTING_AI_INPUT_PRICE_NANO_USD =
  400;

export const LISTING_AI_CACHED_INPUT_PRICE_NANO_USD =
  100;

export const LISTING_AI_OUTPUT_PRICE_NANO_USD =
  1_600;

export const LISTING_AI_PRICING_VERSION =
  "gpt-4.1-mini-2026-08-20";

const TITLE_MAX_LENGTH = 140;
const DESCRIPTION_MAX_LENGTH = 5_000;
const IMAGE_URL_MAX_LENGTH = 8_000_000;

const UUID_V4_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

const DATA_IMAGE_PATTERN =
  /^data:image\/(?:jpeg|jpg|png|webp);base64,/i;

export type ListingAiEnergyRequest = {
  contractVersion:
    typeof LISTING_AI_ENERGY_CONTRACT_VERSION;
  idempotencyKey: string;
  operationKey: EnergyOperationKey;
  title: string;
  description: string;
  imageUrl: string;
  requestHash: string;
};

export type ListingAiResult = {
  object: string;
  category: string;
  subcategory: string;
  detailCategory: string;
  brand: string;
  model: string;
  suggested_title: string;
  suggested_description: string;
  confidence: number;
  fields: Record<string, string>;
};

export type ListingAiUsageSnapshot = {
  responseId: string;
  model: string;
  inputTokens: number;
  cachedInputTokens: number;
  cacheWriteInputTokens: number;
  outputTokens: number;
  totalTokens: number;
  durationMs: number;
  estimatedProviderCostNanoUsd: number;
  estimatedProviderCostUsd: string;
  pricingVersion:
    typeof LISTING_AI_PRICING_VERSION;
};

type ListingAiRouteErrorInput = {
  message: string;
  status: number;
  code: string;
  retryable: boolean;
  stage: string;
  internalMessage?: string;
  internalCause?: unknown;
};

export class ListingAiRouteError
  extends Error {
  readonly status: number;
  readonly code: string;
  readonly retryable: boolean;
  readonly stage: string;
  readonly internalMessage:
    string | null;
  readonly internalCause: unknown;

  constructor(
    input: ListingAiRouteErrorInput
  ) {
    super(input.message);

    this.name =
      "ListingAiRouteError";
    this.status =
      input.status;
    this.code =
      input.code;
    this.retryable =
      input.retryable;
    this.stage =
      input.stage;
    this.internalMessage =
      input.internalMessage || null;
    this.internalCause =
      input.internalCause;
  }
}

function invalidRequest(
  message: string,
  internalMessage: string
): ListingAiRouteError {
  return new ListingAiRouteError({
    message,
    status: 400,
    code:
      "invalid_listing_ai_request",
    retryable: false,
    stage:
      "request_validation",
    internalMessage,
  });
}

function asRecord(
  value: unknown
): Record<string, unknown> | null {
  if (
    !value ||
    typeof value !== "object" ||
    Array.isArray(value)
  ) {
    return null;
  }

  return value as
    Record<string, unknown>;
}

function compactTitle(
  value: unknown
): string {
  return String(
    value || ""
  )
    .trim()
    .replace(
      /\s+/g,
      " "
    );
}

function compactDescription(
  value: unknown
): string {
  return String(
    value || ""
  ).trim();
}

function validateImageUrl(
  value: unknown
): string {
  const imageUrl =
    String(
      value || ""
    ).trim();

  if (!imageUrl) {
    throw invalidRequest(
      "Lisa enne AI analüüsi vähemalt üks pilt.",
      "The V2 Energy request did not contain imageUrl."
    );
  }

  if (
    imageUrl.length >
    IMAGE_URL_MAX_LENGTH
  ) {
    throw invalidRequest(
      "AI analüüsi põhipilt on liiga mahukas.",
      `imageUrl exceeds ${IMAGE_URL_MAX_LENGTH} characters.`
    );
  }

  if (
    !DATA_IMAGE_PATTERN.test(
      imageUrl
    ) &&
    !imageUrl.startsWith(
      "https://"
    )
  ) {
    throw invalidRequest(
      "AI analüüsi pildi formaat ei ole toetatud.",
      "imageUrl must be an HTTPS URL or a JPEG, PNG or WEBP data URL."
    );
  }

  return imageUrl;
}

function validateIdempotencyKey(
  value: unknown
): string {
  const key =
    String(
      value || ""
    ).trim();

  if (
    !UUID_V4_PATTERN.test(
      key
    )
  ) {
    throw invalidRequest(
      "AI analüüsi toimingu võti ei ole korrektne.",
      "idempotencyKey must be a UUID v4 generated by the browser."
    );
  }

  return key.toLowerCase();
}

export function normalizeListingAiEnergyRequest(
  value: unknown
): ListingAiEnergyRequest {
  const row =
    asRecord(value);

  if (!row) {
    throw invalidRequest(
      "AI analüüsi päring ei ole korrektne.",
      "Request body is not an object."
    );
  }

  if (
    row.contractVersion !==
    LISTING_AI_ENERGY_CONTRACT_VERSION
  ) {
    throw invalidRequest(
      "AI analüüsi versioon ei ole toetatud.",
      "The Energy contractVersion is missing or unsupported."
    );
  }

  const title =
    compactTitle(
      row.title
    );

  const description =
    compactDescription(
      row.description
    );

  if (
    title.length >
    TITLE_MAX_LENGTH
  ) {
    throw invalidRequest(
      `Pealkiri võib olla kuni ${TITLE_MAX_LENGTH} tähemärki.`,
      "Title exceeds the V2 listing limit."
    );
  }

  if (
    description.length >
    DESCRIPTION_MAX_LENGTH
  ) {
    throw invalidRequest(
      `Kirjeldus võib olla kuni ${DESCRIPTION_MAX_LENGTH} tähemärki.`,
      "Description exceeds the V2 listing limit."
    );
  }

  const idempotencyKey =
    validateIdempotencyKey(
      row.idempotencyKey
    );

  const imageUrl =
    validateImageUrl(
      row.imageUrl
    );

  const requestHash =
    createHash("sha256")
      .update(
        JSON.stringify({
          contractVersion:
            LISTING_AI_ENERGY_CONTRACT_VERSION,
          title,
          description,
          imageUrl,
        })
      )
      .digest("hex");

  const operationKey =
    assertEnergyOperationKey(
      `energy:${LISTING_AI_FEATURE}:${idempotencyKey}`
    );

  return {
    contractVersion:
      LISTING_AI_ENERGY_CONTRACT_VERSION,
    idempotencyKey,
    operationKey,
    title,
    description,
    imageUrl,
    requestHash,
  };
}

function safeInteger(
  value: unknown
): number {
  const parsed =
    typeof value === "number" ||
    typeof value === "string"
      ? Number(value)
      : Number.NaN;

  if (
    !Number.isSafeInteger(
      parsed
    ) ||
    parsed < 0
  ) {
    return 0;
  }

  return parsed;
}

function textValue(
  value: unknown,
  maxLength: number
): string {
  return String(
    value || ""
  )
    .trim()
    .slice(
      0,
      maxLength
    );
}

function numberValue(
  value: unknown
): number {
  const parsed =
    Number(value);

  if (
    !Number.isFinite(
      parsed
    )
  ) {
    return 0;
  }

  return Math.min(
    1,
    Math.max(
      0,
      parsed
    )
  );
}

export function extractListingAiJson(
  value: string
): Record<string, unknown> {
  const text =
    value.trim();

  if (!text) {
    throw new ListingAiRouteError({
      message:
        "AI ei tagastanud analüüsi tulemust.",
      status: 502,
      code:
        "ai_empty_response",
      retryable: true,
      stage:
        "response_parse",
      internalMessage:
        "OpenAI response.output_text was empty.",
    });
  }

  const candidates = [
    text,
    text.match(
      /\{[\s\S]*\}/
    )?.[0] || "",
  ];

  for (
    const candidate
    of candidates
  ) {
    if (!candidate) {
      continue;
    }

    try {
      const parsed =
        JSON.parse(
          candidate
        );

      const row =
        asRecord(
          parsed
        );

      if (row) {
        return row;
      }
    } catch {
      // Try the next candidate.
    }
  }

  throw new ListingAiRouteError({
    message:
      "AI vastust ei saanud lugeda.",
    status: 502,
    code:
      "ai_invalid_json",
    retryable: true,
    stage:
      "response_parse",
    internalMessage:
      "OpenAI output did not contain a valid JSON object.",
  });
}

export function normalizeListingAiResult(
  value: unknown,
  input: {
    category: string;
    subcategory: string;
    detailCategory: string;
    allowedFieldKeys:
      readonly string[];
  }
): ListingAiResult {
  const row =
    asRecord(value);

  if (!row) {
    throw new ListingAiRouteError({
      message:
        "AI analüüsi tulemus ei ole korrektne.",
      status: 502,
      code:
        "ai_invalid_result",
      retryable: true,
      stage:
        "response_validation",
      internalMessage:
        "The parsed AI result is not an object.",
    });
  }

  const incomingFields =
    asRecord(
      row.fields
    ) || {};

  const fields:
    Record<string, string> = {};

  for (
    const key
    of input.allowedFieldKeys
  ) {
    const fieldValue =
      incomingFields[key];

    if (
      typeof fieldValue ===
        "string" &&
      fieldValue.trim()
    ) {
      fields[key] =
        fieldValue
          .trim()
          .slice(
            0,
            1_000
          );
    }
  }

  return {
    object:
      textValue(
        row.object,
        160
      ),
    category:
      input.category,
    subcategory:
      input.subcategory,
    detailCategory:
      input.detailCategory,
    brand:
      textValue(
        row.brand,
        120
      ),
    model:
      textValue(
        row.model,
        160
      ),
    suggested_title:
      textValue(
        row.suggested_title,
        TITLE_MAX_LENGTH
      ),
    suggested_description:
      textValue(
        row.suggested_description,
        1_200
      ),
    confidence:
      numberValue(
        row.confidence
      ),
    fields,
  };
}

export function buildListingAiUsageSnapshot(
  response: unknown,
  durationMs: number
): ListingAiUsageSnapshot {
  const responseRow =
    asRecord(response) || {};

  const usageRow =
    asRecord(
      responseRow.usage
    ) || {};

  const inputDetails =
    asRecord(
      usageRow
        .input_tokens_details
    ) || {};

  const inputTokens =
    safeInteger(
      usageRow.input_tokens
    );

  const cachedInputTokens =
    Math.min(
      inputTokens,
      safeInteger(
        inputDetails.cached_tokens
      )
    );

  const cacheWriteInputTokens =
    Math.min(
      inputTokens,
      safeInteger(
        inputDetails
          .cache_write_tokens
      )
    );

  const outputTokens =
    safeInteger(
      usageRow.output_tokens
    );

  const totalTokens =
    safeInteger(
      usageRow.total_tokens
    ) ||
    inputTokens +
      outputTokens;

  const ordinaryInputTokens =
    Math.max(
      0,
      inputTokens -
        cachedInputTokens
    );

  const estimatedProviderCostNanoUsd =
    ordinaryInputTokens *
      LISTING_AI_INPUT_PRICE_NANO_USD +
    cachedInputTokens *
      LISTING_AI_CACHED_INPUT_PRICE_NANO_USD +
    outputTokens *
      LISTING_AI_OUTPUT_PRICE_NANO_USD;

  return {
    responseId:
      textValue(
        responseRow.id,
        200
      ),
    model:
      textValue(
        responseRow.model,
        200
      ) ||
      LISTING_AI_MODEL,
    inputTokens,
    cachedInputTokens,
    cacheWriteInputTokens,
    outputTokens,
    totalTokens,
    durationMs:
      safeInteger(
        durationMs
      ),
    estimatedProviderCostNanoUsd,
    estimatedProviderCostUsd:
      (
        estimatedProviderCostNanoUsd /
        1_000_000_000
      ).toFixed(9),
    pricingVersion:
      LISTING_AI_PRICING_VERSION,
  };
}

export function isListingAiResult(
  value: unknown
): value is ListingAiResult {
  const row =
    asRecord(value);

  if (!row) {
    return false;
  }

  const fields =
    asRecord(
      row.fields
    );

  return (
    typeof row.object ===
      "string" &&
    typeof row.category ===
      "string" &&
    typeof row.subcategory ===
      "string" &&
    typeof row.detailCategory ===
      "string" &&
    typeof row.brand ===
      "string" &&
    typeof row.model ===
      "string" &&
    typeof row.suggested_title ===
      "string" &&
    typeof row.suggested_description ===
      "string" &&
    typeof row.confidence ===
      "number" &&
    Boolean(fields)
  );
}

export function isListingAiUsageSnapshot(
  value: unknown
): value is ListingAiUsageSnapshot {
  const row =
    asRecord(value);

  return Boolean(
    row &&
      typeof row.responseId ===
        "string" &&
      typeof row.model ===
        "string" &&
      typeof row.inputTokens ===
        "number" &&
      typeof row.cachedInputTokens ===
        "number" &&
      typeof row.cacheWriteInputTokens ===
        "number" &&
      typeof row.outputTokens ===
        "number" &&
      typeof row.totalTokens ===
        "number" &&
      typeof row.durationMs ===
        "number" &&
      typeof row.estimatedProviderCostNanoUsd ===
        "number" &&
      typeof row.estimatedProviderCostUsd ===
        "string" &&
      row.pricingVersion ===
        LISTING_AI_PRICING_VERSION
  );
}
