-- NEW tests only; no replay of the old core/atomic/creation suites.
CREATE SCHEMA reader_test;
CREATE FUNCTION reader_test.ok(p boolean,label text) RETURNS void LANGUAGE plpgsql AS $f$
BEGIN IF p IS DISTINCT FROM true THEN RAISE EXCEPTION 'PRICE_READ_FAILED: %',label; END IF;
 RAISE NOTICE 'PRICE_READ_PASS: %',label; END $f$;
-- Exercise real SQL roles without table grants. Synthetic actor, not a real JWT.
CREATE FUNCTION reader_test.call_as(role_name text,actor text,query text) RETURNS jsonb LANGUAGE plpgsql AS $f$
DECLARE v_result jsonb; BEGIN
 EXECUTE format('SET LOCAL ROLE %I',role_name);
 PERFORM set_config('request.jwt.claim.sub',actor,true);
 EXECUTE query INTO v_result;
 RESET ROLE; PERFORM set_config('request.jwt.claim.sub','',true); RETURN v_result;
EXCEPTION WHEN OTHERS THEN
 RESET ROLE; PERFORM set_config('request.jwt.claim.sub','',true); RAISE;
END $f$;
CREATE FUNCTION reader_test.error_as(role_name text,actor text,query text,code text) RETURNS boolean LANGUAGE plpgsql AS $f$
BEGIN
 PERFORM reader_test.call_as(role_name,actor,query); RETURN false;
EXCEPTION WHEN OTHERS THEN RETURN SQLSTATE=code; END $f$;
CREATE FUNCTION reader_test.same_nonprice(a jsonb,b jsonb) RETURNS boolean LANGUAGE sql IMMUTABLE AS $f$
SELECT (a - ARRAY['schema_version','items']) = (b - ARRAY['schema_version','items']) AND
 (SELECT coalesce(jsonb_agg(x - ARRAY['price','price_amount','currency'] ORDER BY n),'[]'::jsonb)
 FROM jsonb_array_elements(a->'items') WITH ORDINALITY t(x,n)) =
 (SELECT coalesce(jsonb_agg(x - 'price' ORDER BY n),'[]'::jsonb)
 FROM jsonb_array_elements(b->'items') WITH ORDINALITY t(x,n)); $f$;
CREATE TABLE reader_test.saved(k text PRIMARY KEY,v jsonb);
CREATE TABLE reader_test.rows_before AS SELECT * FROM public.listings;
INSERT INTO reader_test.saved VALUES ('table_acl',to_jsonb((SELECT relacl::text FROM pg_class WHERE oid='public.listings'::regclass)));
INSERT INTO reader_test.saved VALUES ('v1def',to_jsonb(pg_get_functiondef('public.search_public_listings_v1(text,text,text,text,text,text,integer,integer)'::regprocedure)));
SELECT reader_test.ok(NOT has_function_privilege('anon','public.search_public_listings_v2(text,text,text,text,text,text,integer,integer)','EXECUTE'),'anon_closed_acl');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''');','42501'),'anon_closed_runtime');
SELECT reader_test.ok(NOT has_function_privilege('anon','public.listing_price_read_model_v1(text,numeric,text,bigint,text)','EXECUTE'),'anon_projection_closed');
SELECT reader_test.ok(NOT has_function_privilege('authenticated','public.search_public_listings_v2(text,text,text,text,text,text,integer,integer)','EXECUTE'),'authenticated_closed_acl');
SELECT reader_test.ok(reader_test.error_as('authenticated','11111111-1111-4111-8111-111111111111','SELECT public.search_public_listings_v2(p_search_query=>'''');','42501'),'authenticated_closed_runtime');
SELECT reader_test.ok(NOT has_function_privilege('authenticated','public.listing_price_read_model_v1(text,numeric,text,bigint,text)','EXECUTE'),'authenticated_projection_closed');
SELECT reader_test.ok(NOT has_function_privilege('service_role','public.search_public_listings_v2(text,text,text,text,text,text,integer,integer)','EXECUTE'),'service_role_closed_acl');
SELECT reader_test.ok(reader_test.error_as('service_role','11111111-1111-4111-8111-111111111111','SELECT public.search_public_listings_v2(p_search_query=>'''');','42501'),'service_role_closed_runtime');
SELECT reader_test.ok(NOT has_function_privilege('service_role','public.listing_price_read_model_v1(text,numeric,text,bigint,text)','EXECUTE'),'service_role_projection_closed');
SELECT reader_test.ok(NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.search_public_listings_v2(text,text,text,text,text,text,integer,integer)'::regprocedure AND NOT prosecdef),'search_definer');
SELECT reader_test.ok((SELECT provolatile='s' FROM pg_proc WHERE oid='public.search_public_listings_v2(text,text,text,text,text,text,integer,integer)'::regprocedure),'search_stable');
GRANT EXECUTE ON FUNCTION public.search_public_listings_v2(text,text,text,text,text,text,integer,integer) TO anon,authenticated,service_role;
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''');')->>'total_count'='3','public_count_three');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''hidden'');')->>'total_count'='0','all_nonpublic_before_count');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''Original'');')->>'total_count'='0','unassigned_not_visible');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''reader-alpha'');')->>'schema_version'='1','old_v1_schema_unchanged');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''');')->>'schema_version'='2','new_v2_schema');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''');')),'all_nonprice_same');
SELECT reader_test.ok((SELECT to_jsonb(l) FROM public.listings l WHERE id=1001)=(SELECT to_jsonb(l) FROM reader_test.rows_before l WHERE id=1001),'reader_no_row_write');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''reader-alpha'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')),'same_keyword_reader_alpha');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''Modeltoken'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''Modeltoken'');')),'same_keyword_modeltoken');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''SECRET_VIN'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''SECRET_VIN'');')),'same_keyword_secret_vin');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''SECRET_DETAILS'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''SECRET_DETAILS'');')),'same_keyword_secret_details');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''SECRET_AI'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''SECRET_AI'');')),'same_keyword_secret_ai');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''SECRET_ADDRESS'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''SECRET_ADDRESS'');')),'same_keyword_secret_address');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''SECRET_VIN'');')->>'total_count'='0','not_searching_secret_vin');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''SECRET_DETAILS'');')->>'total_count'='0','not_searching_secret_details');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''SECRET_AI'');')->>'total_count'='0','not_searching_secret_ai');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''SECRET_ADDRESS'');')->>'total_count'='0','not_searching_secret_address');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''Modeltoken'');')->>'total_count'='1','existing_detail_keyword_matches');
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_text'='5578','legacy_text_exact');
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_amount'='5578','legacy_numeric_separate');
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'kind'='null'::jsonb AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'currency'='null'::jsonb,'legacy_no_kind_currency_guess');
UPDATE public.listings SET price='2345 €',price_amount=2345 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_text'='2345 €' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'kind'='null'::jsonb,'legacy_symbol_not_inferred');
UPDATE public.listings SET price='1000 SEK',price_amount=1000 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_text'='1000 SEK' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'kind'='null'::jsonb,'legacy_code_not_inferred');
UPDATE public.listings SET price='Hind kokkuleppel',price_amount=0 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_text'='Hind kokkuleppel' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'kind'='null'::jsonb,'legacy_negotiable_text_not_inferred');
UPDATE public.listings SET price='Tasuta',price_amount=0 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_text'='Tasuta' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'kind'='null'::jsonb,'legacy_free_text_not_inferred');
UPDATE public.listings SET price='130.',price_amount=130 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_text'='130.' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'kind'='null'::jsonb,'legacy_trailing_dot_not_inferred');
UPDATE public.listings SET price='$ 100',price_amount=100 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_text'='$ 100' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'kind'='null'::jsonb,'legacy_ambiguous_symbol_not_inferred');
UPDATE public.listings SET price='12,34',price_amount=12.34 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_text'='12,34' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'kind'='null'::jsonb,'legacy_decimal_comma_not_inferred');
UPDATE public.listings SET price=NULL,price_amount=-1 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'legacy_amount'='null'::jsonb,'legacy_invalid_number_39');
UPDATE public.listings SET price=NULL,price_amount='NaN'::numeric WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'legacy_amount'='null'::jsonb,'legacy_invalid_number_40');
UPDATE public.listings SET price=NULL,price_amount='Infinity'::numeric WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'legacy_amount'='null'::jsonb,'legacy_invalid_number_41');
UPDATE public.listings SET price=NULL,price_amount='-Infinity'::numeric WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'legacy_amount'='null'::jsonb,'legacy_invalid_number_42');
UPDATE public.listings SET price=NULL,price_amount=NULL WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'legacy_amount'='null'::jsonb,'legacy_invalid_number_43');
UPDATE public.listings SET price=NULL,price_amount=999999999999999999.123 WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'legacy_amount'='999999999999999999.123','legacy_exact_large_number_not_rounded');
GRANT EXECUTE ON FUNCTION public.get_my_listing_basics_v1(text,uuid), public.save_my_listing_basics_v1(text,uuid,jsonb,jsonb,jsonb,text) TO authenticated;
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='AUD' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='AUD','exact_AUD');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_AUD');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.999,currency='BHD' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.999' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='BHD','exact_BHD');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_BHD');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='CAD' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='CAD','exact_CAD');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_CAD');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='CHF' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='CHF','exact_CHF');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_CHF');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='CZK' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='CZK','exact_CZK');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_CZK');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='DKK' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='DKK','exact_DKK');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_DKK');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='EUR' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='EUR','exact_EUR');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_EUR');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='GBP' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='GBP','exact_GBP');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_GBP');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999,currency='JPY' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='JPY','exact_JPY');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_JPY');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.999,currency='KWD' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.999' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='KWD','exact_KWD');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_KWD');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='NOK' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='NOK','exact_NOK');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_NOK');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='NZD' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='NZD','exact_NZD');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_NZD');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='PLN' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='PLN','exact_PLN');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_PLN');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='SEK' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='SEK','exact_SEK');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_SEK');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.999,currency='TND' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.999' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='TND','exact_TND');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_TND');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.99,currency='USD' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='999999999999999999.99' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='USD','exact_USD');
SELECT reader_test.ok(jsonb_typeof((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount')='string','amount_is_string_USD');
INSERT INTO reader_test.saved VALUES('owner',reader_test.call_as('authenticated','11111111-1111-4111-8111-111111111111','SELECT public.get_my_listing_basics_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'');'));
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}') - 'legacy_amount' = (SELECT (v->'price') - 'revision' FROM reader_test.saved WHERE k='owner'),'owner_public_same_price_snapshot');
SELECT reader_test.ok((SELECT jsonb_typeof(v#>'{price,revision}')='string' FROM reader_test.saved WHERE k='owner'),'owner_revision_string_only_owner');
SELECT reader_test.ok(NOT ((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}') ? 'revision'),'public_no_revision');
INSERT INTO reader_test.saved SELECT 'writer',reader_test.call_as('authenticated','11111111-1111-4111-8111-111111111111',format('SELECT public.save_my_listing_basics_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',%L::jsonb,%L::jsonb,''{"kind":"fixed","amount":"9007199254740993.01","currency":"USD"}''::jsonb,%L);',v->'basics',v->'basics',v#>>'{price,revision}')) FROM reader_test.saved WHERE k='owner';
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='9007199254740993.01' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'currency'='USD','atomic_writer_exact_readback');
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')-'legacy_amount'=(SELECT (v#>'{snapshot,price}')-'revision' FROM reader_test.saved WHERE k='writer'),'atomic_writer_same_public_tuple');
SELECT reader_test.ok((SELECT v->>'basics_changed'='false' AND v->>'price_changed'='true' FROM reader_test.saved WHERE k='writer'),'atomic_writer_no_unrequested_basics');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''reader-alpha'');')#>'{items,0,currency}'='null'::jsonb,'v1_null_currency_after_new_writer');
UPDATE public.listings SET price_kind='free',price_amount=NULL,currency=NULL WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'kind'='free' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount'='null'::jsonb AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'currency'='null'::jsonb,'state_free_null_values');
UPDATE public.listings SET price_kind='negotiable',price_amount=NULL,currency=NULL WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'kind'='negotiable' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount'='null'::jsonb AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'currency'='null'::jsonb,'state_negotiable_null_values');
UPDATE public.listings SET price_kind='unspecified',price_amount=NULL,currency=NULL WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'kind'='unspecified' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'amount'='null'::jsonb AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->'currency'='null'::jsonb,'state_unspecified_null_values');
UPDATE public.listings SET price_kind='fixed',price_amount=0,currency='EUR' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'kind'='fixed' AND (reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='0','fixed_zero_not_free');
UPDATE public.listings SET price_kind='fixed',price_amount=12.50,currency='EUR' WHERE id=1001;
SELECT reader_test.ok((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')->>'amount'='12.5','normalized_writer_scale_no_display_rounding');
SELECT reader_test.ok((SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys((reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0,price}')) AS t(key))=ARRAY['amount','currency','kind','legacy_amount','legacy_text','version']::text[],'exact_price_keys');
SELECT reader_test.ok((SELECT array_agg(key ORDER BY key) FROM jsonb_object_keys(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>'{items,0}') t(key))=ARRAY['category','city','condition','content_id','content_type','country','created_at','description_preview','detail_category','image_url','price','seller_avatar_url','seller_name','seller_slug','seller_type','subcategory','title']::text[],'exact_public_card_keys');
SELECT reader_test.ok(strpos(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')::text,'SECRET_VIN')=0,'public_omits_91');
SELECT reader_test.ok(strpos(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')::text,'SECRET_DETAILS')=0,'public_omits_92');
SELECT reader_test.ok(strpos(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')::text,'SECRET_AI')=0,'public_omits_93');
SELECT reader_test.ok(strpos(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')::text,'SECRET_ADDRESS')=0,'public_omits_94');
SELECT reader_test.ok(strpos(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')::text,'SECRET_EMAIL')=0,'public_omits_95');
SELECT reader_test.ok(strpos(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')::text,'SECRET_PROFILE_ADDRESS')=0,'public_omits_96');
SELECT reader_test.ok(strpos(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')::text,'11111111-1111-4111-8111-111111111111')=0,'public_omits_97');
SELECT reader_test.ok(strpos(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')::text,'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')=0,'public_omits_98');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>>'{items,0,image_url}'='https://example.invalid/primary.jpg','primary_image_preserved');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')#>>'{items,0,seller_slug}'='seller-a','seller_preserved');
UPDATE public.listings SET status='paused' WHERE id=1001;
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')->>'total_count'='0','paused_excluded');
SELECT reader_test.ok(reader_test.call_as('authenticated','11111111-1111-4111-8111-111111111111','SELECT public.get_my_listing_basics_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'');')->>'listing_id'='1001','paused_owner_can_read');
UPDATE public.listings SET status='active' WHERE id=1001;
UPDATE public.listings SET status='sold' WHERE id=1001;
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')->>'total_count'='0','sold_excluded');
SELECT reader_test.ok(reader_test.call_as('authenticated','11111111-1111-4111-8111-111111111111','SELECT public.get_my_listing_basics_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'');')->>'listing_id'='1001','sold_owner_can_read');
UPDATE public.listings SET status='active' WHERE id=1001;
UPDATE public.listings SET active_until=now() WHERE id=1001;
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')->>'total_count'='0','exact_deadline_excluded');
UPDATE public.listings SET active_until=NULL WHERE id=1001;
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')->>'total_count'='1','legacy_null_expiry_matches_v1');
UPDATE public.listings SET active_until='2099-01-01T00:00:00Z' WHERE id=1001;
INSERT INTO public.user_blocks(id,blocker_id,blocked_id) VALUES(1,'11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222');
SELECT reader_test.ok(reader_test.call_as('authenticated','22222222-2222-4222-8222-222222222222','SELECT public.search_public_listings_v2(p_search_query=>'''');')->>'total_count'='1','block_direction_0');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('authenticated','22222222-2222-4222-8222-222222222222','SELECT public.search_public_listings_v1(p_search_query=>'''');'),reader_test.call_as('authenticated','22222222-2222-4222-8222-222222222222','SELECT public.search_public_listings_v2(p_search_query=>'''');')),'block_v1_parity_0');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''');')->>'total_count'='3','anonymous_unaffected_by_account_blocks_0');
DELETE FROM public.user_blocks;
INSERT INTO public.user_blocks(id,blocker_id,blocked_id) VALUES(2,'22222222-2222-4222-8222-222222222222','11111111-1111-4111-8111-111111111111');
SELECT reader_test.ok(reader_test.call_as('authenticated','22222222-2222-4222-8222-222222222222','SELECT public.search_public_listings_v2(p_search_query=>'''');')->>'total_count'='1','block_direction_1');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('authenticated','22222222-2222-4222-8222-222222222222','SELECT public.search_public_listings_v1(p_search_query=>'''');'),reader_test.call_as('authenticated','22222222-2222-4222-8222-222222222222','SELECT public.search_public_listings_v2(p_search_query=>'''');')),'block_v1_parity_1');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''');')->>'total_count'='3','anonymous_unaffected_by_account_blocks_1');
DELETE FROM public.user_blocks;
SELECT reader_test.ok(reader_test.error_as('authenticated','22222222-2222-4222-8222-222222222222','SELECT public.get_my_listing_basics_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'');','42501'),'wrong_owner_denied');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.get_my_listing_basics_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'');','42501'),'anonymous_owner_reader_denied');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>0);','22023'),'bad_filter_0');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>61);','22023'),'bad_filter_1');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>NULL);','22023'),'bad_filter_2');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_offset=>-1);','22023'),'bad_filter_3');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_offset=>100001);','22023'),'bad_filter_4');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_offset=>NULL);','22023'),'bad_filter_5');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_subcategory=>''cars'');','22023'),'bad_filter_6');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_detail_category=>''passenger_cars'');','22023'),'bad_filter_7');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_category=>''INVALID'');','22023'),'bad_filter_8');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_condition=>''other'');','22023'),'bad_filter_9');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_location_query=>repeat(''x'',161));','22023'),'bad_filter_10');
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'');','22023'),'query_limit_rejected');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_result_limit=>1,p_result_offset=>0);'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>1,p_result_offset=>0);')),'pagination_1_0_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_result_limit=>1,p_result_offset=>1);'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>1,p_result_offset=>1);')),'pagination_1_1_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_result_limit=>1,p_result_offset=>2);'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>1,p_result_offset=>2);')),'pagination_1_2_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_result_limit=>1,p_result_offset=>3);'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>1,p_result_offset=>3);')),'pagination_1_3_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_result_limit=>1,p_result_offset=>100000);'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>1,p_result_offset=>100000);')),'pagination_1_100000_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_result_limit=>60,p_result_offset=>0);'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>60,p_result_offset=>0);')),'pagination_60_0_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_result_limit=>24,p_result_offset=>0);'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_result_limit=>24,p_result_offset=>0);')),'pagination_24_0_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_category=>''vehicles'',p_subcategory=>''cars'',p_detail_category=>''passenger_cars'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_category=>''vehicles'',p_subcategory=>''cars'',p_detail_category=>''passenger_cars'');')),'filter_category_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_condition=>''used'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_condition=>''used'');')),'filter_condition_unchanged');
SELECT reader_test.ok(reader_test.same_nonprice(reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>'''',p_location_query=>''paide'');'),reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''',p_location_query=>''paide'');')),'filter_location_unchanged');
INSERT INTO public.listings(id,title,user_id,identity_id,created_at) VALUES (9223372036854775807,'id-boundary','11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','2026-01-01T00:00:00Z');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''id-boundary'');')#>>'{items,0,content_id}'='9223372036854775807','bigint_id_string');
INSERT INTO reader_test.saved VALUES('order',reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''');')->'items');
UPDATE public.listings SET price_kind='fixed',price_amount=999999999999999999.999,currency='KWD' WHERE id=1001;
SELECT reader_test.ok((SELECT jsonb_agg(x->'content_id' ORDER BY n) FROM jsonb_array_elements(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>'''');')->'items') WITH ORDINALITY t(x,n))=(SELECT jsonb_agg(x->'content_id' ORDER BY n) FROM reader_test.saved,jsonb_array_elements(v) WITH ORDINALITY t(x,n) WHERE k='order'),'price_change_no_ranking_bump');
DELETE FROM public.listings WHERE id=9223372036854775807;
SELECT reader_test.ok(reader_test.error_as('postgres','','SELECT public.listing_price_read_model_v1(''fixed'',1,''BAD'',1,''1 BAD'');','22023'),'corrupt_tuple_unknown_registry');
SELECT reader_test.ok(reader_test.error_as('postgres','','SELECT public.listing_price_read_model_v1(''fixed'',1,''EUR'',0,''1 EUR'');','22023'),'corrupt_tuple_missing_revision');
SELECT reader_test.ok(reader_test.error_as('postgres','','SELECT public.listing_price_read_model_v1(''free'',1,NULL,1,''Tasuta'');','22023'),'corrupt_tuple_stale_free_amount');
SELECT reader_test.ok(reader_test.error_as('postgres','','SELECT public.listing_price_read_model_v1(''fixed'',1,''EUR'',1,''wrong label'');','22023'),'corrupt_tuple_wrong_label');
INSERT INTO reader_test.saved VALUES('capture',jsonb_build_object('v1',reader_test.call_as('anon','','SELECT public.search_public_listings_v1(p_search_query=>''reader-alpha'');'),'v2',reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');'),'owner',reader_test.call_as('authenticated','11111111-1111-4111-8111-111111111111','SELECT public.get_my_listing_basics_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'');')));
SELECT reader_test.ok((SELECT to_jsonb(pg_get_functiondef('public.search_public_listings_v1(text,text,text,text,text,text,integer,integer)'::regprocedure))=(SELECT v FROM reader_test.saved WHERE k='v1def')),'v1_definition_still_exact');
SELECT reader_test.ok(to_jsonb((SELECT relacl::text FROM pg_class WHERE oid='public.listings'::regclass))=(SELECT v FROM reader_test.saved WHERE k='table_acl'),'legacy_table_acl_unchanged_not_fixed');
REVOKE SELECT ON public.listings FROM anon,authenticated,service_role;
SELECT reader_test.ok(reader_test.error_as('anon','','SELECT to_jsonb(id) FROM public.listings LIMIT 1;','42501'),'direct_read_denied_anon');
SELECT reader_test.ok(reader_test.call_as('anon','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')->>'total_count'='1','definer_without_table_select_anon');
SELECT reader_test.ok(reader_test.error_as('authenticated','','SELECT to_jsonb(id) FROM public.listings LIMIT 1;','42501'),'direct_read_denied_authenticated');
SELECT reader_test.ok(reader_test.call_as('authenticated','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')->>'total_count'='1','definer_without_table_select_authenticated');
SELECT reader_test.ok(reader_test.error_as('service_role','','SELECT to_jsonb(id) FROM public.listings LIMIT 1;','42501'),'direct_read_denied_service_role');
SELECT reader_test.ok(reader_test.call_as('service_role','','SELECT public.search_public_listings_v2(p_search_query=>''reader-alpha'');')->>'total_count'='1','definer_without_table_select_service_role');
GRANT SELECT ON public.listings TO anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.search_public_listings_v2(text,text,text,text,text,text,integer,integer) FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.get_my_listing_basics_v1(text,uuid), public.save_my_listing_basics_v1(text,uuid,jsonb,jsonb,jsonb,text) FROM PUBLIC,anon,authenticated,service_role;
SELECT reader_test.ok(NOT has_function_privilege('anon','public.search_public_listings_v2(text,text,text,text,text,text,integer,integer)','EXECUTE'),'anon_closed_after_suite');
SELECT reader_test.ok(NOT has_function_privilege('authenticated','public.search_public_listings_v2(text,text,text,text,text,text,integer,integer)','EXECUTE'),'authenticated_closed_after_suite');
SELECT reader_test.ok(NOT has_function_privilege('service_role','public.search_public_listings_v2(text,text,text,text,text,text,integer,integer)','EXECUTE'),'service_role_closed_after_suite');
SELECT v FROM reader_test.saved WHERE k='capture';
\echo PRICE_READ_SUITE=PASS
