-- NEW integration/authority assertions; not a replay of an earlier suite.
CREATE FUNCTION pg_temp.ok(p_value boolean,p_label text) RETURNS void LANGUAGE plpgsql AS $t$
BEGIN IF p_value IS DISTINCT FROM true THEN RAISE EXCEPTION 'RELEASE_ASSERT_FAILED:%',p_label; END IF;
 RAISE NOTICE 'RELEASE_PASS:%',p_label; END $t$;
CREATE FUNCTION pg_temp.fails(p_label text,p_sql text,p_state text,p_message text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY INVOKER AS $t$
DECLARE got_state text; got_message text;
BEGIN
 BEGIN EXECUTE p_sql;
 EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS got_state=RETURNED_SQLSTATE,got_message=MESSAGE_TEXT;
  IF got_state=p_state AND (p_message IS NULL OR got_message=p_message) THEN
   RAISE NOTICE 'RELEASE_PASS:%',p_label; RETURN;
  END IF;
  RAISE EXCEPTION 'RELEASE_WRONG_ERROR:% state=% message=%',p_label,got_state,got_message;
 END;
 RAISE EXCEPTION 'RELEASE_EXPECTED_REJECTION:%',p_label;
END $t$;
CREATE FUNCTION pg_temp.capture(p_label text,p_value jsonb) RETURNS void LANGUAGE plpgsql AS $t$
BEGIN RAISE NOTICE 'RELEASE_CAPTURE:%:%',p_label,p_value::text; END $t$;
CREATE TEMP TABLE keep(id bigint PRIMARY KEY,value jsonb);
INSERT INTO keep SELECT id,to_jsonb(l) FROM public.listings l;
GRANT SELECT ON keep TO authenticated;
-- V2 dependency regression: preserve source, privacy and wanted-budget meaning.
CREATE FUNCTION pg_temp.dependency_ok(v boolean,label text) RETURNS void LANGUAGE plpgsql AS $dep$
BEGIN
  IF v IS DISTINCT FROM true THEN RAISE EXCEPTION 'RELEASE_DEPENDENCY_FAILED:%',label; END IF;
  RAISE NOTICE 'RELEASE_DEPENDENCY_PASS:%',label;
END $dep$;
SELECT pg_temp.dependency_ok((SELECT proowner='postgres'::regrole AND prorettype='jsonb'::regtype AND provolatile='i' AND NOT prosecdef AND proconfig=ARRAY['search_path=pg_catalog, pg_temp']::text[] AND prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql') FROM pg_proc WHERE oid='public.project_horse_wanted_owner_summary_v1(jsonb)'::regprocedure),'wanted_dependency_signature_config');
SELECT pg_temp.dependency_ok((SELECT md5(prosrc)='94d8612d4e56443696eca44a0406cc4b' FROM pg_proc WHERE oid='public.project_horse_wanted_owner_summary_v1(jsonb)'::regprocedure),'wanted_dependency_body_exact');
SELECT pg_temp.dependency_ok((NOT has_function_privilege('anon','public.project_horse_wanted_owner_summary_v1(jsonb)','EXECUTE') AND NOT has_function_privilege('authenticated','public.project_horse_wanted_owner_summary_v1(jsonb)','EXECUTE') AND NOT has_function_privilege('service_role','public.project_horse_wanted_owner_summary_v1(jsonb)','EXECUTE') AND NOT EXISTS(SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a WHERE p.oid='public.project_horse_wanted_owner_summary_v1(jsonb)'::regprocedure AND a.grantee=0 AND a.privilege_type='EXECUTE')),'wanted_dependency_private_acl');
SELECT pg_temp.dependency_ok((public.project_horse_wanted_owner_summary_v1('{"schema_version":1,"branch":"wanted","wanted":{"budget":{"mode":"maximum","amount":5000,"currency":"EUR"},"search_area":{"country_code":"EE","city_or_municipality":"Rapla","region":null},"private_extra":"never_export"},"private_extra":"never_export"}'::jsonb)='{"version":1,"budget":{"mode":"maximum","amount":5000,"currency":"EUR"},"search_area":{"country_code":"EE","city_or_municipality":"Rapla","region":null}}'::jsonb),'wanted_dependency_original_whitelist');
SELECT pg_temp.dependency_ok((public.project_horse_wanted_owner_summary_v2('{"schema_version":1,"branch":"wanted","wanted":{"budget":{"mode":"maximum","amount":5000,"currency":"EUR"},"search_area":{"country_code":"EE","city_or_municipality":"Rapla","region":null},"private_extra":"never_export"},"private_extra":"never_export"}'::jsonb)='{"version":2,"budget":{"mode":"maximum","amount":"5000","currency":"EUR"},"search_area":{"country_code":"EE","city_or_municipality":"Rapla","region":null}}'::jsonb),'wanted_dependency_text_projection');
SELECT pg_temp.dependency_ok((public.project_horse_wanted_owner_summary_v1('{"schema_version":1,"branch":"wanted","wanted":{"budget":{"mode":"maximum","amount":"5000","currency":"EUR"}}}'::jsonb)='{"version":1,"budget":null,"search_area":null}'::jsonb AND public.project_horse_wanted_owner_summary_v2('{"schema_version":1,"branch":"wanted","wanted":{"budget":{"mode":"maximum","amount":"5000","currency":"EUR"}}}'::jsonb)='{"version":2,"budget":null,"search_area":null}'::jsonb),'wanted_dependency_invalid_budget_not_reinterpreted');
-- END V2 dependency regressions; original 77 assertions continue unchanged.
SELECT pg_temp.ok((SELECT NOT (rolsuper OR rolcanlogin OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls OR rolinherit) FROM pg_roles WHERE rolname='selqiro_listing_price_writer_v1'),'dedicated_role_no_login_no_bypass');
SELECT pg_temp.ok((SELECT count(*)=1 AND bool_and(member::regrole::text='postgres' AND admin_option AND inherit_option AND set_option) FROM pg_auth_members WHERE roleid='selqiro_listing_price_writer_v1'::regrole),'only_trusted_admin_membership');
SELECT pg_temp.ok((NOT pg_has_role('anon','selqiro_listing_price_writer_v1','SET')),'anon_cannot_set_writer');
SELECT pg_temp.ok((NOT has_function_privilege('anon','public.set_my_listing_price_core_v1(text,uuid,text,jsonb)','EXECUTE')),'anon_cannot_execute_private_core');
SELECT pg_temp.ok((NOT has_function_privilege('anon','public.lock_my_listing_basics_v1(text,uuid,boolean)','EXECUTE')),'anon_cannot_execute_private_locker');
SELECT pg_temp.ok((NOT pg_has_role('authenticated','selqiro_listing_price_writer_v1','SET')),'authenticated_cannot_set_writer');
SELECT pg_temp.ok((NOT has_function_privilege('authenticated','public.set_my_listing_price_core_v1(text,uuid,text,jsonb)','EXECUTE')),'authenticated_cannot_execute_private_core');
SELECT pg_temp.ok((NOT has_function_privilege('authenticated','public.lock_my_listing_basics_v1(text,uuid,boolean)','EXECUTE')),'authenticated_cannot_execute_private_locker');
SELECT pg_temp.ok((NOT pg_has_role('service_role','selqiro_listing_price_writer_v1','SET')),'service_role_cannot_set_writer');
SELECT pg_temp.ok((NOT has_function_privilege('service_role','public.set_my_listing_price_core_v1(text,uuid,text,jsonb)','EXECUTE')),'service_role_cannot_execute_private_core');
SELECT pg_temp.ok((NOT has_function_privilege('service_role','public.lock_my_listing_basics_v1(text,uuid,boolean)','EXECUTE')),'service_role_cannot_execute_private_locker');
SELECT pg_temp.ok((SELECT array_agg(attname::text ORDER BY attname)=ARRAY['currency','price_amount','price_kind']::text[] FROM pg_attribute WHERE attrelid='public.listings'::regclass AND attnum>0 AND NOT attisdropped AND has_column_privilege('selqiro_listing_price_writer_v1','public.listings',attname,'UPDATE')),'writer_only_price_column_updates');
SELECT pg_temp.ok((NOT has_table_privilege('selqiro_listing_price_writer_v1','public.listings','UPDATE') AND NOT has_table_privilege('selqiro_listing_price_writer_v1','public.listings','INSERT') AND NOT has_table_privilege('selqiro_listing_price_writer_v1','public.listings','DELETE') AND NOT has_table_privilege('selqiro_listing_price_writer_v1','public.listings','TRUNCATE')),'writer_no_broad_write');
SELECT pg_temp.ok((NOT has_schema_privilege('selqiro_listing_price_writer_v1','public','CREATE') AND NOT has_schema_privilege('selqiro_listing_price_writer_v1','auth','USAGE')),'writer_no_schema_create_or_auth_usage');
SELECT pg_temp.ok((NOT has_table_privilege('selqiro_listing_price_writer_v1','public.profiles','SELECT') AND NOT has_table_privilege('selqiro_listing_price_writer_v1','public.identities','SELECT') AND NOT has_table_privilege('selqiro_listing_price_writer_v1','public.business_members','SELECT')),'writer_no_identity_table_read');
SELECT pg_temp.ok((SELECT count(*)=1 AND bool_and(proname='set_my_listing_price_core_v1' AND prosecdef) FROM pg_proc WHERE proowner='selqiro_listing_price_writer_v1'::regrole),'only_core_owned_by_writer');
SELECT pg_temp.ok((SELECT prosecdef AND proowner='postgres'::regrole FROM pg_proc WHERE oid='public.lock_my_listing_basics_v1(text,uuid,boolean)'::regprocedure),'locker_definer_postgres');
SELECT pg_temp.ok((NOT has_function_privilege('anon','public.get_my_listing_edit_v1(text,uuid,uuid)','EXECUTE') AND NOT has_function_privilege('anon','public.save_my_listing_edit_v1(text,uuid,uuid,jsonb,jsonb,jsonb,text)','EXECUTE')),'anon_no_edit_grant');
SELECT pg_temp.ok((NOT has_function_privilege('service_role','public.get_my_listing_edit_v1(text,uuid,uuid)','EXECUTE') AND NOT has_function_privilege('service_role','public.save_my_listing_edit_v1(text,uuid,uuid,jsonb,jsonb,jsonb,text)','EXECUTE')),'service_role_no_edit_grant');
SELECT pg_temp.ok((has_function_privilege('authenticated','public.get_my_listing_edit_v1(text,uuid,uuid)','EXECUTE') AND has_function_privilege('authenticated','public.save_my_listing_edit_v1(text,uuid,uuid,jsonb,jsonb,jsonb,text)','EXECUTE')),'authenticated_exact_edit_access');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','',true),set_config('request.jwt.claim.role','anon',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE anon;
SELECT pg_temp.fails('anon_read_denied','SELECT public.get_my_listing_edit_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'')','42501',NULL);
SELECT pg_temp.fails('anon_write_denied','SELECT public.save_my_listing_edit_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'',''{"title":"Original A","description":"Description","condition":"used"}''::jsonb,''{"title":"Original A","description":"Description","condition":"used"}''::jsonb,''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb,''0'')','42501',NULL);
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','',true),set_config('request.jwt.claim.role','authenticated',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.fails('missing_jwt_denied','SELECT public.get_my_listing_edit_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'')','42501','listing_edit_actor_changed');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true),set_config('request.jwt.claim.role','authenticated',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.fails('wrong_expected_actor_denied','SELECT public.get_my_listing_edit_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''22222222-2222-4222-8222-222222222222'')','42501','listing_edit_actor_changed');
SELECT pg_temp.fails('wrong_identity_denied','SELECT public.get_my_listing_edit_v1(''1001'',''bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'',''11111111-1111-4111-8111-111111111111'')','42501','listing_price_identity_changed');
SELECT pg_temp.fails('other_listing_denied','SELECT public.get_my_listing_edit_v1(''1002'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'')','42501','listing_price_not_found_or_forbidden');
SELECT pg_temp.fails('unassigned_listing_denied','SELECT public.get_my_listing_edit_v1(''1004'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'')','42501','listing_price_not_found_or_forbidden');
SELECT pg_temp.capture('raw_editor',public.get_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111'));
SELECT pg_temp.ok((public.get_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111')#>'{snapshot,basics}'='{"title":"Original A","description":"Description","condition":"used"}'::jsonb AND public.get_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111')#>>'{snapshot,price,legacy_text}'='5578'),'raw_editor_exact_baseline');
SELECT pg_temp.capture('saved_max',public.save_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"title":"Original A","description":"Description","condition":"used"}'::jsonb,'{"title":"Release truck","description":"Description","condition":"used"}'::jsonb,'{"kind":"fixed","amount":"999999999999999999.999","currency":"KWD"}'::jsonb,'0'));
SELECT pg_temp.ok((SELECT price_kind='fixed' AND price_amount::text='999999999999999999.999' AND currency='KWD' AND price_revision=1 AND price='999999999999999999.999 KWD' FROM public.listings WHERE id=1001),'dedicated_writer_price_and_revision');
SELECT pg_temp.capture('max_editor',public.get_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111'));
SELECT pg_temp.ok((SELECT (to_jsonb(l)-ARRAY['title','price','price_kind','price_amount','currency','price_revision','search_text','search_vector','updated_by_user_id'])=(k.value-ARRAY['title','price','price_kind','price_amount','currency','price_revision','search_text','search_vector','updated_by_user_id']) FROM public.listings l JOIN keep k USING(id) WHERE id=1001),'conversion_unrelated_columns_preserved');
SELECT pg_temp.ok(((public.save_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"title":"Release truck","description":"Description","condition":"used"}'::jsonb,'{"title":"Release truck","description":"Description","condition":"used"}'::jsonb,'{"kind":"fixed","amount":"999999999999999999.999","currency":"KWD"}'::jsonb,'1')->>'price_changed')::boolean=false),'noop_does_not_increment');
SELECT pg_temp.fails('legacy_structured_price_blocked','UPDATE public.listings SET price=''9'',price_amount=9,title=''Lost'' WHERE id=1001','42501','listing_price_direct_write_forbidden');
SELECT pg_temp.fails('currency_change_blocked','UPDATE public.listings SET currency=''EUR'' WHERE id=1001','42501','listing_price_direct_write_forbidden');
SELECT pg_temp.fails('downgrade_blocked','UPDATE public.listings SET price_kind=NULL,currency=NULL,price_amount=0,price=''0'' WHERE id=1001','42501','listing_price_downgrade_forbidden');
SELECT pg_temp.fails('manual_revision_blocked','UPDATE public.listings SET price_revision=0 WHERE id=1001','42501','listing_price_revision_server_owned');
SELECT pg_temp.fails('structured_owner_rebind_blocked','UPDATE public.listings SET identity_id=''dddddddd-dddd-4ddd-8ddd-dddddddddddd'' WHERE id=1001','42501','listing_price_owner_tuple_immutable');
SELECT pg_temp.fails('structured_delete_blocked','DELETE FROM public.listings WHERE id=1001','42501','listing_price_direct_delete_forbidden');
SELECT pg_temp.fails('truncate_blocked','TRUNCATE public.listings','42501','listing_price_direct_truncate_forbidden');
SELECT pg_temp.ok((SELECT title='Release truck' AND price_revision=1 FROM public.listings WHERE id=1001),'rejected_legacy_write_also_preserved_title');
SELECT set_config('selqiro.price_write','true',true),set_config('request.jwt.claim.role','service_role',true);
SELECT pg_temp.fails('spoofed_flags_not_authority','UPDATE public.listings SET price=''1'',price_amount=1 WHERE id=1001','42501','listing_price_direct_write_forbidden');
SELECT set_config('request.jwt.claim.role','authenticated',true);
RESET ROLE;
CREATE FUNCTION public.synthetic_unsafe_price_writer() RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $s$ BEGIN UPDATE public.listings SET price='8',price_amount=8 WHERE id=1001; END $s$; GRANT EXECUTE ON FUNCTION public.synthetic_unsafe_price_writer() TO authenticated;
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true),set_config('request.jwt.claim.role','authenticated',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.fails('postgres_owned_definer_cannot_bypass','SELECT public.synthetic_unsafe_price_writer()','42501','listing_price_direct_write_forbidden');
SELECT pg_temp.fails('stale_price_rolls_back_whole_save','SELECT public.save_my_listing_edit_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'',''{"title":"Release truck","description":"Description","condition":"used"}''::jsonb,''{"title":"Must not save","description":"Description","condition":"used"}''::jsonb,''{"kind":"fixed","amount":"20","currency":"EUR"}''::jsonb,''0'')','40001','listing_price_conflict');
SELECT pg_temp.ok((SELECT title='Release truck' AND price_revision=1 AND price_amount::text='999999999999999999.999' FROM public.listings WHERE id=1001),'after_conflict_exact_title_money');
SELECT pg_temp.fails('stale_basics_rejects_price_too','SELECT public.save_my_listing_edit_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'',''{"title":"Original A","description":"Description","condition":"used"}''::jsonb,''{"title":"Original A","description":"Description","condition":"used"}''::jsonb,''{"kind":"fixed","amount":"20","currency":"EUR"}''::jsonb,''1'')','40001','listing_basics_conflict');
SELECT pg_temp.capture('search_max',public.search_public_listings_v2('Release truck'));
SELECT pg_temp.capture('legacy_search_max',public.search_public_listings_v1('Release truck'));
SELECT pg_temp.ok((public.search_public_listings_v1('Release truck')#>>'{items,0,price}'='999999999999999999.999 KWD' AND public.search_public_listings_v1('Release truck')#>'{items,0,currency}'='null'::jsonb),'legacy_search_keeps_explicit_raw_label');
SELECT pg_temp.capture('detail_max',public.get_public_listing_detail_v1('1001'));
SELECT pg_temp.capture('profile_max',public.get_public_profile_listings_v1('release-a',NULL,12,0));
SELECT pg_temp.capture('owner_max',public.get_my_marketplace_items_v3('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',30,0,'all','',NULL));
DO $t$ DECLARE d jsonb;s jsonb;p jsonb;o jsonb; BEGIN
 d:=public.get_public_listing_detail_v1('1001')->'item'->'price';
 s:=public.search_public_listings_v2('Release truck')->'items'->0->'price';
 SELECT e->'price' INTO p FROM jsonb_array_elements(public.get_public_profile_listings_v1('release-a',NULL,12,0)->'items')e WHERE e->>'content_id'='1001';
 SELECT e->'money'->'value' INTO o FROM jsonb_array_elements(public.get_my_marketplace_items_v3('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',30,0,'all','',NULL)->'items')e WHERE e->>'content_id'='1001';
 PERFORM pg_temp.ok(d=s AND d=p AND d=o AND NOT(d?'revision'),'four_surfaces_exact_same_price');
END $t$;
SELECT pg_temp.capture('changed_price',public.save_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"title":"Release truck","description":"Description","condition":"used"}'::jsonb,'{"title":"Release truck","description":"Description","condition":"used"}'::jsonb,'{"kind":"fixed","amount":"91.5","currency":"USD"}'::jsonb,'1'));
SELECT pg_temp.capture('basics_omits_price',public.save_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"title":"Release truck","description":"Description","condition":"used"}'::jsonb,'{"title":"Release revised","description":"Description","condition":"used"}'::jsonb,NULL,NULL));
SELECT pg_temp.ok((SELECT price_amount::text='91.5' AND currency='USD' AND price_revision=2 AND title='Release revised' FROM public.listings WHERE id=1001),'omitted_price_keeps_latest');
RESET ROLE; DELETE FROM keep; INSERT INTO keep SELECT id,to_jsonb(l) FROM public.listings l;
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true),set_config('request.jwt.claim.role','authenticated',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE authenticated;
SELECT public.add_listing_image_v2('1001','https://example.invalid/two.jpg','https://example.invalid/two-m.jpg','https://example.invalid/two-t.jpg',10);
RESET ROLE; SELECT set_config('release.test_image_id',(SELECT id::text FROM public.listing_images WHERE listing_id=1001 AND original_url='https://example.invalid/two.jpg'),true); SET LOCAL ROLE authenticated;
SELECT public.set_listing_primary_image_v2('1001',current_setting('release.test_image_id'));
SELECT public.delete_listing_image_v2('1001',current_setting('release.test_image_id'));
SELECT pg_temp.ok((SELECT ROW(l.price,l.price_kind,l.price_amount::text,l.currency,l.price_revision::text)=ROW(k.value->>'price',k.value->>'price_kind',k.value->>'price_amount',k.value->>'currency',k.value->>'price_revision') FROM public.listings l JOIN keep k USING(id) WHERE id=1001),'three_real_image_writers_preserve_money');
SELECT public.update_my_listing_classification_location_v2('1001','vehicles','trucks_commercial','trucks','Estonia','Türi',NULL,NULL);
SELECT public.set_my_listing_store_categories_v2('1001',ARRAY['a0000000-0000-4000-8000-000000000002'::uuid]);
SELECT pg_temp.ok((SELECT ROW(l.price,l.price_kind,l.price_amount::text,l.currency,l.price_revision::text)=ROW(k.value->>'price',k.value->>'price_kind',k.value->>'price_amount',k.value->>'currency',k.value->>'price_revision') FROM public.listings l JOIN keep k USING(id) WHERE id=1001),'classification_and_store_keep_money');
SELECT public.renew_my_listing_activity_v1('1001',(SELECT active_until FROM public.listings WHERE id=1001));
SELECT pg_temp.ok((SELECT l.price=k.value->>'price' AND l.price_revision::text=k.value->>'price_revision' AND l.created_at=(k.value->>'created_at')::timestamptz AND l.active_until>(k.value->>'active_until')::timestamptz FROM public.listings l JOIN keep k USING(id) WHERE id=1001),'renewal_keeps_money_and_created_at');
UPDATE public.listings SET status='paused' WHERE id=1001;
SELECT pg_temp.ok((SELECT status='paused' AND price_revision=2 FROM public.listings WHERE id=1001),'legacy_status_change_allowed');
SELECT pg_temp.ok((public.get_public_listing_detail_v1('1001')->'item'='null'::jsonb),'paused_public_detail_hidden');
UPDATE public.listings SET status='active' WHERE id=1001;
INSERT INTO public.listings(id,user_id,identity_id,title,price,price_amount) VALUES(1010,'11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Legacy create','7',7);
UPDATE public.listings SET price='8',price_amount=8 WHERE id=1010;
SELECT pg_temp.ok((SELECT price_kind IS NULL AND currency IS NULL AND price_revision=1 AND price='8' FROM public.listings WHERE id=1010),'legacy_raw_create_edit_increments');
DELETE FROM public.listings WHERE id=1010;
SELECT pg_temp.ok((NOT EXISTS(SELECT 1 FROM public.listings WHERE id=1010)),'legacy_raw_delete_still_allowed');
SELECT pg_temp.fails('structured_direct_insert_closed','INSERT INTO public.listings(id,user_id,identity_id,title,price_kind,price_amount,currency) VALUES(1011,''11111111-1111-4111-8111-111111111111'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''Do not create'',''fixed'',1,''EUR'')','42501','listing_price_structured_create_not_enabled');
UPDATE public.listings SET title='Legacy title only' WHERE id=1001;
SELECT pg_temp.ok((SELECT title='Legacy title only' AND price_revision=2 FROM public.listings WHERE id=1001),'legacy_title_only_keeps_price');
SELECT pg_temp.capture('saved_free',public.save_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"title":"Legacy title only","description":"Description","condition":"used"}'::jsonb,'{"title":"Legacy title only","description":"Description","condition":"used"}'::jsonb,'{"kind":"free","amount":null,"currency":null}'::jsonb,'2'));
SELECT pg_temp.ok((SELECT price_kind='free' AND price_amount IS NULL AND currency IS NULL AND price_revision=3 FROM public.listings WHERE id=1001),'free_tuple');
SELECT pg_temp.capture('saved_negotiable',public.save_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"title":"Legacy title only","description":"Description","condition":"used"}'::jsonb,'{"title":"Legacy title only","description":"Description","condition":"used"}'::jsonb,'{"kind":"negotiable","amount":null,"currency":null}'::jsonb,'3'));
SELECT pg_temp.ok((SELECT price_kind='negotiable' AND price_amount IS NULL AND currency IS NULL AND price_revision=4 FROM public.listings WHERE id=1001),'negotiable_tuple');
SELECT pg_temp.capture('saved_unspecified',public.save_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"title":"Legacy title only","description":"Description","condition":"used"}'::jsonb,'{"title":"Legacy title only","description":"Description","condition":"used"}'::jsonb,'{"kind":"unspecified","amount":null,"currency":null}'::jsonb,'4'));
SELECT pg_temp.ok((SELECT price_kind='unspecified' AND price_amount IS NULL AND currency IS NULL AND price_revision=5 FROM public.listings WHERE id=1001),'unspecified_tuple');
SELECT pg_temp.capture('saved_zero',public.save_my_listing_edit_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','{"title":"Legacy title only","description":"Description","condition":"used"}'::jsonb,'{"title":"Legacy title only","description":"Description","condition":"used"}'::jsonb,'{"kind":"fixed","amount":"0","currency":"JPY"}'::jsonb,'5'));
SELECT pg_temp.ok((SELECT price_kind='fixed' AND price_amount=0 AND currency='JPY' AND price_revision=6 FROM public.listings WHERE id=1001),'zero_is_fixed');
SELECT pg_temp.fails('excess_scale_no_rounding','SELECT public.save_my_listing_edit_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'',''{"title":"Legacy title only","description":"Description","condition":"used"}''::jsonb,''{"title":"Legacy title only","description":"Description","condition":"used"}''::jsonb,''{"kind":"fixed","amount":"0.5","currency":"JPY"}''::jsonb,''6'')','22023','listing_price_amount_invalid');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true),set_config('request.jwt.claim.role','authenticated',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.fails('same_business_wrong_actor_denied','SELECT public.get_my_listing_edit_v1(''1003'',''cccccccc-cccc-4ccc-8ccc-cccccccccccc'',''44444444-4444-4444-8444-444444444444'')','42501','listing_edit_actor_changed');
SELECT pg_temp.capture('business_saved',public.save_my_listing_edit_v1('1003','cccccccc-cccc-4ccc-8ccc-cccccccccccc','33333333-3333-4333-8333-333333333333','{"title":"Business listing","description":"Biz","condition":"used"}'::jsonb,'{"title":"Business changed","description":"Biz","condition":"used"}'::jsonb,'{"kind":"fixed","amount":"20","currency":"EUR"}'::jsonb,'0'));
SELECT pg_temp.ok((SELECT updated_by_user_id=auth.uid() AND price_revision=1 FROM public.listings WHERE id=1003),'business_true_actor_recorded');
RESET ROLE; UPDATE public.business_members SET status='inactive' WHERE user_id='33333333-3333-4333-8333-333333333333';
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true),set_config('request.jwt.claim.role','authenticated',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.fails('revoked_member_rejected','SELECT public.get_my_listing_edit_v1(''1003'',''cccccccc-cccc-4ccc-8ccc-cccccccccccc'',''33333333-3333-4333-8333-333333333333'')','42501','listing_price_identity_forbidden');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','44444444-4444-4444-8444-444444444444',true),set_config('request.jwt.claim.role','authenticated',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.capture('business_other_member_read',public.get_my_listing_edit_v1('1003','cccccccc-cccc-4ccc-8ccc-cccccccccccc','44444444-4444-4444-8444-444444444444'));
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true),set_config('request.jwt.claim.role','service_role',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE service_role;
SELECT pg_temp.fails('service_role_no_edit_api','SELECT public.get_my_listing_edit_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''11111111-1111-4111-8111-111111111111'')','42501',NULL);
SELECT pg_temp.fails('service_role_direct_structured_denied','UPDATE public.listings SET price=''2'',price_amount=2 WHERE id=1001','42501','listing_price_direct_write_forbidden');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','',true),set_config('request.jwt.claim.role','anon',true),set_config('request.jwt.claims','',true);
SET LOCAL ROLE anon;
SELECT pg_temp.capture('anonymous_zero_detail',public.get_public_listing_detail_v1('1001'));
SELECT pg_temp.ok((public.get_public_listing_detail_v1('1001')#>>'{item,price,kind}'='fixed' AND public.get_public_listing_detail_v1('1001')#>>'{item,price,amount}'='0'),'anonymous_exact_zero_not_free');
RESET ROLE;
SELECT pg_temp.ok((EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.add_listing_image_v2(text,text,text,text,integer)'::regprocedure AND prosecdef AND proowner='postgres'::regrole)),'legacy_api_bodies_preserved_not_replaced');
SELECT pg_temp.ok((SELECT md5(prosrc)='0517a60533710ee1794d7649f5295471' FROM pg_proc WHERE oid='public.add_listing_image_v2(text,text,text,text,integer)'::regprocedure),'retained_body_add_listing_image_v2');
SELECT pg_temp.ok((SELECT md5(prosrc)='9ba2f60e30530f76164012c329448fa2' FROM pg_proc WHERE oid='public.delete_listing_image_v2(text,text)'::regprocedure),'retained_body_delete_listing_image_v2');
SELECT pg_temp.ok((SELECT md5(prosrc)='6423eb6fc715090238b5af147dd632a5' FROM pg_proc WHERE oid='public.set_listing_primary_image_v2(text,text)'::regprocedure),'retained_body_set_listing_primary_image_v2');
SELECT pg_temp.ok((SELECT md5(prosrc)='d9790dfb4d21f965e69192c929f5c8e1' FROM pg_proc WHERE oid='public.update_my_listing_classification_location_v2(text,text,text,text,text,text,double precision,double precision)'::regprocedure),'retained_body_update_my_listing_classification_location_v2');
SELECT pg_temp.ok((SELECT md5(prosrc)='c6f7c0e56ccc5fe831b9da6b2c4ad057' FROM pg_proc WHERE oid='public.set_my_listing_store_categories_v2(text,uuid[])'::regprocedure),'retained_body_set_my_listing_store_categories_v2');
SELECT pg_temp.ok((NOT has_column_privilege('selqiro_listing_price_writer_v1','public.listings','title','UPDATE')),'writer_cannot_update_title');
SELECT pg_temp.ok((NOT has_column_privilege('selqiro_listing_price_writer_v1','public.listings','price_revision','UPDATE')),'writer_cannot_update_revision');
SELECT pg_temp.ok((NOT has_column_privilege('selqiro_listing_price_writer_v1','public.listings','price','UPDATE')),'writer_cannot_update_raw_label');
SELECT pg_temp.ok((NOT has_column_privilege('selqiro_listing_price_writer_v1','public.listings','identity_id','UPDATE')),'writer_cannot_update_identity');
DO $t$ BEGIN RAISE NOTICE 'RELEASE_SUITE_COMPLETE'; END $t$;
