-- CLOSED LOCAL DISPLAY REGISTRY, independently derived from the current category form.
-- Not the FTS allowlist. Changing this helper never changes the search index.
CREATE FUNCTION public.public_listing_detail_field_spec_v1(p_path text[])
RETURNS jsonb LANGUAGE sql IMMUTABLE PARALLEL SAFE
SET search_path=pg_catalog,pg_temp
AS $fn$
  SELECT CASE p_path
    WHEN ARRAY['vehicles','cars','passenger_cars']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"generation","label":"Generation / body code"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"drivetrain","label":"Drivetrain"},{"key":"mileage","label":"Mileage"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"body_type","label":"Body type"},{"key":"doors","label":"Number of doors"},{"key":"seats","label":"Seats"},{"key":"color","label":"Color"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','cars','suv_offroad']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"generation","label":"Generation / body code"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"drivetrain","label":"Drivetrain"},{"key":"mileage","label":"Mileage"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"body_type","label":"Body type"},{"key":"doors","label":"Number of doors"},{"key":"seats","label":"Seats"},{"key":"color","label":"Color"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','cars','vans_minibuses']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"generation","label":"Generation / body code"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"drivetrain","label":"Drivetrain"},{"key":"mileage","label":"Mileage"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"body_type","label":"Body type"},{"key":"doors","label":"Number of doors"},{"key":"seats","label":"Seats"},{"key":"color","label":"Color"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','cars','pickup_trucks']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"generation","label":"Generation / body code"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"drivetrain","label":"Drivetrain"},{"key":"mileage","label":"Mileage"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"body_type","label":"Body type"},{"key":"doors","label":"Number of doors"},{"key":"seats","label":"Seats"},{"key":"color","label":"Color"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','cars','motorhomes_campers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"generation","label":"Generation / body code"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"drivetrain","label":"Drivetrain"},{"key":"mileage","label":"Mileage"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"body_type","label":"Body type"},{"key":"doors","label":"Number of doors"},{"key":"seats","label":"Seats"},{"key":"color","label":"Color"},{"key":"inspection_valid_until","label":"Inspection valid until"},{"key":"sleeping_places","label":"Sleeping places"},{"key":"length","label":"Length"},{"key":"gross_weight","label":"Gross weight"},{"key":"equipment","label":"Equipment"}]'::jsonb
    WHEN ARRAY['vehicles','cars','racing_vehicles']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"generation","label":"Generation / body code"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"drivetrain","label":"Drivetrain"},{"key":"mileage","label":"Mileage"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"body_type","label":"Body type"},{"key":"doors","label":"Number of doors"},{"key":"seats","label":"Seats"},{"key":"color","label":"Color"},{"key":"inspection_valid_until","label":"Inspection valid until"},{"key":"discipline","label":"Discipline"},{"key":"roll_cage","label":"Roll cage"},{"key":"homologation","label":"Homologation"},{"key":"track_street_legal","label":"Track / street legal"}]'::jsonb
    WHEN ARRAY['vehicles','motorcycles','sport_bikes']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"engine_size","label":"Engine size"},{"key":"power","label":"Power"},{"key":"fuel","label":"Fuel"},{"key":"mileage","label":"Mileage"},{"key":"transmission","label":"Transmission"},{"key":"type","label":"Type"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','motorcycles','cruisers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"engine_size","label":"Engine size"},{"key":"power","label":"Power"},{"key":"fuel","label":"Fuel"},{"key":"mileage","label":"Mileage"},{"key":"transmission","label":"Transmission"},{"key":"type","label":"Type"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','motorcycles','touring']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"engine_size","label":"Engine size"},{"key":"power","label":"Power"},{"key":"fuel","label":"Fuel"},{"key":"mileage","label":"Mileage"},{"key":"transmission","label":"Transmission"},{"key":"type","label":"Type"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','motorcycles','enduro_mx']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"engine_size","label":"Engine size"},{"key":"power","label":"Power"},{"key":"fuel","label":"Fuel"},{"key":"mileage","label":"Mileage"},{"key":"transmission","label":"Transmission"},{"key":"type","label":"Type"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','motorcycles','scooters']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"engine_size","label":"Engine size"},{"key":"power","label":"Power"},{"key":"fuel","label":"Fuel"},{"key":"mileage","label":"Mileage"},{"key":"transmission","label":"Transmission"},{"key":"type","label":"Type"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','motorcycles','atv_utv']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"engine_size","label":"Engine size"},{"key":"power","label":"Power"},{"key":"fuel","label":"Fuel"},{"key":"mileage","label":"Mileage"},{"key":"transmission","label":"Transmission"},{"key":"type","label":"Type"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"},{"key":"drivetrain","label":"Drivetrain"},{"key":"winch","label":"Winch"},{"key":"road_legal","label":"Road legal"}]'::jsonb
    WHEN ARRAY['vehicles','motorcycles','snowmobiles']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"engine_size","label":"Engine size"},{"key":"power","label":"Power"},{"key":"mileage","label":"Mileage"},{"key":"track_length","label":"Track length"},{"key":"electric_start","label":"Electric start"}]'::jsonb
    WHEN ARRAY['vehicles','trucks_commercial','trucks']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"mileage","label":"Mileage"},{"key":"seats","label":"Seats"},{"key":"axle_configuration","label":"Axle configuration"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"load_space_length","label":"Load space length"},{"key":"load_space_width","label":"Load space width"},{"key":"load_space_height","label":"Load space height"},{"key":"tachograph","label":"Tachograph"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','trucks_commercial','semi_trucks']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"mileage","label":"Mileage"},{"key":"seats","label":"Seats"},{"key":"axle_configuration","label":"Axle configuration"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"load_space_length","label":"Load space length"},{"key":"load_space_width","label":"Load space width"},{"key":"load_space_height","label":"Load space height"},{"key":"tachograph","label":"Tachograph"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','trucks_commercial','buses']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"gearbox","label":"Gearbox"},{"key":"mileage","label":"Mileage"},{"key":"seats","label":"Seats"},{"key":"axle_configuration","label":"Axle configuration"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"load_space_length","label":"Load space length"},{"key":"load_space_width","label":"Load space width"},{"key":"load_space_height","label":"Load space height"},{"key":"tachograph","label":"Tachograph"},{"key":"vin","label":"VIN"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','trucks_commercial','commercial_trailers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"trailer_type","label":"Trailer type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"height","label":"Height"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"axles","label":"Axles"},{"key":"brake_type","label":"Brake type"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','agricultural_heavy_machinery','tractors']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"machine_type","label":"Machine type"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"working_hours","label":"Working hours"},{"key":"fuel","label":"Fuel"},{"key":"drivetrain_tracks","label":"Drivetrain / tracks"},{"key":"weight","label":"Weight"},{"key":"attachment_type","label":"Attachment type"},{"key":"hydraulics","label":"Hydraulics"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"seats","label":"Seats"}]'::jsonb
    WHEN ARRAY['vehicles','agricultural_heavy_machinery','harvesters']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"machine_type","label":"Machine type"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"working_hours","label":"Working hours"},{"key":"fuel","label":"Fuel"},{"key":"drivetrain_tracks","label":"Drivetrain / tracks"},{"key":"weight","label":"Weight"},{"key":"attachment_type","label":"Attachment type"},{"key":"hydraulics","label":"Hydraulics"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"header_width","label":"Header width"},{"key":"crop_type","label":"Crop type"}]'::jsonb
    WHEN ARRAY['vehicles','agricultural_heavy_machinery','excavators']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"machine_type","label":"Machine type"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"working_hours","label":"Working hours"},{"key":"fuel","label":"Fuel"},{"key":"drivetrain_tracks","label":"Drivetrain / tracks"},{"key":"weight","label":"Weight"},{"key":"attachment_type","label":"Attachment type"},{"key":"hydraulics","label":"Hydraulics"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"operating_weight","label":"Operating weight"},{"key":"bucket_size","label":"Bucket size"},{"key":"lift_capacity","label":"Lift capacity"},{"key":"reach","label":"Reach"}]'::jsonb
    WHEN ARRAY['vehicles','agricultural_heavy_machinery','forestry_machinery']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"machine_type","label":"Machine type"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"working_hours","label":"Working hours"},{"key":"fuel","label":"Fuel"},{"key":"drivetrain_tracks","label":"Drivetrain / tracks"},{"key":"weight","label":"Weight"},{"key":"attachment_type","label":"Attachment type"},{"key":"hydraulics","label":"Hydraulics"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"operating_weight","label":"Operating weight"},{"key":"lift_capacity","label":"Lift capacity"}]'::jsonb
    WHEN ARRAY['vehicles','agricultural_heavy_machinery','construction_machinery']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"machine_type","label":"Machine type"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"working_hours","label":"Working hours"},{"key":"fuel","label":"Fuel"},{"key":"drivetrain_tracks","label":"Drivetrain / tracks"},{"key":"weight","label":"Weight"},{"key":"attachment_type","label":"Attachment type"},{"key":"hydraulics","label":"Hydraulics"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"operating_weight","label":"Operating weight"},{"key":"bucket_size","label":"Bucket size"},{"key":"lift_capacity","label":"Lift capacity"}]'::jsonb
    WHEN ARRAY['vehicles','agricultural_heavy_machinery','agricultural_attachments_implements']::text[] THEN '[{"key":"implement_type","label":"Implement type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"working_width","label":"Working width"},{"key":"attachment_type","label":"Attachment type"},{"key":"compatible_machine","label":"Compatible machine"},{"key":"pto_required","label":"PTO required"},{"key":"hydraulics_required","label":"Hydraulics required"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','agricultural_heavy_machinery','agricultural_heavy_machinery_spare_parts']::text[] THEN '[{"key":"part_name","label":"Part name"},{"key":"manufacturer","label":"Manufacturer"},{"key":"part_number","label":"Part number"},{"key":"compatible_machine","label":"Compatible machine"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','marine','boats']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"type","label":"Type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"material","label":"Material"},{"key":"engine_type","label":"Engine type"},{"key":"engine_power","label":"Engine power"},{"key":"fuel","label":"Fuel"},{"key":"engine_hours","label":"Engine hours"},{"key":"cabins","label":"Cabins"},{"key":"trailer_included","label":"Trailer included"},{"key":"registration_number","label":"Registration number"}]'::jsonb
    WHEN ARRAY['vehicles','marine','yachts']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"type","label":"Type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"material","label":"Material"},{"key":"engine_type","label":"Engine type"},{"key":"engine_power","label":"Engine power"},{"key":"fuel","label":"Fuel"},{"key":"engine_hours","label":"Engine hours"},{"key":"cabins","label":"Cabins"},{"key":"trailer_included","label":"Trailer included"},{"key":"registration_number","label":"Registration number"}]'::jsonb
    WHEN ARRAY['vehicles','marine','jet_skis']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"type","label":"Type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"material","label":"Material"},{"key":"engine_type","label":"Engine type"},{"key":"engine_power","label":"Engine power"},{"key":"fuel","label":"Fuel"},{"key":"engine_hours","label":"Engine hours"},{"key":"cabins","label":"Cabins"},{"key":"trailer_included","label":"Trailer included"},{"key":"registration_number","label":"Registration number"}]'::jsonb
    WHEN ARRAY['vehicles','marine','boat_trailers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"trailer_type","label":"Trailer type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"height","label":"Height"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"axles","label":"Axles"},{"key":"brake_type","label":"Brake type"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','marine','outboard_motors']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"power","label":"Power"},{"key":"fuel","label":"Fuel"},{"key":"shaft_length","label":"Shaft length"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['vehicles','aviation','airplanes']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"aircraft_type","label":"Aircraft type"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"flight_hours","label":"Flight hours"},{"key":"seats","label":"Seats"},{"key":"range","label":"Range"},{"key":"registration_number","label":"Registration number"},{"key":"serial_number","label":"Serial number"},{"key":"maintenance_status","label":"Maintenance status"}]'::jsonb
    WHEN ARRAY['vehicles','aviation','helicopters']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"aircraft_type","label":"Aircraft type"},{"key":"engine","label":"Engine"},{"key":"power","label":"Power"},{"key":"flight_hours","label":"Flight hours"},{"key":"seats","label":"Seats"},{"key":"range","label":"Range"},{"key":"registration_number","label":"Registration number"},{"key":"serial_number","label":"Serial number"},{"key":"maintenance_status","label":"Maintenance status"}]'::jsonb
    WHEN ARRAY['vehicles','aviation','ultralights']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"aircraft_type","label":"Aircraft type"},{"key":"engine","label":"Engine"},{"key":"flight_hours","label":"Flight hours"},{"key":"seats","label":"Seats"},{"key":"registration_number","label":"Registration number"}]'::jsonb
    WHEN ARRAY['vehicles','aviation','drones']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"camera","label":"Camera"},{"key":"flight_time","label":"Flight time"},{"key":"range","label":"Range"},{"key":"battery_count","label":"Battery count"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','aviation','aircraft_parts']::text[] THEN '[{"key":"part_name","label":"Part name"},{"key":"manufacturer","label":"Manufacturer"},{"key":"part_number","label":"Part number"},{"key":"serial_number","label":"Serial number"},{"key":"compatible_aircraft","label":"Compatible aircraft"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','trailers','light_trailers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"trailer_type","label":"Trailer type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"height","label":"Height"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"axles","label":"Axles"},{"key":"brake_type","label":"Brake type"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','trailers','car_trailers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"trailer_type","label":"Trailer type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"height","label":"Height"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"axles","label":"Axles"},{"key":"brake_type","label":"Brake type"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','trailers','cargo_trailers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"trailer_type","label":"Trailer type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"height","label":"Height"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"axles","label":"Axles"},{"key":"brake_type","label":"Brake type"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','trailers','caravans']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"trailer_type","label":"Trailer type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"height","label":"Height"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"axles","label":"Axles"},{"key":"brake_type","label":"Brake type"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"},{"key":"sleeping_places","label":"Sleeping places"},{"key":"heating","label":"Heating"},{"key":"kitchen","label":"Kitchen"},{"key":"toilet_shower","label":"Toilet / shower"},{"key":"awning","label":"Awning"}]'::jsonb
    WHEN ARRAY['vehicles','trailers','horse_livestock_trailers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"trailer_type","label":"Trailer type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"height","label":"Height"},{"key":"gross_weight","label":"Gross weight"},{"key":"empty_weight","label":"Empty weight"},{"key":"payload","label":"Payload"},{"key":"axles","label":"Axles"},{"key":"brake_type","label":"Brake type"},{"key":"vin_serial","label":"VIN / serial number"},{"key":"registration_number","label":"Registration number"},{"key":"inspection_valid_until","label":"Inspection valid until"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','engines_engine_parts']::text[] THEN '[{"key":"part_name","label":"Part name"},{"key":"brand","label":"Brand"},{"key":"engine_type","label":"Engine type"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"part_number","label":"Part number"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','transmission_drivetrain']::text[] THEN '[{"key":"part_name","label":"Part name"},{"key":"gearbox_type","label":"Gearbox type"},{"key":"drivetrain_type","label":"Drivetrain type"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"part_number","label":"Part number"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','suspension_steering']::text[] THEN '[{"key":"part_name","label":"Part name"},{"key":"side_position","label":"Side / position"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"part_number","label":"Part number"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','brakes']::text[] THEN '[{"key":"brake_type","label":"Brake type"},{"key":"side_position","label":"Side / position"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"part_number","label":"Part number"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','electrical_parts']::text[] THEN '[{"key":"part_name","label":"Part name"},{"key":"voltage","label":"Voltage"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"part_number","label":"Part number"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','batteries']::text[] THEN '[{"key":"battery_type","label":"Battery type"},{"key":"capacity","label":"Capacity"},{"key":"voltage","label":"Voltage"},{"key":"cca","label":"CCA"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','starters_alternators']::text[] THEN '[{"key":"part_type","label":"Part type"},{"key":"voltage","label":"Voltage"},{"key":"power_rating","label":"Power rating"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"part_number","label":"Part number"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','body_parts']::text[] THEN '[{"key":"body_part_type","label":"Body part type"},{"key":"side_position","label":"Side / position"},{"key":"color","label":"Color"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','lights_lamps']::text[] THEN '[{"key":"light_type","label":"Light type"},{"key":"technology","label":"Technology"},{"key":"side_position","label":"Side / position"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','interior_parts']::text[] THEN '[{"key":"interior_part_type","label":"Interior part type"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','exhaust_parts']::text[] THEN '[{"key":"exhaust_part_type","label":"Exhaust part type"},{"key":"material","label":"Material"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','cooling_heating']::text[] THEN '[{"key":"part_type","label":"Part type"},{"key":"coolant_type","label":"Coolant type"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','fuel_system']::text[] THEN '[{"key":"fuel_system_part","label":"Fuel system part"},{"key":"fuel_type","label":"Fuel type"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"part_number","label":"Part number"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','tires']::text[] THEN '[{"key":"width","label":"Width"},{"key":"profile","label":"Profile"},{"key":"diameter","label":"Diameter"},{"key":"season","label":"Season"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"load_index","label":"Load index"},{"key":"speed_index","label":"Speed index"},{"key":"tread_depth","label":"Tread depth"},{"key":"quantity","label":"Quantity"},{"key":"dot_year","label":"DOT year"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','wheels_rims']::text[] THEN '[{"key":"diameter","label":"Diameter"},{"key":"width","label":"Width"},{"key":"bolt_pattern","label":"Bolt pattern"},{"key":"offset","label":"ET / offset"},{"key":"center_bore","label":"Center bore"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"quantity","label":"Quantity"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','accessories']::text[] THEN '[{"key":"accessory_type","label":"Accessory type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"part_number","label":"Part number"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','riding_racing_gear']::text[] THEN '[{"key":"gear_type","label":"Gear type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"discipline","label":"Discipline"},{"key":"certification","label":"Certification"},{"key":"material","label":"Material"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','spare_parts']::text[] THEN '[{"key":"part_name","label":"Part name"},{"key":"manufacturer","label":"Manufacturer"},{"key":"part_number","label":"Part number"},{"key":"oem_number","label":"OEM number"},{"key":"fits_brand","label":"Fits brand"},{"key":"fits_model","label":"Fits model"},{"key":"fits_generation","label":"Fits generation / body code"},{"key":"fits_year_from","label":"Fits year from"},{"key":"fits_year_to","label":"Fits year to"},{"key":"fits_engine","label":"Fits engine"},{"key":"fits_gearbox","label":"Fits gearbox"},{"key":"side_position","label":"Side / position"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['vehicles','vehicle_parts','vehicle_for_parts']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"year","label":"Year"},{"key":"generation","label":"Generation / body code"},{"key":"fuel","label":"Fuel"},{"key":"engine","label":"Engine"},{"key":"gearbox","label":"Gearbox"},{"key":"drivetrain","label":"Drivetrain"},{"key":"mileage","label":"Mileage"},{"key":"vin","label":"VIN"},{"key":"condition","label":"Condition"},{"key":"available_parts","label":"Available parts"}]'::jsonb
    WHEN ARRAY['electronics','phones']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"storage","label":"Storage"},{"key":"ram","label":"RAM"},{"key":"color","label":"Color"},{"key":"sim_type","label":"SIM type"},{"key":"battery_health","label":"Battery health"},{"key":"screen_condition","label":"Screen condition"},{"key":"network_lock","label":"Network lock"},{"key":"imei_serial","label":"IMEI / serial number"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['electronics','computers']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"processor","label":"Processor"},{"key":"ram","label":"RAM"},{"key":"storage","label":"Storage"},{"key":"graphics_card","label":"Graphics card"},{"key":"screen_size","label":"Screen size"},{"key":"operating_system","label":"Operating system"},{"key":"battery_health","label":"Battery health"},{"key":"serial_number","label":"Serial number"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['electronics','tv_audio']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"screen_size","label":"Screen size"},{"key":"display_type","label":"Display type"},{"key":"resolution","label":"Resolution"},{"key":"smart_tv","label":"Smart TV"},{"key":"audio_type","label":"Audio type"},{"key":"power_output","label":"Power output"},{"key":"connections","label":"Connections"},{"key":"remote_included","label":"Remote included"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['electronics','cameras']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"camera_type","label":"Camera type"},{"key":"lens_included","label":"Lens included"},{"key":"sensor_size","label":"Sensor size"},{"key":"megapixels","label":"Megapixels"},{"key":"shutter_count","label":"Shutter count"},{"key":"video_resolution","label":"Video resolution"},{"key":"battery_count","label":"Battery count"},{"key":"memory_card_included","label":"Memory card included"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['electronics','gaming']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"platform","label":"Platform"},{"key":"storage","label":"Storage"},{"key":"controller_count","label":"Controller count"},{"key":"game_count","label":"Game count"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['electronics','smart_home']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"device_type","label":"Device type"},{"key":"compatibility","label":"Compatibility"},{"key":"connection_type","label":"Connection type"},{"key":"power_type","label":"Power type"},{"key":"app_support","label":"App support"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['electronics','components']::text[] THEN '[{"key":"component_type","label":"Component type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"socket_compatibility","label":"Socket / compatibility"},{"key":"capacity","label":"Capacity"},{"key":"speed","label":"Speed"},{"key":"power_rating","label":"Power rating"},{"key":"condition","label":"Condition"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['electronics','electronics_accessories']::text[] THEN '[{"key":"accessory_type","label":"Accessory type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"compatibility","label":"Compatibility"},{"key":"connection_type","label":"Connection type"},{"key":"color","label":"Color"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['electronics','other_electronics']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['real_estate','apartments']::text[] THEN '[{"key":"listing_type","label":"Listing type"},{"key":"property_type","label":"Property type"},{"key":"rooms","label":"Rooms"},{"key":"area","label":"Area (m²)"},{"key":"floor","label":"Floor"},{"key":"total_floors","label":"Total floors"},{"key":"year_built","label":"Year built"},{"key":"condition","label":"Condition"},{"key":"heating_type","label":"Heating type"},{"key":"energy_class","label":"Energy class"},{"key":"balcony","label":"Balcony"},{"key":"furnished","label":"Furnished"},{"key":"parking","label":"Parking"},{"key":"storage_room","label":"Storage room"},{"key":"bathroom_count","label":"Bathroom count"},{"key":"district","label":"District / neighborhood"}]'::jsonb
    WHEN ARRAY['real_estate','houses']::text[] THEN '[{"key":"listing_type","label":"Listing type"},{"key":"house_type","label":"House type"},{"key":"rooms","label":"Rooms"},{"key":"living_area","label":"Living area (m²)"},{"key":"land_area","label":"Land area"},{"key":"floors","label":"Floors"},{"key":"year_built","label":"Year built"},{"key":"condition","label":"Condition"},{"key":"heating_type","label":"Heating type"},{"key":"energy_class","label":"Energy class"},{"key":"garage","label":"Garage"},{"key":"sauna","label":"Sauna"},{"key":"terrace","label":"Terrace"},{"key":"water_supply","label":"Water supply"},{"key":"sewer_connection","label":"Sewer connection"},{"key":"district","label":"District / neighborhood"}]'::jsonb
    WHEN ARRAY['real_estate','land']::text[] THEN '[{"key":"land_type","label":"Land type"},{"key":"area","label":"Area"},{"key":"purpose","label":"Purpose"},{"key":"detailed_plan","label":"Detailed plan"},{"key":"electricity","label":"Electricity"},{"key":"water","label":"Water"},{"key":"sewer","label":"Sewer"},{"key":"road_access","label":"Road access"},{"key":"district","label":"District / neighborhood"}]'::jsonb
    WHEN ARRAY['real_estate','commercial_property']::text[] THEN '[{"key":"property_type","label":"Property type"},{"key":"area","label":"Area"},{"key":"floor","label":"Floor"},{"key":"purpose","label":"Purpose"},{"key":"parking","label":"Parking"},{"key":"loading_access","label":"Loading access"},{"key":"heating","label":"Heating"},{"key":"security","label":"Security"},{"key":"district","label":"District / neighborhood"}]'::jsonb
    WHEN ARRAY['real_estate','garages']::text[] THEN '[{"key":"area","label":"Area"},{"key":"electricity","label":"Electricity"},{"key":"heating","label":"Heating"},{"key":"security","label":"Security"},{"key":"water","label":"Water"},{"key":"district","label":"District / neighborhood"}]'::jsonb
    WHEN ARRAY['real_estate','vacation_property']::text[] THEN '[{"key":"property_type","label":"Property type"},{"key":"rooms","label":"Rooms"},{"key":"area","label":"Area"},{"key":"beds","label":"Beds"},{"key":"sauna","label":"Sauna"},{"key":"pool","label":"Pool"},{"key":"beach_access","label":"Beach access"},{"key":"seasonal_year_round","label":"Seasonal / year-round"},{"key":"district","label":"District / neighborhood"}]'::jsonb
    WHEN ARRAY['clothing_fashion','men']::text[] THEN '[{"key":"category_type","label":"Category type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"fit","label":"Fit"},{"key":"color","label":"Color"},{"key":"material","label":"Material"},{"key":"condition","label":"Condition"},{"key":"season","label":"Season"},{"key":"authenticity","label":"Authenticity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['clothing_fashion','women']::text[] THEN '[{"key":"category_type","label":"Category type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"fit","label":"Fit"},{"key":"color","label":"Color"},{"key":"material","label":"Material"},{"key":"condition","label":"Condition"},{"key":"season","label":"Season"},{"key":"authenticity","label":"Authenticity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['clothing_fashion','kids']::text[] THEN '[{"key":"category_type","label":"Category type"},{"key":"brand","label":"Brand"},{"key":"size_age","label":"Size / age"},{"key":"gender","label":"Gender"},{"key":"color","label":"Color"},{"key":"material","label":"Material"},{"key":"condition","label":"Condition"},{"key":"season","label":"Season"}]'::jsonb
    WHEN ARRAY['clothing_fashion','workwear']::text[] THEN '[{"key":"workwear_type","label":"Workwear type"},{"key":"gender","label":"Gender"},{"key":"size","label":"Size"},{"key":"industry","label":"Industry"},{"key":"season","label":"Season"},{"key":"visibility_class","label":"Visibility class"},{"key":"protection_class","label":"Protection class"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['clothing_fashion','shoes']::text[] THEN '[{"key":"gender","label":"Gender"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"size","label":"Size"},{"key":"color","label":"Color"},{"key":"material","label":"Material"},{"key":"condition","label":"Condition"},{"key":"season","label":"Season"},{"key":"heel_height","label":"Heel height"},{"key":"authenticity","label":"Authenticity"},{"key":"original_box_included","label":"Original box included"}]'::jsonb
    WHEN ARRAY['clothing_fashion','watches']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"movement_type","label":"Movement type"},{"key":"case_material","label":"Case material"},{"key":"case_size","label":"Case size"},{"key":"water_resistance","label":"Water resistance"},{"key":"condition","label":"Condition"},{"key":"box_papers_included","label":"Box / papers included"},{"key":"authenticity","label":"Authenticity"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['clothing_fashion','bags']::text[] THEN '[{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"condition","label":"Condition"},{"key":"authenticity","label":"Authenticity"},{"key":"dust_bag_box_included","label":"Dust bag / box included"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['clothing_fashion','jewelry']::text[] THEN '[{"key":"jewelry_type","label":"Jewelry type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"gemstone","label":"Gemstone"},{"key":"size","label":"Size"},{"key":"weight","label":"Weight"},{"key":"condition","label":"Condition"},{"key":"authenticity","label":"Authenticity"},{"key":"certificate_included","label":"Certificate included"}]'::jsonb
    WHEN ARRAY['clothing_fashion','other_clothing_fashion']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['tools_industrial','power_tools']::text[] THEN '[{"key":"tool_type","label":"Tool type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"power_source","label":"Power source"},{"key":"voltage","label":"Voltage"},{"key":"power_rating","label":"Power rating"},{"key":"battery_included","label":"Battery included"},{"key":"battery_count","label":"Battery count"},{"key":"charger_included","label":"Charger included"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['tools_industrial','hand_tools']::text[] THEN '[{"key":"tool_type","label":"Tool type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"size","label":"Size"},{"key":"condition","label":"Condition"},{"key":"set_single","label":"Set / single item"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['tools_industrial','workshop_equipment']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"power_source","label":"Power source"},{"key":"voltage","label":"Voltage"},{"key":"capacity","label":"Capacity"},{"key":"dimensions","label":"Dimensions"},{"key":"weight","label":"Weight"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['tools_industrial','industrial_equipment']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"power_source","label":"Power source"},{"key":"voltage","label":"Voltage"},{"key":"capacity","label":"Capacity"},{"key":"working_pressure","label":"Working pressure"},{"key":"weight","label":"Weight"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['tools_industrial','safety_equipment']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"certification","label":"Certification"},{"key":"condition","label":"Condition"},{"key":"expiration_date","label":"Expiration date"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['tools_industrial','other_tools_industrial']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['home_garden','furniture']::text[] THEN '[{"key":"furniture_type","label":"Furniture type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"dimensions","label":"Dimensions"},{"key":"assembly_required","label":"Assembly required"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['home_garden','appliances']::text[] THEN '[{"key":"appliance_type","label":"Appliance type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"energy_class","label":"Energy class"},{"key":"power_source","label":"Power source"},{"key":"capacity","label":"Capacity"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"warranty_remaining","label":"Warranty remaining"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['home_garden','garden_tools']::text[] THEN '[{"key":"tool_type","label":"Tool type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"power_source","label":"Power source"},{"key":"voltage","label":"Voltage"},{"key":"battery_included","label":"Battery included"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['home_garden','plants_seedlings']::text[] THEN '[{"key":"plant_type","label":"Plant type"},{"key":"variety","label":"Variety"},{"key":"quantity","label":"Quantity"},{"key":"pot_size","label":"Pot size"},{"key":"growth_stage","label":"Growth stage"},{"key":"organic","label":"Organic"}]'::jsonb
    WHEN ARRAY['home_garden','seeds']::text[] THEN '[{"key":"seed_type","label":"Seed type"},{"key":"variety","label":"Variety"},{"key":"quantity","label":"Quantity"},{"key":"package_weight","label":"Package weight"},{"key":"sowing_season","label":"Sowing season"},{"key":"organic","label":"Organic"}]'::jsonb
    WHEN ARRAY['home_garden','crops_produce']::text[] THEN '[{"key":"produce_type","label":"Produce type"},{"key":"variety","label":"Variety"},{"key":"quantity","label":"Quantity"},{"key":"unit","label":"Unit"},{"key":"harvest_date","label":"Harvest date"},{"key":"organic","label":"Organic"}]'::jsonb
    WHEN ARRAY['home_garden','farm_supplies']::text[] THEN '[{"key":"supply_type","label":"Supply type"},{"key":"brand","label":"Brand"},{"key":"quantity","label":"Quantity"},{"key":"material","label":"Material"},{"key":"intended_use","label":"Intended use"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['home_garden','animal_feed']::text[] THEN '[{"key":"feed_type","label":"Feed type"},{"key":"animal_type","label":"Animal type"},{"key":"quantity","label":"Quantity"},{"key":"package_weight","label":"Package weight"},{"key":"ingredients","label":"Ingredients"},{"key":"expiry_date","label":"Expiry date"}]'::jsonb
    WHEN ARRAY['home_garden','greenhouses']::text[] THEN '[{"key":"greenhouse_type","label":"Greenhouse type"},{"key":"material","label":"Material"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"height","label":"Height"},{"key":"frame_material","label":"Frame material"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['home_garden','decor']::text[] THEN '[{"key":"decor_type","label":"Decor type"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"style","label":"Style"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['home_garden','lighting']::text[] THEN '[{"key":"lighting_type","label":"Lighting type"},{"key":"brand","label":"Brand"},{"key":"power_source","label":"Power source"},{"key":"bulb_type","label":"Bulb type"},{"key":"color_temperature","label":"Color temperature"},{"key":"smart_lighting_support","label":"Smart lighting support"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['home_garden','kitchenware']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['home_garden','home_textiles']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['home_garden','household_supplies']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['home_garden','bathroom']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['home_garden','heating_fuels']::text[] THEN '[{"key":"fuel_type","label":"Fuel type"},{"key":"wood_type","label":"Wood type"},{"key":"quantity","label":"Quantity"},{"key":"unit","label":"Unit"},{"key":"moisture_level","label":"Moisture level"},{"key":"packaging","label":"Packaging"},{"key":"delivery_available","label":"Delivery available"}]'::jsonb
    WHEN ARRAY['home_garden','heating_equipment']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"fuel_type","label":"Fuel type"},{"key":"power","label":"Power"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['home_garden','outdoor_furniture']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['home_garden','other_home_garden']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','gym_equipment']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"weight_resistance","label":"Weight / resistance"},{"key":"dimensions","label":"Dimensions"},{"key":"foldable","label":"Foldable"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','bicycles']::text[] THEN '[{"key":"bike_type","label":"Bike type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"frame_size","label":"Frame size"},{"key":"wheel_size","label":"Wheel size"},{"key":"material","label":"Material"},{"key":"gear_count","label":"Gear count"},{"key":"suspension","label":"Suspension"},{"key":"brake_type","label":"Brake type"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['sports_outdoor','winter_sports']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"size","label":"Size"},{"key":"binding_included","label":"Binding included"},{"key":"boot_size","label":"Boot size"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','camping']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"capacity","label":"Capacity"},{"key":"weight","label":"Weight"},{"key":"dimensions","label":"Dimensions"},{"key":"season_rating","label":"Season rating"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','fishing']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"length","label":"Length"},{"key":"power_rating","label":"Power rating"},{"key":"reel_included","label":"Reel included"},{"key":"line_included","label":"Line included"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','other_sports_outdoor']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','equestrian_horse_supplies','saddles_accessories']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"discipline","label":"Discipline"},{"key":"horse_size","label":"Horse size"},{"key":"seat_size","label":"Seat size"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','equestrian_horse_supplies','bridles_halters_tack']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"discipline","label":"Discipline"},{"key":"horse_size","label":"Horse size"},{"key":"seat_size","label":"Seat size"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','equestrian_horse_supplies','rider_clothing_safety']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"gender","label":"Gender"},{"key":"discipline","label":"Discipline"},{"key":"safety_standard","label":"Safety standard"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['sports_outdoor','equestrian_horse_supplies','horse_blankets_textiles']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"horse_size","label":"Horse size"},{"key":"blanket_weight","label":"Blanket weight"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['sports_outdoor','equestrian_horse_supplies','horse_grooming_care']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"horse_size","label":"Horse size"},{"key":"material","label":"Material"},{"key":"quantity","label":"Quantity"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','equestrian_horse_supplies','stable_paddock_equipment']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"dimensions","label":"Dimensions"},{"key":"capacity","label":"Capacity"},{"key":"quantity","label":"Quantity"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['sports_outdoor','equestrian_horse_supplies','driving_carriage_equipment']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"discipline","label":"Discipline"},{"key":"horse_size","label":"Horse size"},{"key":"seat_size","label":"Seat size"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['sports_outdoor','equestrian_horse_supplies','other_equestrian_supplies']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['antiques_collectibles','art']::text[] THEN '[{"key":"art_type","label":"Art type"},{"key":"artist","label":"Artist"},{"key":"title","label":"Title"},{"key":"year_period","label":"Year / period"},{"key":"material","label":"Material"},{"key":"dimensions","label":"Dimensions"},{"key":"signed","label":"Signed"},{"key":"certificate_included","label":"Certificate included"},{"key":"condition","label":"Condition"},{"key":"frame_included","label":"Frame included"}]'::jsonb
    WHEN ARRAY['antiques_collectibles','vintage']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand_maker","label":"Brand / maker"},{"key":"year_era","label":"Year / era"},{"key":"material","label":"Material"},{"key":"origin_country","label":"Origin country"},{"key":"condition","label":"Condition"},{"key":"restored","label":"Restored"}]'::jsonb
    WHEN ARRAY['antiques_collectibles','coins']::text[] THEN '[{"key":"country","label":"Country"},{"key":"year","label":"Year"},{"key":"currency","label":"Currency"},{"key":"material","label":"Material"},{"key":"denomination","label":"Denomination"},{"key":"mint_mark","label":"Mint mark"},{"key":"condition_grading","label":"Condition / grading"},{"key":"certificate_included","label":"Certificate included"}]'::jsonb
    WHEN ARRAY['antiques_collectibles','military']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"country","label":"Country"},{"key":"era","label":"Era"},{"key":"original_reproduction","label":"Original / reproduction"},{"key":"material","label":"Material"},{"key":"condition","label":"Condition"},{"key":"serial_markings","label":"Serial number / markings"},{"key":"certificate_included","label":"Certificate included"}]'::jsonb
    WHEN ARRAY['antiques_collectibles','memorabilia']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"related_person_event","label":"Related person / event"},{"key":"year_era","label":"Year / era"},{"key":"signed","label":"Signed"},{"key":"certificate_included","label":"Certificate included"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['antiques_collectibles','other_antiques_collectibles']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['building_materials','lumber']::text[] THEN '[{"key":"material_type","label":"Material type"},{"key":"wood_type","label":"Wood type"},{"key":"length","label":"Length"},{"key":"width","label":"Width"},{"key":"thickness","label":"Thickness"},{"key":"moisture_level","label":"Moisture level"},{"key":"treatment_type","label":"Treatment type"},{"key":"quantity","label":"Quantity"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['building_materials','concrete']::text[] THEN '[{"key":"material_type","label":"Material type"},{"key":"strength_class","label":"Strength class"},{"key":"weight","label":"Weight"},{"key":"bag_size","label":"Bag size"},{"key":"quantity","label":"Quantity"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['building_materials','insulation']::text[] THEN '[{"key":"insulation_type","label":"Insulation type"},{"key":"material","label":"Material"},{"key":"thickness","label":"Thickness"},{"key":"coverage_area","label":"Coverage area"},{"key":"fire_rating","label":"Fire rating"},{"key":"quantity","label":"Quantity"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['building_materials','roofing']::text[] THEN '[{"key":"roofing_type","label":"Roofing type"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"dimensions","label":"Dimensions"},{"key":"coverage_area","label":"Coverage area"},{"key":"quantity","label":"Quantity"},{"key":"condition","label":"Condition"}]'::jsonb
    WHEN ARRAY['building_materials','plumbing']::text[] THEN '[{"key":"plumbing_type","label":"Plumbing type"},{"key":"material","label":"Material"},{"key":"diameter","label":"Diameter"},{"key":"length","label":"Length"},{"key":"compatibility","label":"Compatibility"},{"key":"pressure_rating","label":"Pressure rating"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['building_materials','other_building_materials']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['children_baby','strollers_prams']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"age_range","label":"Age range"},{"key":"safety_standard","label":"Safety standard"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['children_baby','child_car_seats']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"age_range","label":"Age range"},{"key":"safety_standard","label":"Safety standard"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['children_baby','nursery_furniture']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"age_range","label":"Age range"},{"key":"safety_standard","label":"Safety standard"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['children_baby','baby_feeding_care']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"age_range","label":"Age range"},{"key":"safety_standard","label":"Safety standard"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['children_baby','baby_safety_accessories']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"age_range","label":"Age range"},{"key":"safety_standard","label":"Safety standard"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['children_baby','other_children_baby']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"age_range","label":"Age range"},{"key":"safety_standard","label":"Safety standard"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['pet_supplies','dog_supplies']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"animal_type","label":"Animal type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"material","label":"Material"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['pet_supplies','cat_supplies']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"animal_type","label":"Animal type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"material","label":"Material"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['pet_supplies','aquariums_terrariums']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"animal_type","label":"Animal type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"material","label":"Material"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['pet_supplies','cages_housing']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"animal_type","label":"Animal type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"material","label":"Material"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['pet_supplies','pet_transport_grooming']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"animal_type","label":"Animal type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"material","label":"Material"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['pet_supplies','other_pet_supplies']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"animal_type","label":"Animal type"},{"key":"brand","label":"Brand"},{"key":"size","label":"Size"},{"key":"material","label":"Material"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['books_music_media','books']::text[] THEN '[{"key":"media_type","label":"Media type"},{"key":"title","label":"Title"},{"key":"creator","label":"Author / creator"},{"key":"language","label":"Language"},{"key":"publication_year","label":"Publication year"},{"key":"format","label":"Format"},{"key":"genre","label":"Genre"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['books_music_media','magazines_comics']::text[] THEN '[{"key":"media_type","label":"Media type"},{"key":"title","label":"Title"},{"key":"creator","label":"Author / creator"},{"key":"language","label":"Language"},{"key":"publication_year","label":"Publication year"},{"key":"format","label":"Format"},{"key":"genre","label":"Genre"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['books_music_media','music_movies']::text[] THEN '[{"key":"media_type","label":"Media type"},{"key":"title","label":"Title"},{"key":"creator","label":"Author / creator"},{"key":"language","label":"Language"},{"key":"publication_year","label":"Publication year"},{"key":"format","label":"Format"},{"key":"genre","label":"Genre"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['books_music_media','musical_instruments']::text[] THEN '[{"key":"instrument_type","label":"Instrument type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"size","label":"Size"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['books_music_media','instrument_accessories']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['books_music_media','other_books_media']::text[] THEN '[{"key":"media_type","label":"Media type"},{"key":"title","label":"Title"},{"key":"creator","label":"Author / creator"},{"key":"language","label":"Language"},{"key":"publication_year","label":"Publication year"},{"key":"format","label":"Format"},{"key":"genre","label":"Genre"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['hobbies_toys_crafts','toys']::text[] THEN '[{"key":"hobby_type","label":"Hobby type"},{"key":"brand","label":"Brand"},{"key":"age_range","label":"Age range"},{"key":"material","label":"Material"},{"key":"dimensions","label":"Dimensions"},{"key":"skill_level","label":"Skill level"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['hobbies_toys_crafts','board_games_puzzles']::text[] THEN '[{"key":"hobby_type","label":"Hobby type"},{"key":"brand","label":"Brand"},{"key":"age_range","label":"Age range"},{"key":"material","label":"Material"},{"key":"dimensions","label":"Dimensions"},{"key":"skill_level","label":"Skill level"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['hobbies_toys_crafts','arts_crafts']::text[] THEN '[{"key":"hobby_type","label":"Hobby type"},{"key":"brand","label":"Brand"},{"key":"age_range","label":"Age range"},{"key":"material","label":"Material"},{"key":"dimensions","label":"Dimensions"},{"key":"skill_level","label":"Skill level"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['hobbies_toys_crafts','model_rc_hobbies']::text[] THEN '[{"key":"hobby_type","label":"Hobby type"},{"key":"brand","label":"Brand"},{"key":"age_range","label":"Age range"},{"key":"material","label":"Material"},{"key":"dimensions","label":"Dimensions"},{"key":"skill_level","label":"Skill level"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['hobbies_toys_crafts','sewing_knitting']::text[] THEN '[{"key":"hobby_type","label":"Hobby type"},{"key":"brand","label":"Brand"},{"key":"age_range","label":"Age range"},{"key":"material","label":"Material"},{"key":"dimensions","label":"Dimensions"},{"key":"skill_level","label":"Skill level"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['hobbies_toys_crafts','other_hobbies_toys']::text[] THEN '[{"key":"hobby_type","label":"Hobby type"},{"key":"brand","label":"Brand"},{"key":"age_range","label":"Age range"},{"key":"material","label":"Material"},{"key":"dimensions","label":"Dimensions"},{"key":"skill_level","label":"Skill level"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    WHEN ARRAY['office_business','office_equipment']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"connection_type","label":"Connection type"},{"key":"power_source","label":"Power source"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['office_business','printers_scanners']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"connection_type","label":"Connection type"},{"key":"power_source","label":"Power source"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['office_business','office_furniture']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"capacity","label":"Capacity"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"}]'::jsonb
    WHEN ARRAY['office_business','retail_warehouse_equipment']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"connection_type","label":"Connection type"},{"key":"power_source","label":"Power source"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['office_business','presentation_equipment']::text[] THEN '[{"key":"equipment_type","label":"Equipment type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"connection_type","label":"Connection type"},{"key":"power_source","label":"Power source"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"included_accessories","label":"Included accessories"},{"key":"serial_number","label":"Serial number"}]'::jsonb
    WHEN ARRAY['office_business','other_office_business']::text[] THEN '[{"key":"item_type","label":"Item type"},{"key":"brand","label":"Brand"},{"key":"model","label":"Model"},{"key":"material","label":"Material"},{"key":"color","label":"Color"},{"key":"size","label":"Size"},{"key":"dimensions","label":"Dimensions"},{"key":"condition","label":"Condition"},{"key":"quantity","label":"Quantity"},{"key":"included_accessories","label":"Included accessories"}]'::jsonb
    ELSE '[]'::jsonb END;
$fn$;

CREATE FUNCTION public.public_listing_detail_values_v1(p_row public.listings)
RETURNS jsonb LANGUAGE plpgsql IMMUTABLE
SET search_path=pg_catalog,public,pg_temp
AS $fn$
DECLARE path_value text[]; specs jsonb; spec jsonb; value_text text; raw_value jsonb;
  result jsonb:='[]'; seen text[]:=ARRAY[]::text[]; clipped boolean:=false; attrs jsonb;
BEGIN
  path_value:=ARRAY[(p_row).category,(p_row).subcategory];
  IF jsonb_typeof((p_row).details->'detailCategory')='string'
     AND (p_row).details->>'detailCategory'<>'' THEN
    path_value:=path_value||ARRAY[(p_row).details->>'detailCategory'];
  END IF;
  -- These columns are explicit authored public form inputs, not AI or inferred values.
  attrs:=jsonb_build_array(
    jsonb_build_object('key','manufacturer','label','Manufacturer','value',(p_row).manufacturer),
    jsonb_build_object('key','part_number','label','Part number','value',(p_row).part_number),
    jsonb_build_object('key','oem_number','label','OEM number','value',(p_row).oem_number),
    jsonb_build_object('key','vehicle_brand','label','Vehicle brand','value',(p_row).vehicle_brand),
    jsonb_build_object('key','vehicle_model','label','Vehicle model','value',(p_row).vehicle_model),
    jsonb_build_object('key','vehicle_year','label','Vehicle year','value',(p_row).vehicle_year),
    jsonb_build_object('key','engine','label','Engine','value',(p_row).engine));
  FOR spec IN SELECT value FROM jsonb_array_elements(attrs) LOOP
    value_text:=spec->>'value';
    IF value_text IS NOT NULL AND btrim(value_text)<>'' THEN
      clipped:=clipped OR char_length(value_text)>1000;
      result:=result||jsonb_build_array(jsonb_build_object('key',spec->>'key',
        'label',spec->>'label','value',left(value_text,1000)));
      seen:=array_append(seen,spec->>'key');
    END IF;
  END LOOP;
  specs:=public.public_listing_detail_field_spec_v1(path_value);
  IF jsonb_typeof((p_row).details)='object' THEN
    FOR spec IN SELECT value FROM jsonb_array_elements(specs) LOOP
      IF (spec->>'key')=ANY(seen) THEN CONTINUE; END IF;
      raw_value:=(p_row).details->(spec->>'key');
      IF jsonb_typeof(raw_value) IN ('string','number','boolean') THEN
        value_text:=raw_value#>>'{}';
        IF btrim(value_text)<>'' THEN
          clipped:=clipped OR char_length(value_text)>1000;
          result:=result||jsonb_build_array(jsonb_build_object('key',spec->>'key',
            'label',spec->>'label','value',left(value_text,1000)));
          seen:=array_append(seen,spec->>'key');
        END IF;
      END IF;
    END LOOP;
  END IF;
  RETURN jsonb_build_object('fields',result,'truncated',clipped);
END $fn$;
ALTER FUNCTION public.public_listing_detail_field_spec_v1(text[]) OWNER TO postgres;
ALTER FUNCTION public.public_listing_detail_values_v1(public.listings) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.public_listing_detail_field_spec_v1(text[]),
 public.public_listing_detail_values_v1(public.listings) FROM PUBLIC,anon,authenticated,service_role;
