export type CategoryField = {
  key: string;
  label: string;
  type?: "text" | "number" | "select";
  options?: string[];
};

const carFields: CategoryField[] = [
  { key: "brand", label: "Brand" },
  { key: "model", label: "Model" },
  { key: "year", label: "Year" },
  { key: "generation", label: "Generation / body code" },
  { key: "fuel", label: "Fuel" },
  { key: "engine", label: "Engine" },
  { key: "power", label: "Power" },
  { key: "gearbox", label: "Gearbox" },
  { key: "drivetrain", label: "Drivetrain" },
  { key: "mileage", label: "Mileage" },
  { key: "vin", label: "VIN" },
  { key: "registration_number", label: "Registration number" },
  { key: "body_type", label: "Body type" },
  { key: "doors", label: "Number of doors" },
  { key: "seats", label: "Seats" },
  { key: "color", label: "Color" },
  { key: "inspection_valid_until", label: "Inspection valid until" },
];

const motorcycleFields: CategoryField[] = [
  { key: "brand", label: "Brand" },
  { key: "model", label: "Model" },
  { key: "year", label: "Year" },
  { key: "engine_size", label: "Engine size" },
  { key: "power", label: "Power" },
  { key: "fuel", label: "Fuel" },
  { key: "mileage", label: "Mileage" },
  { key: "transmission", label: "Transmission" },
  { key: "type", label: "Type" },
  { key: "vin", label: "VIN" },
  { key: "registration_number", label: "Registration number" },
  { key: "inspection_valid_until", label: "Inspection valid until" },
];

const truckFields: CategoryField[] = [
  { key: "brand", label: "Brand" },
  { key: "model", label: "Model" },
  { key: "year", label: "Year" },
  { key: "fuel", label: "Fuel" },
  { key: "engine", label: "Engine" },
  { key: "power", label: "Power" },
  { key: "gearbox", label: "Gearbox" },
  { key: "mileage", label: "Mileage" },
  { key: "seats", label: "Seats" },
  { key: "axle_configuration", label: "Axle configuration" },
  { key: "gross_weight", label: "Gross weight" },
  { key: "empty_weight", label: "Empty weight" },
  { key: "payload", label: "Payload" },
  { key: "load_space_length", label: "Load space length" },
  { key: "load_space_width", label: "Load space width" },
  { key: "load_space_height", label: "Load space height" },
  { key: "tachograph", label: "Tachograph" },
  { key: "vin", label: "VIN" },
  { key: "registration_number", label: "Registration number" },
  { key: "inspection_valid_until", label: "Inspection valid until" },
];

const machineryFields: CategoryField[] = [
  { key: "brand", label: "Brand" },
  { key: "model", label: "Model" },
  { key: "year", label: "Year" },
  { key: "machine_type", label: "Machine type" },
  { key: "engine", label: "Engine" },
  { key: "power", label: "Power" },
  { key: "working_hours", label: "Working hours" },
  { key: "fuel", label: "Fuel" },
  { key: "drivetrain_tracks", label: "Drivetrain / tracks" },
  { key: "weight", label: "Weight" },
  { key: "attachment_type", label: "Attachment type" },
  { key: "hydraulics", label: "Hydraulics" },
  { key: "vin_serial", label: "VIN / serial number" },
];

const boatFields: CategoryField[] = [
  { key: "brand", label: "Brand" },
  { key: "model", label: "Model" },
  { key: "year", label: "Year" },
  { key: "type", label: "Type" },
  { key: "length", label: "Length" },
  { key: "width", label: "Width" },
  { key: "material", label: "Material" },
  { key: "engine_type", label: "Engine type" },
  { key: "engine_power", label: "Engine power" },
  { key: "fuel", label: "Fuel" },
  { key: "engine_hours", label: "Engine hours" },
  { key: "cabins", label: "Cabins" },
  { key: "trailer_included", label: "Trailer included" },
  { key: "registration_number", label: "Registration number" },
];

const trailerFields: CategoryField[] = [
  { key: "brand", label: "Brand" },
  { key: "model", label: "Model" },
  { key: "year", label: "Year" },
  { key: "trailer_type", label: "Trailer type" },
  { key: "length", label: "Length" },
  { key: "width", label: "Width" },
  { key: "height", label: "Height" },
  { key: "gross_weight", label: "Gross weight" },
  { key: "empty_weight", label: "Empty weight" },
  { key: "payload", label: "Payload" },
  { key: "axles", label: "Axles" },
  { key: "brake_type", label: "Brake type" },
  { key: "vin_serial", label: "VIN / serial number" },
  { key: "registration_number", label: "Registration number" },
  { key: "inspection_valid_until", label: "Inspection valid until" },
];

export const CATEGORY_FIELDS: Record<string, CategoryField[]> = {
  passenger_cars: carFields,
  suv_offroad: carFields,
  vans_minibuses: carFields,
  pickup_trucks: carFields,

  motorhomes_campers: [
    ...carFields,
    { key: "sleeping_places", label: "Sleeping places" },
    { key: "length", label: "Length" },
    { key: "gross_weight", label: "Gross weight" },
    { key: "equipment", label: "Equipment" },
  ],

  racing_vehicles: [
    ...carFields,
    { key: "discipline", label: "Discipline" },
    { key: "roll_cage", label: "Roll cage" },
    { key: "homologation", label: "Homologation" },
    { key: "track_street_legal", label: "Track / street legal" },
  ],

  sport_bikes: motorcycleFields,
  cruisers: motorcycleFields,
  touring: motorcycleFields,
  enduro_mx: motorcycleFields,
  scooters: motorcycleFields,

  atv_utv: [
    ...motorcycleFields,
    { key: "drivetrain", label: "Drivetrain" },
    { key: "winch", label: "Winch" },
    { key: "road_legal", label: "Road legal" },
  ],

  snowmobiles: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "year", label: "Year" },
    { key: "engine_size", label: "Engine size" },
    { key: "power", label: "Power" },
    { key: "mileage", label: "Mileage" },
    { key: "track_length", label: "Track length" },
    { key: "electric_start", label: "Electric start" },
  ],

  trucks: truckFields,
  semi_trucks: truckFields,
  buses: truckFields,

  commercial_trailers: trailerFields,

  tractors: [
    ...machineryFields,
    { key: "seats", label: "Seats" },
  ],

  harvesters: [
    ...machineryFields,
    { key: "header_width", label: "Header width" },
    { key: "crop_type", label: "Crop type" },
  ],

  excavators: [
    ...machineryFields,
    { key: "operating_weight", label: "Operating weight" },
    { key: "bucket_size", label: "Bucket size" },
    { key: "lift_capacity", label: "Lift capacity" },
    { key: "reach", label: "Reach" },
  ],

  forestry_machinery: [
    ...machineryFields,
    { key: "operating_weight", label: "Operating weight" },
    { key: "lift_capacity", label: "Lift capacity" },
  ],

  construction_machinery: [
    ...machineryFields,
    { key: "operating_weight", label: "Operating weight" },
    { key: "bucket_size", label: "Bucket size" },
    { key: "lift_capacity", label: "Lift capacity" },
  ],

  boats: boatFields,
  yachts: boatFields,
  jet_skis: boatFields,

  boat_trailers: trailerFields,

  outboard_motors: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "year", label: "Year" },
    { key: "power", label: "Power" },
    { key: "fuel", label: "Fuel" },
    { key: "shaft_length", label: "Shaft length" },
    { key: "serial_number", label: "Serial number" },
  ],

  airplanes: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "year", label: "Year" },
    { key: "aircraft_type", label: "Aircraft type" },
    { key: "engine", label: "Engine" },
    { key: "power", label: "Power" },
    { key: "flight_hours", label: "Flight hours" },
    { key: "seats", label: "Seats" },
    { key: "range", label: "Range" },
    { key: "registration_number", label: "Registration number" },
    { key: "serial_number", label: "Serial number" },
    { key: "maintenance_status", label: "Maintenance status" },
  ],

  helicopters: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "year", label: "Year" },
    { key: "aircraft_type", label: "Aircraft type" },
    { key: "engine", label: "Engine" },
    { key: "power", label: "Power" },
    { key: "flight_hours", label: "Flight hours" },
    { key: "seats", label: "Seats" },
    { key: "range", label: "Range" },
    { key: "registration_number", label: "Registration number" },
    { key: "serial_number", label: "Serial number" },
    { key: "maintenance_status", label: "Maintenance status" },
  ],

  ultralights: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "year", label: "Year" },
    { key: "aircraft_type", label: "Aircraft type" },
    { key: "engine", label: "Engine" },
    { key: "flight_hours", label: "Flight hours" },
    { key: "seats", label: "Seats" },
    { key: "registration_number", label: "Registration number" },
  ],

  drones: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "camera", label: "Camera" },
    { key: "flight_time", label: "Flight time" },
    { key: "range", label: "Range" },
    { key: "battery_count", label: "Battery count" },
    { key: "condition", label: "Condition" },
  ],

  aircraft_parts: [
    { key: "part_name", label: "Part name" },
    { key: "manufacturer", label: "Manufacturer" },
    { key: "part_number", label: "Part number" },
    { key: "serial_number", label: "Serial number" },
    { key: "compatible_aircraft", label: "Compatible aircraft" },
    { key: "condition", label: "Condition" },
    { key: "certification_documents", label: "Certification / documents" },
  ],

  light_trailers: trailerFields,
  car_trailers: trailerFields,
  cargo_trailers: trailerFields,

  caravans: [
    ...trailerFields,
    { key: "sleeping_places", label: "Sleeping places" },
    { key: "heating", label: "Heating" },
    { key: "kitchen", label: "Kitchen" },
    { key: "toilet_shower", label: "Toilet / shower" },
    { key: "awning", label: "Awning" },
  ],

  vehicle_for_parts: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "year", label: "Year" },
    { key: "generation", label: "Generation / body code" },
    { key: "fuel", label: "Fuel" },
    { key: "engine", label: "Engine" },
    { key: "gearbox", label: "Gearbox" },
    { key: "drivetrain", label: "Drivetrain" },
    { key: "mileage", label: "Mileage" },
    { key: "vin", label: "VIN" },
    { key: "condition", label: "Condition" },
    { key: "available_parts", label: "Available parts" },
  ],

  spare_parts: [
    { key: "part_name", label: "Part name" },
    { key: "manufacturer", label: "Manufacturer" },
    { key: "part_number", label: "Part number" },
    { key: "oem_number", label: "OEM number" },
    { key: "fits_brand", label: "Fits brand" },
    { key: "fits_model", label: "Fits model" },
    { key: "fits_generation", label: "Fits generation / body code" },
    { key: "fits_year_from", label: "Fits year from" },
    { key: "fits_year_to", label: "Fits year to" },
    { key: "fits_engine", label: "Fits engine" },
    { key: "fits_gearbox", label: "Fits gearbox" },
    { key: "side_position", label: "Side / position" },
    { key: "condition", label: "Condition" },
  ],

  tires: [
    { key: "width", label: "Width" },
    { key: "profile", label: "Profile" },
    { key: "diameter", label: "Diameter" },
    { key: "season", label: "Season" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "load_index", label: "Load index" },
    { key: "speed_index", label: "Speed index" },
    { key: "tread_depth", label: "Tread depth" },
    { key: "quantity", label: "Quantity" },
    { key: "dot_year", label: "DOT year" },
  ],

  wheels_rims: [
    { key: "diameter", label: "Diameter" },
    { key: "width", label: "Width" },
    { key: "bolt_pattern", label: "Bolt pattern" },
    { key: "offset", label: "ET / offset" },
    { key: "center_bore", label: "Center bore" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "material", label: "Material" },
    { key: "quantity", label: "Quantity" },
    { key: "condition", label: "Condition" },
  ],

  accessories: [
    { key: "accessory_type", label: "Accessory type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "fits_brand", label: "Fits brand" },
    { key: "fits_model", label: "Fits model" },
    { key: "part_number", label: "Part number" },
    { key: "condition", label: "Condition" },
  ],

  phones: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "storage", label: "Storage" },
    { key: "ram", label: "RAM" },
    { key: "color", label: "Color" },
    { key: "sim_type", label: "SIM type" },
    { key: "battery_health", label: "Battery health" },
    { key: "screen_condition", label: "Screen condition" },
    { key: "network_lock", label: "Network lock" },
    { key: "imei_serial", label: "IMEI / serial number" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  computers: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "processor", label: "Processor" },
    { key: "ram", label: "RAM" },
    { key: "storage", label: "Storage" },
    { key: "graphics_card", label: "Graphics card" },
    { key: "screen_size", label: "Screen size" },
    { key: "operating_system", label: "Operating system" },
    { key: "battery_health", label: "Battery health" },
    { key: "serial_number", label: "Serial number" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  tv_audio: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "screen_size", label: "Screen size" },
    { key: "display_type", label: "Display type" },
    { key: "resolution", label: "Resolution" },
    { key: "smart_tv", label: "Smart TV" },
    { key: "audio_type", label: "Audio type" },
    { key: "power_output", label: "Power output" },
    { key: "connections", label: "Connections" },
    { key: "remote_included", label: "Remote included" },
    { key: "serial_number", label: "Serial number" },
  ],

  cameras: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "camera_type", label: "Camera type" },
    { key: "lens_included", label: "Lens included" },
    { key: "sensor_size", label: "Sensor size" },
    { key: "megapixels", label: "Megapixels" },
    { key: "shutter_count", label: "Shutter count" },
    { key: "video_resolution", label: "Video resolution" },
    { key: "battery_count", label: "Battery count" },
    { key: "memory_card_included", label: "Memory card included" },
    { key: "serial_number", label: "Serial number" },
  ],

  gaming: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "platform", label: "Platform" },
    { key: "storage", label: "Storage" },
    { key: "controller_count", label: "Controller count" },
    { key: "game_count", label: "Game count" },
    { key: "online_account_included", label: "Online account included" },
    { key: "included_accessories", label: "Included accessories" },
    { key: "serial_number", label: "Serial number" },
  ],

  smart_home: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "device_type", label: "Device type" },
    { key: "compatibility", label: "Compatibility" },
    { key: "connection_type", label: "Connection type" },
    { key: "power_type", label: "Power type" },
    { key: "app_support", label: "App support" },
    { key: "included_accessories", label: "Included accessories" },
    { key: "serial_number", label: "Serial number" },
  ],

  components: [
    { key: "component_type", label: "Component type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "socket_compatibility", label: "Socket / compatibility" },
    { key: "capacity", label: "Capacity" },
    { key: "speed", label: "Speed" },
    { key: "power_rating", label: "Power rating" },
    { key: "condition", label: "Condition" },
    { key: "serial_number", label: "Serial number" },
  ],

  electronics_accessories: [
    { key: "accessory_type", label: "Accessory type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "compatibility", label: "Compatibility" },
    { key: "connection_type", label: "Connection type" },
    { key: "color", label: "Color" },
    { key: "condition", label: "Condition" },
    { key: "quantity", label: "Quantity" },
  ],

  apartments: [
    { key: "listing_type", label: "Listing type" },
    { key: "property_type", label: "Property type" },
    { key: "rooms", label: "Rooms" },
    { key: "area", label: "Area (m²)" },
    { key: "floor", label: "Floor" },
    { key: "total_floors", label: "Total floors" },
    { key: "year_built", label: "Year built" },
    { key: "condition", label: "Condition" },
    { key: "heating_type", label: "Heating type" },
    { key: "energy_class", label: "Energy class" },
    { key: "balcony", label: "Balcony" },
    { key: "furnished", label: "Furnished" },
    { key: "parking", label: "Parking" },
    { key: "storage_room", label: "Storage room" },
    { key: "bathroom_count", label: "Bathroom count" },
    { key: "district", label: "District / neighborhood" },
  ],

  houses: [
    { key: "listing_type", label: "Listing type" },
    { key: "house_type", label: "House type" },
    { key: "rooms", label: "Rooms" },
    { key: "living_area", label: "Living area (m²)" },
    { key: "land_area", label: "Land area" },
    { key: "floors", label: "Floors" },
    { key: "year_built", label: "Year built" },
    { key: "condition", label: "Condition" },
    { key: "heating_type", label: "Heating type" },
    { key: "energy_class", label: "Energy class" },
    { key: "garage", label: "Garage" },
    { key: "sauna", label: "Sauna" },
    { key: "terrace", label: "Terrace" },
    { key: "water_supply", label: "Water supply" },
    { key: "sewer_connection", label: "Sewer connection" },
    { key: "district", label: "District / neighborhood" },
  ],

  land: [
    { key: "land_type", label: "Land type" },
    { key: "area", label: "Area" },
    { key: "purpose", label: "Purpose" },
    { key: "detailed_plan", label: "Detailed plan" },
    { key: "electricity", label: "Electricity" },
    { key: "water", label: "Water" },
    { key: "sewer", label: "Sewer" },
    { key: "road_access", label: "Road access" },
    { key: "district", label: "District / neighborhood" },
  ],

  commercial_property: [
    { key: "property_type", label: "Property type" },
    { key: "area", label: "Area" },
    { key: "floor", label: "Floor" },
    { key: "purpose", label: "Purpose" },
    { key: "parking", label: "Parking" },
    { key: "loading_access", label: "Loading access" },
    { key: "heating", label: "Heating" },
    { key: "security", label: "Security" },
    { key: "district", label: "District / neighborhood" },
  ],

  garages: [
    { key: "area", label: "Area" },
    { key: "electricity", label: "Electricity" },
    { key: "heating", label: "Heating" },
    { key: "security", label: "Security" },
    { key: "water", label: "Water" },
    { key: "district", label: "District / neighborhood" },
  ],

  vacation_property: [
    { key: "property_type", label: "Property type" },
    { key: "rooms", label: "Rooms" },
    { key: "area", label: "Area" },
    { key: "beds", label: "Beds" },
    { key: "sauna", label: "Sauna" },
    { key: "pool", label: "Pool" },
    { key: "beach_access", label: "Beach access" },
    { key: "seasonal_year_round", label: "Seasonal / year-round" },
    { key: "district", label: "District / neighborhood" },
  ],

  men: [
    { key: "category_type", label: "Category type" },
    { key: "brand", label: "Brand" },
    { key: "size", label: "Size" },
    { key: "fit", label: "Fit" },
    { key: "color", label: "Color" },
    { key: "material", label: "Material" },
    { key: "condition", label: "Condition" },
    { key: "season", label: "Season" },
    { key: "authenticity", label: "Authenticity" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  women: [
    { key: "category_type", label: "Category type" },
    { key: "brand", label: "Brand" },
    { key: "size", label: "Size" },
    { key: "fit", label: "Fit" },
    { key: "color", label: "Color" },
    { key: "material", label: "Material" },
    { key: "condition", label: "Condition" },
    { key: "season", label: "Season" },
    { key: "authenticity", label: "Authenticity" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  kids: [
    { key: "category_type", label: "Category type" },
    { key: "brand", label: "Brand" },
    { key: "size_age", label: "Size / age" },
    { key: "gender", label: "Gender" },
    { key: "color", label: "Color" },
    { key: "material", label: "Material" },
    { key: "condition", label: "Condition" },
    { key: "season", label: "Season" },
  ],

  shoes: [
    { key: "gender", label: "Gender" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "size", label: "Size" },
    { key: "color", label: "Color" },
    { key: "material", label: "Material" },
    { key: "condition", label: "Condition" },
    { key: "season", label: "Season" },
    { key: "heel_height", label: "Heel height" },
    { key: "authenticity", label: "Authenticity" },
    { key: "original_box_included", label: "Original box included" },
  ],

  watches: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "movement_type", label: "Movement type" },
    { key: "case_material", label: "Case material" },
    { key: "case_size", label: "Case size" },
    { key: "water_resistance", label: "Water resistance" },
    { key: "condition", label: "Condition" },
    { key: "box_papers_included", label: "Box / papers included" },
    { key: "authenticity", label: "Authenticity" },
    { key: "serial_number", label: "Serial number" },
  ],

  bags: [
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "material", label: "Material" },
    { key: "color", label: "Color" },
    { key: "size", label: "Size" },
    { key: "condition", label: "Condition" },
    { key: "authenticity", label: "Authenticity" },
    { key: "dust_bag_box_included", label: "Dust bag / box included" },
    { key: "serial_number", label: "Serial number" },
  ],

  jewelry: [
    { key: "jewelry_type", label: "Jewelry type" },
    { key: "brand", label: "Brand" },
    { key: "material", label: "Material" },
    { key: "gemstone", label: "Gemstone" },
    { key: "size", label: "Size" },
    { key: "weight", label: "Weight" },
    { key: "condition", label: "Condition" },
    { key: "authenticity", label: "Authenticity" },
    { key: "certificate_included", label: "Certificate included" },
  ],

  power_tools: [
    { key: "tool_type", label: "Tool type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "power_source", label: "Power source" },
    { key: "voltage", label: "Voltage" },
    { key: "power_rating", label: "Power rating" },
    { key: "battery_included", label: "Battery included" },
    { key: "battery_count", label: "Battery count" },
    { key: "charger_included", label: "Charger included" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
    { key: "serial_number", label: "Serial number" },
  ],

  hand_tools: [
    { key: "tool_type", label: "Tool type" },
    { key: "brand", label: "Brand" },
    { key: "material", label: "Material" },
    { key: "size", label: "Size" },
    { key: "condition", label: "Condition" },
    { key: "set_single", label: "Set / single item" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  workshop_equipment: [
    { key: "equipment_type", label: "Equipment type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "power_source", label: "Power source" },
    { key: "voltage", label: "Voltage" },
    { key: "capacity", label: "Capacity" },
    { key: "dimensions", label: "Dimensions" },
    { key: "weight", label: "Weight" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
    { key: "serial_number", label: "Serial number" },
  ],

  industrial_equipment: [
    { key: "equipment_type", label: "Equipment type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "power_source", label: "Power source" },
    { key: "voltage", label: "Voltage" },
    { key: "capacity", label: "Capacity" },
    { key: "working_pressure", label: "Working pressure" },
    { key: "weight", label: "Weight" },
    { key: "dimensions", label: "Dimensions" },
    { key: "condition", label: "Condition" },
    { key: "serial_number", label: "Serial number" },
  ],

  safety_equipment: [
    { key: "equipment_type", label: "Equipment type" },
    { key: "brand", label: "Brand" },
    { key: "size", label: "Size" },
    { key: "certification", label: "Certification" },
    { key: "condition", label: "Condition" },
    { key: "expiration_date", label: "Expiration date" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  furniture: [
    { key: "furniture_type", label: "Furniture type" },
    { key: "brand", label: "Brand" },
    { key: "material", label: "Material" },
    { key: "color", label: "Color" },
    { key: "dimensions", label: "Dimensions" },
    { key: "assembly_required", label: "Assembly required" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  appliances: [
    { key: "appliance_type", label: "Appliance type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "energy_class", label: "Energy class" },
    { key: "power_source", label: "Power source" },
    { key: "capacity", label: "Capacity" },
    { key: "dimensions", label: "Dimensions" },
    { key: "condition", label: "Condition" },
    { key: "warranty_remaining", label: "Warranty remaining" },
    { key: "included_accessories", label: "Included accessories" },
    { key: "serial_number", label: "Serial number" },
  ],

  garden_tools: [
    { key: "tool_type", label: "Tool type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "power_source", label: "Power source" },
    { key: "voltage", label: "Voltage" },
    { key: "battery_included", label: "Battery included" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  decor: [
    { key: "decor_type", label: "Decor type" },
    { key: "material", label: "Material" },
    { key: "color", label: "Color" },
    { key: "style", label: "Style" },
    { key: "dimensions", label: "Dimensions" },
    { key: "condition", label: "Condition" },
  ],

  lighting: [
    { key: "lighting_type", label: "Lighting type" },
    { key: "brand", label: "Brand" },
    { key: "power_source", label: "Power source" },
    { key: "bulb_type", label: "Bulb type" },
    { key: "color_temperature", label: "Color temperature" },
    { key: "smart_lighting_support", label: "Smart lighting support" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  gym_equipment: [
    { key: "equipment_type", label: "Equipment type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "weight_resistance", label: "Weight / resistance" },
    { key: "dimensions", label: "Dimensions" },
    { key: "foldable", label: "Foldable" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  bicycles: [
    { key: "bike_type", label: "Bike type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "frame_size", label: "Frame size" },
    { key: "wheel_size", label: "Wheel size" },
    { key: "material", label: "Material" },
    { key: "gear_count", label: "Gear count" },
    { key: "suspension", label: "Suspension" },
    { key: "brake_type", label: "Brake type" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
    { key: "serial_number", label: "Serial number" },
  ],

  winter_sports: [
    { key: "equipment_type", label: "Equipment type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "size", label: "Size" },
    { key: "binding_included", label: "Binding included" },
    { key: "boot_size", label: "Boot size" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  camping: [
    { key: "equipment_type", label: "Equipment type" },
    { key: "brand", label: "Brand" },
    { key: "capacity", label: "Capacity" },
    { key: "weight", label: "Weight" },
    { key: "dimensions", label: "Dimensions" },
    { key: "season_rating", label: "Season rating" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  fishing: [
    { key: "equipment_type", label: "Equipment type" },
    { key: "brand", label: "Brand" },
    { key: "model", label: "Model" },
    { key: "length", label: "Length" },
    { key: "power_rating", label: "Power rating" },
    { key: "reel_included", label: "Reel included" },
    { key: "line_included", label: "Line included" },
    { key: "condition", label: "Condition" },
    { key: "included_accessories", label: "Included accessories" },
  ],

  art: [
    { key: "art_type", label: "Art type" },
    { key: "artist", label: "Artist" },
    { key: "title", label: "Title" },
    { key: "year_period", label: "Year / period" },
    { key: "material", label: "Material" },
    { key: "dimensions", label: "Dimensions" },
    { key: "signed", label: "Signed" },
    { key: "certificate_included", label: "Certificate included" },
    { key: "condition", label: "Condition" },
    { key: "frame_included", label: "Frame included" },
  ],

  vintage: [
    { key: "item_type", label: "Item type" },
    { key: "brand_maker", label: "Brand / maker" },
    { key: "year_era", label: "Year / era" },
    { key: "material", label: "Material" },
    { key: "origin_country", label: "Origin country" },
    { key: "condition", label: "Condition" },
    { key: "restored", label: "Restored" },
  ],

  coins: [
    { key: "country", label: "Country" },
    { key: "year", label: "Year" },
    { key: "currency", label: "Currency" },
    { key: "material", label: "Material" },
    { key: "denomination", label: "Denomination" },
    { key: "mint_mark", label: "Mint mark" },
    { key: "condition_grading", label: "Condition / grading" },
    { key: "certificate_included", label: "Certificate included" },
  ],

  military: [
    { key: "item_type", label: "Item type" },
    { key: "country", label: "Country" },
    { key: "era", label: "Era" },
    { key: "original_reproduction", label: "Original / reproduction" },
    { key: "material", label: "Material" },
    { key: "condition", label: "Condition" },
    { key: "serial_markings", label: "Serial number / markings" },
    { key: "certificate_included", label: "Certificate included" },
  ],

  memorabilia: [
    { key: "item_type", label: "Item type" },
    { key: "related_person_event", label: "Related person / event" },
    { key: "year_era", label: "Year / era" },
    { key: "signed", label: "Signed" },
    { key: "certificate_included", label: "Certificate included" },
    { key: "condition", label: "Condition" },
  ],

  lumber: [
    { key: "material_type", label: "Material type" },
    { key: "wood_type", label: "Wood type" },
    { key: "length", label: "Length" },
    { key: "width", label: "Width" },
    { key: "thickness", label: "Thickness" },
    { key: "moisture_level", label: "Moisture level" },
    { key: "treatment_type", label: "Treatment type" },
    { key: "quantity", label: "Quantity" },
    { key: "condition", label: "Condition" },
  ],

  concrete: [
    { key: "material_type", label: "Material type" },
    { key: "strength_class", label: "Strength class" },
    { key: "weight", label: "Weight" },
    { key: "bag_size", label: "Bag size" },
    { key: "quantity", label: "Quantity" },
    { key: "condition", label: "Condition" },
  ],

  insulation: [
    { key: "insulation_type", label: "Insulation type" },
    { key: "material", label: "Material" },
    { key: "thickness", label: "Thickness" },
    { key: "coverage_area", label: "Coverage area" },
    { key: "fire_rating", label: "Fire rating" },
    { key: "quantity", label: "Quantity" },
    { key: "condition", label: "Condition" },
  ],

  roofing: [
    { key: "roofing_type", label: "Roofing type" },
    { key: "material", label: "Material" },
    { key: "color", label: "Color" },
    { key: "dimensions", label: "Dimensions" },
    { key: "coverage_area", label: "Coverage area" },
    { key: "quantity", label: "Quantity" },
    { key: "condition", label: "Condition" },
  ],

  plumbing: [
    { key: "plumbing_type", label: "Plumbing type" },
    { key: "material", label: "Material" },
    { key: "diameter", label: "Diameter" },
    { key: "length", label: "Length" },
    { key: "compatibility", label: "Compatibility" },
    { key: "pressure_rating", label: "Pressure rating" },
    { key: "condition", label: "Condition" },
    { key: "quantity", label: "Quantity" },
  ],
};

export function getCategoryFields(subcategory: string) {
  return CATEGORY_FIELDS[subcategory] || [];
}
