export const CATEGORY_TREE = [
  {
    value: "vehicles",
    label: "Vehicles",
    children: [
      {
        value: "cars",
        label: "Cars",
        children: [
          { value: "passenger_cars", label: "Passenger cars" },
          { value: "suv_offroad", label: "SUVs / Off-road" },
          { value: "vans_minibuses", label: "Vans & Minibuses" },
          { value: "pickup_trucks", label: "Pickup trucks" },
          { value: "motorhomes_campers", label: "Motorhomes / Campers" },
          { value: "racing_vehicles", label: "Racing vehicles" },
        ],
      },
      {
        value: "motorcycles",
        label: "Motorcycles",
        children: [
          { value: "sport_bikes", label: "Sport bikes" },
          { value: "cruisers", label: "Cruisers" },
          { value: "touring", label: "Touring" },
          { value: "enduro_mx", label: "Enduro / MX" },
          { value: "scooters", label: "Scooters" },
          { value: "atv_utv", label: "ATV / UTV" },
          { value: "snowmobiles", label: "Snowmobiles" },
        ],
      },
      {
        value: "trucks_commercial",
        label: "Trucks & Commercial",
        children: [
          { value: "trucks", label: "Trucks" },
          { value: "semi_trucks", label: "Semi trucks" },
          { value: "buses", label: "Buses" },
          { value: "commercial_trailers", label: "Commercial trailers" },
        ],
      },
      {
        value: "agricultural_heavy_machinery",
        label: "Agricultural & Heavy Machinery",
        children: [
          { value: "tractors", label: "Tractors" },
          { value: "harvesters", label: "Harvesters" },
          { value: "excavators", label: "Excavators" },
          { value: "forestry_machinery", label: "Forestry machinery" },
          { value: "construction_machinery", label: "Construction machinery" },
          {
            value: "agricultural_attachments_implements",
            label: "Agricultural attachments & implements"
          },
          {
            value: "agricultural_heavy_machinery_spare_parts",
            label: "Agricultural & Heavy Machinery Spare Parts"
          },
        ],
      },
      {
        value: "marine",
        label: "Marine",
        children: [
          { value: "boats", label: "Boats" },
          { value: "yachts", label: "Yachts" },
          { value: "jet_skis", label: "Jet skis" },
          { value: "boat_trailers", label: "Boat trailers" },
          { value: "outboard_motors", label: "Outboard motors" },
        ],
      },
      {
        value: "aviation",
        label: "Aviation",
        children: [
          { value: "airplanes", label: "Airplanes" },
          { value: "helicopters", label: "Helicopters" },
          { value: "ultralights", label: "Ultralights" },
          { value: "drones", label: "Drones" },
          { value: "aircraft_parts", label: "Aircraft parts" },
        ],
      },
      {
        value: "trailers",
        label: "Trailers",
        children: [
          { value: "light_trailers", label: "Light trailers" },
          { value: "car_trailers", label: "Car trailers" },
          { value: "cargo_trailers", label: "Cargo trailers" },
          { value: "caravans", label: "Caravans" },
      { value: "horse_livestock_trailers", label: "Horse & livestock trailers" },
        ],
      },
      {
        value: "vehicle_parts",
        label: "Vehicle Parts",
        children: [
          { value: "engines_engine_parts", label: "Engines & Engine parts" },
          { value: "transmission_drivetrain", label: "Transmission & Drivetrain" },
          { value: "suspension_steering", label: "Suspension & Steering" },
          { value: "brakes", label: "Brakes" },
          { value: "electrical_parts", label: "Electrical parts" },
          { value: "batteries", label: "Batteries" },
          { value: "starters_alternators", label: "Starters & Alternators" },
          { value: "body_parts", label: "Body parts" },
          { value: "lights_lamps", label: "Lights & Lamps" },
          { value: "interior_parts", label: "Interior parts" },
          { value: "exhaust_parts", label: "Exhaust parts" },
          { value: "cooling_heating", label: "Cooling & Heating" },
          { value: "fuel_system", label: "Fuel system" },
          { value: "tires", label: "Tires" },
          { value: "wheels_rims", label: "Wheels / Rims" },
          { value: "accessories", label: "Accessories" },
          { value: "riding_racing_gear", label: "Riding & racing gear" },
          { value: "spare_parts", label: "Other spare parts" },
          { value: "vehicle_for_parts", label: "Complete vehicle for parts" },
        ],
      },
    ],
  },
  {
    value: "electronics",
    label: "Electronics",
    children: [
      { value: "phones", label: "Phones" },
      { value: "computers", label: "Computers" },
      { value: "tv_audio", label: "TV & Audio" },
      { value: "cameras", label: "Cameras" },
      { value: "gaming", label: "Gaming" },
      { value: "smart_home", label: "Smart home" },
      { value: "components", label: "Components" },
      { value: "electronics_accessories", label: "Accessories" },
      { value: "other_electronics", label: "Other electronics" },
    ],
  },
  {
    value: "real_estate",
    label: "Real Estate",
    children: [
      { value: "apartments", label: "Apartments" },
      { value: "houses", label: "Houses" },
      { value: "land", label: "Land" },
      { value: "commercial_property", label: "Commercial property" },
      { value: "garages", label: "Garages" },
      { value: "vacation_property", label: "Vacation property" },
    ],
  },
  {
    value: "clothing_fashion",
    label: "Clothing & Fashion",
    children: [
      { value: "men", label: "Men" },
      { value: "women", label: "Women" },
      { value: "kids", label: "Kids" },
      { value: "workwear", label: "Workwear" },
      { value: "shoes", label: "Shoes" },
      { value: "watches", label: "Watches" },
      { value: "bags", label: "Bags" },
      { value: "jewelry", label: "Jewelry" },
      { value: "other_clothing_fashion", label: "Other clothing & fashion" },
    ],
  },
  {
    value: "tools_industrial",
    label: "Tools & Industrial",
    children: [
      { value: "power_tools", label: "Power tools" },
      { value: "hand_tools", label: "Hand tools" },
      { value: "workshop_equipment", label: "Workshop equipment" },
      { value: "industrial_equipment", label: "Industrial equipment" },
      { value: "safety_equipment", label: "Safety equipment" },
      { value: "other_tools_industrial", label: "Other tools & industrial" },
    ],
  },
  {
    value: "home_garden",
    label: "Home & Garden",
    children: [
      { value: "furniture", label: "Furniture" },
      { value: "appliances", label: "Appliances" },
      { value: "garden_tools", label: "Garden tools" },
      { value: "plants_seedlings", label: "Plants & seedlings" },
      { value: "seeds", label: "Seeds" },
      { value: "crops_produce", label: "Crops & produce" },
      { value: "farm_supplies", label: "Farm supplies" },
      { value: "animal_feed", label: "Animal feed" },
      { value: "greenhouses", label: "Greenhouses" },
      { value: "decor", label: "Decor" },
      { value: "lighting", label: "Lighting" },
      { value: "kitchenware", label: "Kitchenware" },
      { value: "home_textiles", label: "Home textiles" },
      { value: "household_supplies", label: "Household supplies" },
      { value: "bathroom", label: "Bathroom" },
      { value: "heating_fuels", label: "Firewood, pellets & heating fuel" },
      { value: "heating_equipment", label: "Stoves & heating equipment" },
      { value: "outdoor_furniture", label: "Outdoor furniture" },
      { value: "other_home_garden", label: "Other home & garden" },
    ],
  },
  {
    value: "sports_outdoor",
    label: "Sports & Outdoor",
    children: [
      { value: "gym_equipment", label: "Gym equipment" },
      { value: "bicycles", label: "Bicycles" },
      { value: "winter_sports", label: "Winter sports" },
      { value: "camping", label: "Camping" },
      { value: "fishing", label: "Fishing" },
      { value: "other_sports_outdoor", label: "Other sports & outdoor" },
      {
        value: "equestrian_horse_supplies",
        label: "Equestrian & Horse Supplies",
        children: [
          { value: "saddles_accessories", label: "Saddles & accessories" },
          { value: "bridles_halters_tack", label: "Bridles, halters & tack" },
          { value: "rider_clothing_safety", label: "Rider clothing & safety" },
          { value: "horse_blankets_textiles", label: "Horse blankets & stable textiles" },
          { value: "horse_grooming_care", label: "Horse grooming & care equipment" },
          { value: "stable_paddock_equipment", label: "Stable & paddock equipment" },
          { value: "driving_carriage_equipment", label: "Driving & carriage equipment" },
          { value: "other_equestrian_supplies", label: "Other equestrian supplies" },
        ],
      },
    ],
  },
  {
    value: "antiques_collectibles",
    label: "Antiques & Collectibles",
    children: [
      { value: "art", label: "Art" },
      { value: "vintage", label: "Vintage" },
      { value: "coins", label: "Coins" },
      { value: "military", label: "Military" },
      { value: "memorabilia", label: "Memorabilia" },
      { value: "other_antiques_collectibles", label: "Other antiques & collectibles" },
    ],
  },
  {
    value: "building_materials",
    label: "Building Materials",
    children: [
      { value: "lumber", label: "Lumber" },
      { value: "concrete", label: "Concrete" },
      { value: "insulation", label: "Insulation" },
      { value: "roofing", label: "Roofing" },
      { value: "plumbing", label: "Plumbing" },
      { value: "other_building_materials", label: "Other building materials" },
    ],
  },
  {
    value: "children_baby",
    label: "Baby & Child Equipment",
    children: [
      { value: "strollers_prams", label: "Strollers & prams" },
      { value: "child_car_seats", label: "Child car seats" },
      { value: "nursery_furniture", label: "Nursery furniture" },
      { value: "baby_feeding_care", label: "Baby feeding & care" },
      { value: "baby_safety_accessories", label: "Baby safety & accessories" },
      { value: "other_children_baby", label: "Other baby & child equipment" },
    ],
  },
  {
    value: "pet_supplies",
    label: "Pet Supplies",
    children: [
      { value: "dog_supplies", label: "Dog supplies" },
      { value: "cat_supplies", label: "Cat supplies" },
      { value: "aquariums_terrariums", label: "Aquariums & terrariums" },
      { value: "cages_housing", label: "Cages & animal housing" },
      { value: "pet_transport_grooming", label: "Pet transport & grooming" },
      { value: "other_pet_supplies", label: "Other pet supplies" },
    ],
  },
  {
    value: "books_music_media",
    label: "Books, Music & Media",
    children: [
      { value: "books", label: "Books" },
      { value: "magazines_comics", label: "Magazines & comics" },
      { value: "music_movies", label: "Music & movies" },
      { value: "musical_instruments", label: "Musical instruments" },
      { value: "instrument_accessories", label: "Instrument accessories" },
      { value: "other_books_media", label: "Other books & media" },
    ],
  },
  {
    value: "hobbies_toys_crafts",
    label: "Hobbies, Toys & Crafts",
    children: [
      { value: "toys", label: "Toys" },
      { value: "board_games_puzzles", label: "Board games & puzzles" },
      { value: "arts_crafts", label: "Arts & crafts" },
      { value: "model_rc_hobbies", label: "Models & RC hobbies" },
      { value: "sewing_knitting", label: "Sewing & knitting" },
      { value: "other_hobbies_toys", label: "Other hobbies & toys" },
    ],
  },
  {
    value: "office_business",
    label: "Office & Business Equipment",
    children: [
      { value: "office_equipment", label: "Office equipment" },
      { value: "printers_scanners", label: "Printers & scanners" },
      { value: "office_furniture", label: "Office furniture" },
      { value: "retail_warehouse_equipment", label: "Retail & warehouse equipment" },
      { value: "presentation_equipment", label: "Presentation equipment" },
      { value: "other_office_business", label: "Other office & business equipment" },
    ],
  },
  {
    value: "general",
    label: "General",
    children: [],
  },
] as const;

export const CATEGORY_LABELS = {
  en: {},
  et: {
    vehicles: "Sõidukid",
    cars: "Autod",
    passenger_cars: "Sõiduautod",
    suv_offroad: "Maasturid",
    vans_minibuses: "Kaubikud ja väikebussid",
    pickup_trucks: "Pikapid",
    motorhomes_campers: "Matkaautod",
    racing_vehicles: "Võidusõidukid",

    motorcycles: "Mootorrattad",
    sport_bikes: "Sportmootorrattad",
    cruisers: "Cruiserid",
    touring: "Matkamootorrattad",
    enduro_mx: "Enduro / MX",
    scooters: "Rollerid",
    atv_utv: "ATV / UTV",
    snowmobiles: "Mootorsaanid",

    trucks_commercial: "Veoautod ja tarbesõidukid",
    trucks: "Veoautod",
    semi_trucks: "Sadulveokid",
    buses: "Bussid",
    commercial_trailers: "Haagised ja poolhaagised",

    agricultural_heavy_machinery: "Põllu- ja rasketehnika",
    tractors: "Traktorid",
    harvesters: "Kombainid",
    excavators: "Ekskavaatorid",
    forestry_machinery: "Metsatehnika",
    construction_machinery: "Ehitusmasinad",
    agricultural_attachments_implements: "Põllumajanduse lisaseadmed",
    agricultural_heavy_machinery_spare_parts: "Põllu- ja rasketehnika varuosad",

    marine: "Veetehnika",
    boats: "Paadid",
    yachts: "Jahid",
    jet_skis: "Jetid",
    boat_trailers: "Paadihaagised",
    outboard_motors: "Päramootorid",

    aviation: "Lennundus",
    airplanes: "Lennukid",
    helicopters: "Helikopterid",
    ultralights: "Ultrakerged lennukid",
    drones: "Droonid",
    aircraft_parts: "Lennukiosad",

    trailers: "Haagised",
    light_trailers: "Kerg-haagised",
    car_trailers: "Autohaagised",
    cargo_trailers: "Kaubahaagised",
    caravans: "Haagissuvilad",

    vehicle_parts: "Sõidukite varuosad",
    engines_engine_parts: "Mootorid ja mootoriosad",
    transmission_drivetrain: "Käigukast ja jõuülekanne",
    suspension_steering: "Vedrustus ja roolisüsteem",
    brakes: "Pidurid",
    electrical_parts: "Elektriosad",
    batteries: "Akud",
    starters_alternators: "Starterid ja generaatorid",
    body_parts: "Kereosad",
    lights_lamps: "Tuled ja lambid",
    interior_parts: "Salongiosad",
    exhaust_parts: "Väljalaskesüsteem",
    cooling_heating: "Jahutus ja küte",
    fuel_system: "Kütusesüsteem",
    tires: "Rehvid",
    wheels_rims: "Veljed",
    accessories: "Lisavarustus",
    riding_racing_gear: "Sõidu- ja võidusõiduvarustus",
    spare_parts: "Muud varuosad",
    vehicle_for_parts: "Sõiduk varuosadeks",

    electronics: "Elektroonika",
    phones: "Telefonid",
    computers: "Arvutid",
    tv_audio: "TV ja audio",
    cameras: "Kaamerad",
    gaming: "Mängud ja konsoolid",
    smart_home: "Nutikodu",
    components: "Komponendid",
    electronics_accessories: "Elektroonika lisatarvikud",

    real_estate: "Kinnisvara",
    apartments: "Korterid",
    houses: "Majad",
    land: "Maa",
    commercial_property: "Äripinnad",
    garages: "Garaažid",
    vacation_property: "Puhkekinnisvara",

    clothing_fashion: "Riided ja mood",
    men: "Mehed",
    women: "Naised",
    kids: "Lapsed",
    workwear: "Tööriided",
    shoes: "Jalanõud",
    watches: "Kellad",
    bags: "Kotid",
    jewelry: "Ehted",

    tools_industrial: "Tööriistad ja tööstus",
    power_tools: "Elektritööriistad",
    hand_tools: "Käsitööriistad",
    workshop_equipment: "Töökoja seadmed",
    industrial_equipment: "Tööstusseadmed",
    safety_equipment: "Ohutusvarustus",

    home_garden: "Kodu ja aed",
    furniture: "Mööbel",
    appliances: "Kodumasinad",
    garden_tools: "Aiatööriistad",
    plants_seedlings: "Taimed ja istikud",
    seeds: "Seemned",
    crops_produce: "Saak ja toodang",
    farm_supplies: "Talutarbed",
    animal_feed: "Loomasööt",
    greenhouses: "Kasvuhooned",
    decor: "Dekoratsioon",
    lighting: "Valgustid",

    sports_outdoor: "Sport ja vaba aeg",
    gym_equipment: "Treeningvahendid",
    bicycles: "Jalgrattad",
    winter_sports: "Talvesport",
    camping: "Matkamine",
    fishing: "Kalastus",

    antiques_collectibles: "Antiik ja kollektsioneerimine",
    art: "Kunst",
    vintage: "Vanaaegne",
    coins: "Mündid",
    military: "Militaar",
    memorabilia: "Meened",

    building_materials: "Ehitusmaterjalid",
    lumber: "Puitmaterjal",
    concrete: "Betoon",
    insulation: "Isolatsioon",
    roofing: "Katusematerjalid",
    plumbing: "Torutööd",

    other_electronics: "Muu elektroonika",
    other_clothing_fashion: "Muud riided ja moeasjad",
    other_tools_industrial: "Muud tööriistad ja tööstuskaubad",
    kitchenware: "Köögitarbed",
    home_textiles: "Kodutekstiil",
    household_supplies: "Majapidamistarbed",
    bathroom: "Vannitoatarbed",
    heating_fuels: "Küttepuud, pellet ja küttematerjal",
    heating_equipment: "Ahjud ja kütteseadmed",
    outdoor_furniture: "Aiamööbel",
    other_home_garden: "Muud kodu- ja aiakaubad",
    other_sports_outdoor: "Muud spordi- ja vabaajakaubad",
    other_antiques_collectibles: "Muu antiik ja kollektsioneerimine",
    other_building_materials: "Muud ehitusmaterjalid",

    children_baby: "Lapsed ja beebitarbed",
    strollers_prams: "Lapsevankrid ja kärud",
    child_car_seats: "Turvatoolid",
    nursery_furniture: "Lastetoa mööbel",
    baby_feeding_care: "Beebi toitmine ja hooldus",
    baby_safety_accessories: "Beebi ohutus ja lisatarvikud",
    other_children_baby: "Muud laste- ja beebitarbed",

    pet_supplies: "Lemmikloomatarbed",
    dog_supplies: "Koeratarbed",
    cat_supplies: "Kassitarbed",
    aquariums_terrariums: "Akvaariumid ja terraariumid",
    cages_housing: "Puurid ja loomade eluasemed",
    pet_transport_grooming: "Lemmiklooma transport ja hooldus",
    other_pet_supplies: "Muud lemmikloomatarbed",

    books_music_media: "Raamatud, muusika ja meedia",
    books: "Raamatud",
    magazines_comics: "Ajakirjad ja koomiksid",
    music_movies: "Muusika ja filmid",
    musical_instruments: "Muusikariistad",
    instrument_accessories: "Muusikariistade lisatarvikud",
    other_books_media: "Muud raamatud ja meedia",

    hobbies_toys_crafts: "Hobid, mänguasjad ja käsitöö",
    toys: "Mänguasjad",
    board_games_puzzles: "Lauamängud ja pusled",
    arts_crafts: "Kunsti- ja käsitöötarbed",
    model_rc_hobbies: "Mudelid ja RC-hobid",
    sewing_knitting: "Õmblemine ja kudumine",
    other_hobbies_toys: "Muud hobid ja mänguasjad",

    office_business: "Kontor ja äritehnika",
    office_equipment: "Kontoritehnika",
    printers_scanners: "Printerid ja skannerid",
    office_furniture: "Kontorimööbel",
    retail_warehouse_equipment: "Kaubandus- ja laoseadmed",
    presentation_equipment: "Esitlustehnika",
    other_office_business: "Muu kontori- ja äritehnika",

    general: "Üldine",
    equestrian_horse_supplies: "Ratsutamine ja hobutarbed",
    saddles_accessories: "Sadulad ja sadulatarvikud",
    bridles_halters_tack: "Valjad, päitsed ja muu ratsavarustus",
    rider_clothing_safety: "Ratsaniku riietus ja turvavarustus",
    horse_blankets_textiles: "Hobusetekid ja tallitekstiil",
    horse_grooming_care: "Hobuse hooldus- ja puhastustarbed",
    stable_paddock_equipment: "Talli- ja koplitarbed",
    driving_carriage_equipment: "Rakmed ja vankrivarustus",
    other_equestrian_supplies: "Muud ratsutamis- ja hobutarbed",
    horse_livestock_trailers: "Hobuse- ja loomaveohaagised",
  },
} as const;

export function getCategoryLabel(
  value: string,
  fallback: string,
  language: string | null | undefined
) {
  if (language === "et") {
    return CATEGORY_LABELS.et[value as keyof typeof CATEGORY_LABELS.et] || fallback;
  }

  return fallback;
}
