export const CATEGORY_TREE = [
  {
    value: "vehicles",
    label: "Vehicles",
    children: [
      {
        value: "cars",
        label: "Cars",
        children: [
          { value: "passenger_cars", label: "Passenger cars" },
          { value: "suv_offroad", label: "SUVs / Off-road" },
          { value: "vans_minibuses", label: "Vans & Minibuses" },
          { value: "pickup_trucks", label: "Pickup trucks" },
          { value: "motorhomes_campers", label: "Motorhomes / Campers" },
          { value: "racing_vehicles", label: "Racing vehicles" },
        ],
      },
      {
        value: "motorcycles",
        label: "Motorcycles",
        children: [
          { value: "sport_bikes", label: "Sport bikes" },
          { value: "cruisers", label: "Cruisers" },
          { value: "touring", label: "Touring" },
          { value: "enduro_mx", label: "Enduro / MX" },
          { value: "scooters", label: "Scooters" },
          { value: "atv_utv", label: "ATV / UTV" },
          { value: "snowmobiles", label: "Snowmobiles" },
        ],
      },
      {
        value: "trucks_commercial",
        label: "Trucks & Commercial",
        children: [
          { value: "trucks", label: "Trucks" },
          { value: "semi_trucks", label: "Semi trucks" },
          { value: "buses", label: "Buses" },
          { value: "commercial_trailers", label: "Commercial trailers" },
        ],
      },
      {
        value: "agricultural_heavy_machinery",
        label: "Agricultural & Heavy Machinery",
        children: [
          { value: "tractors", label: "Tractors" },
          { value: "harvesters", label: "Harvesters" },
          { value: "excavators", label: "Excavators" },
          { value: "forestry_machinery", label: "Forestry machinery" },
          { value: "construction_machinery", label: "Construction machinery" },
          {
            value: "agricultural_attachments_implements",
            label: "Agricultural attachments & implements"
          },
          {
            value: "agricultural_heavy_machinery_spare_parts",
            label: "Agricultural & Heavy Machinery Spare Parts"
          },
        ],
      },
      {
        value: "marine",
        label: "Marine",
        children: [
          { value: "boats", label: "Boats" },
          { value: "yachts", label: "Yachts" },
          { value: "jet_skis", label: "Jet skis" },
          { value: "boat_trailers", label: "Boat trailers" },
          { value: "outboard_motors", label: "Outboard motors" },
        ],
      },
      {
        value: "aviation",
        label: "Aviation",
        children: [
          { value: "airplanes", label: "Airplanes" },
          { value: "helicopters", label: "Helicopters" },
          { value: "ultralights", label: "Ultralights" },
          { value: "drones", label: "Drones" },
          { value: "aircraft_parts", label: "Aircraft parts" },
        ],
      },
      {
        value: "trailers",
        label: "Trailers",
        children: [
          { value: "light_trailers", label: "Light trailers" },
          { value: "car_trailers", label: "Car trailers" },
          { value: "cargo_trailers", label: "Cargo trailers" },
          { value: "caravans", label: "Caravans" },
        ],
      },
      {
        value: "vehicle_parts",
        label: "Vehicle Parts",
        children: [
          { value: "engines_engine_parts", label: "Engines & Engine parts" },
          { value: "transmission_drivetrain", label: "Transmission & Drivetrain" },
          { value: "suspension_steering", label: "Suspension & Steering" },
          { value: "brakes", label: "Brakes" },
          { value: "electrical_parts", label: "Electrical parts" },
          { value: "batteries", label: "Batteries" },
          { value: "starters_alternators", label: "Starters & Alternators" },
          { value: "body_parts", label: "Body parts" },
          { value: "lights_lamps", label: "Lights & Lamps" },
          { value: "interior_parts", label: "Interior parts" },
          { value: "exhaust_parts", label: "Exhaust parts" },
          { value: "cooling_heating", label: "Cooling & Heating" },
          { value: "fuel_system", label: "Fuel system" },
          { value: "tires", label: "Tires" },
          { value: "wheels_rims", label: "Wheels / Rims" },
          { value: "accessories", label: "Accessories" },
          { value: "riding_racing_gear", label: "Riding & racing gear" },
          { value: "spare_parts", label: "Other spare parts" },
          { value: "vehicle_for_parts", label: "Complete vehicle for parts" },
        ],
      },
    ],
  },
  {
    value: "electronics",
    label: "Electronics",
    children: [
      { value: "phones", label: "Phones" },
      { value: "computers", label: "Computers" },
      { value: "tv_audio", label: "TV & Audio" },
      { value: "cameras", label: "Cameras" },
      { value: "gaming", label: "Gaming" },
      { value: "smart_home", label: "Smart home" },
      { value: "components", label: "Components" },
      { value: "electronics_accessories", label: "Accessories" },
    ],
  },
  {
    value: "real_estate",
    label: "Real Estate",
    children: [
      { value: "apartments", label: "Apartments" },
      { value: "houses", label: "Houses" },
      { value: "land", label: "Land" },
      { value: "commercial_property", label: "Commercial property" },
      { value: "garages", label: "Garages" },
      { value: "vacation_property", label: "Vacation property" },
    ],
  },
  {
    value: "clothing_fashion",
    label: "Clothing & Fashion",
    children: [
      { value: "men", label: "Men" },
      { value: "women", label: "Women" },
      { value: "kids", label: "Kids" },
      { value: "workwear", label: "Workwear" },
      { value: "shoes", label: "Shoes" },
      { value: "watches", label: "Watches" },
      { value: "bags", label: "Bags" },
      { value: "jewelry", label: "Jewelry" },
    ],
  },
  {
    value: "tools_industrial",
    label: "Tools & Industrial",
    children: [
      { value: "power_tools", label: "Power tools" },
      { value: "hand_tools", label: "Hand tools" },
      { value: "workshop_equipment", label: "Workshop equipment" },
      { value: "industrial_equipment", label: "Industrial equipment" },
      { value: "safety_equipment", label: "Safety equipment" },
    ],
  },
  {
    value: "home_garden",
    label: "Home & Garden",
    children: [
      { value: "furniture", label: "Furniture" },
      { value: "appliances", label: "Appliances" },
      { value: "garden_tools", label: "Garden tools" },
      { value: "plants_seedlings", label: "Plants & seedlings" },
      { value: "seeds", label: "Seeds" },
      { value: "crops_produce", label: "Crops & produce" },
      { value: "farm_supplies", label: "Farm supplies" },
      { value: "animal_feed", label: "Animal feed" },
      { value: "greenhouses", label: "Greenhouses" },
      { value: "decor", label: "Decor" },
      { value: "lighting", label: "Lighting" },
    ],
  },
  {
    value: "sports_outdoor",
    label: "Sports & Outdoor",
    children: [
      { value: "gym_equipment", label: "Gym equipment" },
      { value: "bicycles", label: "Bicycles" },
      { value: "winter_sports", label: "Winter sports" },
      { value: "camping", label: "Camping" },
      { value: "fishing", label: "Fishing" },
    ],
  },
  {
    value: "antiques_collectibles",
    label: "Antiques & Collectibles",
    children: [
      { value: "art", label: "Art" },
      { value: "vintage", label: "Vintage" },
      { value: "coins", label: "Coins" },
      { value: "military", label: "Military" },
      { value: "memorabilia", label: "Memorabilia" },
    ],
  },
  {
    value: "building_materials",
    label: "Building Materials",
    children: [
      { value: "lumber", label: "Lumber" },
      { value: "concrete", label: "Concrete" },
      { value: "insulation", label: "Insulation" },
      { value: "roofing", label: "Roofing" },
      { value: "plumbing", label: "Plumbing" },
    ],
  },
  {
    value: "general",
    label: "General",
    children: [],
  },
] as const;
