-- OUTER ROLLBACK IS PROVIDED BY THE RUNNER. Synthetic rows only.
SET LOCAL TimeZone='UTC';
CREATE SCHEMA price_test;
GRANT USAGE ON SCHEMA price_test TO anon,authenticated,service_role;
CREATE FUNCTION price_test.ok(value boolean,label text) RETURNS void LANGUAGE plpgsql AS $t$
BEGIN IF value IS DISTINCT FROM true THEN RAISE EXCEPTION 'PRICE_CORE_ASSERT_FAILED: %',label; END IF;
RAISE NOTICE 'PRICE_CORE_PASS: %',label; END $t$;
CREATE FUNCTION price_test.error(statement text,expected_code text,label text) RETURNS void LANGUAGE plpgsql AS $t$
DECLARE got text; BEGIN
  BEGIN EXECUTE statement; EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS got=RETURNED_SQLSTATE; END;
  PERFORM price_test.ok(got IS NOT DISTINCT FROM expected_code,label);
END $t$;
CREATE TABLE price_test.snapshots(name text PRIMARY KEY,value jsonb NOT NULL);
GRANT ALL ON price_test.snapshots TO authenticated;

SELECT price_test.ok((NOT (SELECT rolsuper FROM pg_roles WHERE rolname='authenticated')),'api_role_nonsuperuser');
SELECT price_test.ok((NOT pg_has_role('authenticated','postgres','MEMBER')),'no_api_membership_in_owner');
SELECT price_test.ok((NOT has_function_privilege('anon','public.set_my_listing_price_core_v1(text,uuid,text,jsonb)','EXECUTE')),'core_closed_to_anon');
SELECT price_test.ok((NOT has_function_privilege('authenticated','public.set_my_listing_price_core_v1(text,uuid,text,jsonb)','EXECUTE')),'core_closed_to_authenticated');
SELECT price_test.ok((NOT has_function_privilege('service_role','public.set_my_listing_price_core_v1(text,uuid,text,jsonb)','EXECUTE')),'core_closed_to_service_role');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"AUD"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"AUD"}'::jsonb),'currency_AUD_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.111","currency":"BHD"}'::jsonb)='{"kind":"fixed","amount":"12.111","currency":"BHD"}'::jsonb),'currency_BHD_scale_3');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"CAD"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"CAD"}'::jsonb),'currency_CAD_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"CHF"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"CHF"}'::jsonb),'currency_CHF_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"CZK"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"CZK"}'::jsonb),'currency_CZK_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"DKK"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"DKK"}'::jsonb),'currency_DKK_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"EUR"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"EUR"}'::jsonb),'currency_EUR_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"GBP"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"GBP"}'::jsonb),'currency_GBP_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12","currency":"JPY"}'::jsonb)='{"kind":"fixed","amount":"12","currency":"JPY"}'::jsonb),'currency_JPY_scale_0');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.111","currency":"KWD"}'::jsonb)='{"kind":"fixed","amount":"12.111","currency":"KWD"}'::jsonb),'currency_KWD_scale_3');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"NOK"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"NOK"}'::jsonb),'currency_NOK_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"NZD"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"NZD"}'::jsonb),'currency_NZD_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"PLN"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"PLN"}'::jsonb),'currency_PLN_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"SEK"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"SEK"}'::jsonb),'currency_SEK_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.111","currency":"TND"}'::jsonb)='{"kind":"fixed","amount":"12.111","currency":"TND"}'::jsonb),'currency_TND_scale_3');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.11","currency":"USD"}'::jsonb)='{"kind":"fixed","amount":"12.11","currency":"USD"}'::jsonb),'currency_USD_scale_2');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"free","amount":null,"currency":null}'::jsonb)='{"kind":"free","amount":null,"currency":null}'::jsonb),'mode_free');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"negotiable","amount":null,"currency":null}'::jsonb)='{"kind":"negotiable","amount":null,"currency":null}'::jsonb),'mode_negotiable');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"unspecified","amount":null,"currency":null}'::jsonb)='{"kind":"unspecified","amount":null,"currency":null}'::jsonb),'mode_unspecified');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"0","currency":"EUR"}'::jsonb)->>'amount'='0'),'exact_0');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"0.00","currency":"EUR"}'::jsonb)->>'amount'='0'),'exact_0_00');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"12.10","currency":"EUR"}'::jsonb)->>'amount'='12.1'),'exact_12_10');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"9007199254740993.01","currency":"EUR"}'::jsonb)->>'amount'='9007199254740993.01'),'exact_9007199254740993_01');
SELECT price_test.ok((public.normalize_listing_price_v1('{"kind":"fixed","amount":"999999999999999999.99","currency":"EUR"}'::jsonb)->>'amount'='999999999999999999.99'),'exact_999999999999999999_99');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''null''::jsonb)','22023','invalid_value_00');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''[]''::jsonb)','22023','invalid_value_01');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{}''::jsonb)','22023','invalid_value_02');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": 1, "currency": "EUR"}''::jsonb)','22023','invalid_value_03');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": true, "currency": "EUR"}''::jsonb)','22023','invalid_value_04');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": null, "amount": null, "currency": null}''::jsonb)','22023','invalid_value_05');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "auction", "amount": null, "currency": null}''::jsonb)','22023','invalid_value_06');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1", "currency": null}''::jsonb)','22023','invalid_value_07');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1", "currency": "eur"}''::jsonb)','22023','invalid_value_08');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1", "currency": "ZZZ"}''::jsonb)','22023','invalid_value_09');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1", "currency": "BTC"}''::jsonb)','22023','invalid_value_10');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1", "currency": "USD", "trusted": true}''::jsonb)','22023','invalid_value_11');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "free", "amount": "0", "currency": null}''::jsonb)','22023','invalid_value_12');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "unspecified", "amount": null, "currency": "EUR"}''::jsonb)','22023','invalid_value_13');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "", "currency": "EUR"}''::jsonb)','22023','invalid_value_14');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "NaN", "currency": "EUR"}''::jsonb)','22023','invalid_value_15');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "Infinity", "currency": "EUR"}''::jsonb)','22023','invalid_value_16');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "-Infinity", "currency": "EUR"}''::jsonb)','22023','invalid_value_17');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "-1", "currency": "EUR"}''::jsonb)','22023','invalid_value_18');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "+1", "currency": "EUR"}''::jsonb)','22023','invalid_value_19');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1e2", "currency": "EUR"}''::jsonb)','22023','invalid_value_20');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1,00", "currency": "EUR"}''::jsonb)','22023','invalid_value_21');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1 000", "currency": "EUR"}''::jsonb)','22023','invalid_value_22');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": " 1", "currency": "EUR"}''::jsonb)','22023','invalid_value_23');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1 ", "currency": "EUR"}''::jsonb)','22023','invalid_value_24');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "01", "currency": "EUR"}''::jsonb)','22023','invalid_value_25');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "00", "currency": "EUR"}''::jsonb)','22023','invalid_value_26');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1.", "currency": "EUR"}''::jsonb)','22023','invalid_value_27');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1..2", "currency": "EUR"}''::jsonb)','22023','invalid_value_28');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1.2345", "currency": "EUR"}''::jsonb)','22023','invalid_value_29');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1000000000000000000", "currency": "EUR"}''::jsonb)','22023','invalid_value_30');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1\n", "currency": "EUR"}''::jsonb)','22023','invalid_value_31');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "\uff11\uff12", "currency": "EUR"}''::jsonb)','22023','invalid_value_32');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1 EUR", "currency": "EUR"}''::jsonb)','22023','invalid_value_33');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1.001", "currency": "EUR"}''::jsonb)','22023','invalid_value_34');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(''{"kind": "fixed", "amount": "1.0", "currency": "JPY"}''::jsonb)','22023','invalid_value_35');
SELECT price_test.error('SELECT public.normalize_listing_price_v1(NULL)','22023','sql_null_price_rejected');
SELECT price_test.ok((public.listing_price_tuple_valid_v1('free',NULL,NULL,1,'Tasuta') IS TRUE),'tuple_free_valid');
SELECT price_test.ok((public.listing_price_tuple_valid_v1('fixed',NULL,'EUR',1,'1 EUR') IS FALSE),'tuple_null_amount_rejected');
SELECT price_test.ok((public.listing_price_tuple_valid_v1('fixed','NaN'::numeric,'EUR',1,'NaN EUR') IS FALSE),'tuple_nan_rejected');
SELECT price_test.ok((public.listing_price_tuple_valid_v1('fixed',1,'EUR',0,'1 EUR') IS FALSE),'tuple_zero_revision_rejected');
SELECT price_test.ok((public.listing_price_tuple_valid_v1('fixed',1,'EUR',1,'2 EUR') IS FALSE),'tuple_inconsistent_label_rejected');
INSERT INTO public.identities(id,type,user_id,business_account_id,display_name,status) VALUES
('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','private','11111111-1111-4111-8111-111111111111',NULL,'A','active'),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','private','22222222-2222-4222-8222-222222222222',NULL,'B','active'),
('cccccccc-cccc-4ccc-8ccc-cccccccccccc','business',NULL,'99999999-9999-4999-8999-999999999999','Business','active'),('dddddddd-dddd-4ddd-8ddd-dddddddddddd','private','11111111-1111-4111-8111-111111111111',NULL,'Alt A','active'),
('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','private','11111111-1111-4111-8111-111111111111',NULL,'Inactive','inactive');
INSERT INTO public.profiles(id,active_identity_id) VALUES ('11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),('22222222-2222-4222-8222-222222222222','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'),('33333333-3333-4333-8333-333333333333','cccccccc-cccc-4ccc-8ccc-cccccccccccc');
INSERT INTO public.business_members(business_account_id,user_id,role,status) VALUES ('99999999-9999-4999-8999-999999999999','33333333-3333-4333-8333-333333333333','member','active');
INSERT INTO public.listings(id,user_id,identity_id,title,description,price,price_amount,active_until,details,image) VALUES
(1001,'11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Original A','Description','5578',5578,'2026-01-01 00:00:00+00','{"model":"A"}','synthetic-image'),
(1002,'22222222-2222-4222-8222-222222222222','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','Original B','B','2',2,NULL,'{}',NULL),
(1003,'11111111-1111-4111-8111-111111111111','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Business listing','Biz','3',3,NULL,'{}',NULL),
(1004,'11111111-1111-4111-8111-111111111111',NULL,'Unassigned','Legacy','4',4,NULL,'{}',NULL);

SELECT price_test.ok(((SELECT price_kind IS NULL AND currency IS NULL AND price_revision=0 AND price='5578' FROM public.listings WHERE id=1001)),'legacy_row_not_backfilled');
INSERT INTO price_test.snapshots VALUES ('A_original',(SELECT to_jsonb(l) FROM public.listings l WHERE id=1001));
RESET ROLE; SET LOCAL request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''0'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','closed_core_cannot_be_called');
RESET ROLE; GRANT EXECUTE ON FUNCTION public.set_my_listing_price_core_v1(text,uuid,text,jsonb) TO authenticated;
RESET ROLE; SET LOCAL request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.ok((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','0','{"kind":"fixed","amount":"10","currency":"EUR"}'::jsonb)->>'changed'='true'),'first_structured_update');
SELECT price_test.ok(((SELECT price='10 EUR' AND price_kind='fixed' AND price_amount=10 AND currency='EUR' AND price_revision=1 FROM public.listings WHERE id=1001)),'one_canonical_tuple');
SELECT price_test.ok(((SELECT to_jsonb(l)-ARRAY['price','price_amount','currency','price_kind','price_revision'] FROM public.listings l WHERE id=1001)=(SELECT value-ARRAY['price','price_amount','currency','price_kind','price_revision'] FROM price_test.snapshots WHERE name='A_original')),'all_other_columns_preserved');
SELECT price_test.ok((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','1','{"kind":"fixed","amount":"10.00","currency":"EUR"}'::jsonb)->>'changed'='false'),'same_value_no_revision_bump');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''0'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','40001','stale_revision_even_if_same_value');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'','''',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_revision_78');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''01'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_revision_79');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''-1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_revision_80');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''NaN'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_revision_81');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''9223372036854775808'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_revision_82');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''0'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_id_83');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''-1'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_id_84');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''01'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_id_85');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''NaN'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_id_86');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''9223372036854775808'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','22023','bad_id_87');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1999'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','missing_row_not_disclosed');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1002'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''0'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','other_identity_row_denied');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1004'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''0'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','legacy_null_identity_not_adopted');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''dddddddd-dddd-4ddd-8ddd-dddddddddddd'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','expected_identity_mismatch');
SELECT price_test.error('UPDATE public.listings SET price=''20 EUR'' WHERE id=1001','42501','direct_text_denied');
SELECT price_test.error('UPDATE public.listings SET price_amount=20 WHERE id=1001','42501','direct_amount_denied');
SELECT price_test.error('UPDATE public.listings SET currency=''USD'' WHERE id=1001','42501','direct_currency_denied');
SELECT price_test.error('UPDATE public.listings SET price_kind=''free'',price_amount=NULL,currency=NULL WHERE id=1001','42501','direct_mode_denied');
SELECT price_test.error('UPDATE public.listings SET price_kind=NULL,currency=NULL WHERE id=1001','42501','direct_downgrade_denied');
SELECT price_test.error('UPDATE public.listings SET price_revision=2 WHERE id=1001','42501','direct_revision_denied');
SELECT price_test.error('UPDATE public.listings SET identity_id=''dddddddd-dddd-4ddd-8ddd-dddddddddddd'' WHERE id=1001','42501','direct_identity_denied');
SELECT price_test.error('UPDATE public.listings SET id=9999 WHERE id=1001','42501','direct_id_denied');
SELECT price_test.error('DELETE FROM public.listings WHERE id=1001','42501','direct_delete_structured_denied');
SELECT price_test.error('TRUNCATE public.listings','42501','truncate_bypass_denied');
SET LOCAL selqiro.trusted='true'; SET LOCAL request.jwt.claim.role='service_role';
SELECT price_test.error('UPDATE public.listings SET price_amount=20 WHERE id=1001','42501','client_trusted_flags_not_authority');
SET LOCAL request.jwt.claim.role='authenticated';
SELECT price_test.error('INSERT INTO public.listings(id,user_id,identity_id,price_kind,price_amount,currency) VALUES(1005,''11111111-1111-4111-8111-111111111111'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''fixed'',1,''EUR'')','42501','direct_structured_insert_denied');
UPDATE public.listings SET title='Changed title',description='Changed description',condition='new' WHERE id=1001;
SELECT price_test.ok(((SELECT price='10 EUR' AND price_amount=10 AND price_revision=1 FROM public.listings WHERE id=1001)),'unrelated_edit_preserves_price');
INSERT INTO price_test.snapshots VALUES ('before_renew',(SELECT public.listing_price_snapshot_v1(price_kind,price_amount,currency,price_revision,price) FROM public.listings WHERE id=1001));
SELECT * FROM public.renew_my_listing_activity_v1('1001','2026-01-01 00:00:00+00');
SELECT price_test.ok(((SELECT public.listing_price_snapshot_v1(price_kind,price_amount,currency,price_revision,price) FROM public.listings WHERE id=1001)=(SELECT value FROM price_test.snapshots WHERE name='before_renew')),'existing_renewal_preserves_price');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb);
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb)->'price'->>'kind')='fixed'),'transition_fixed_to_fixed');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='free'),'transition_fixed_to_free');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_fixed_to_free');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='negotiable'),'transition_fixed_to_negotiable');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_fixed_to_negotiable');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='unspecified'),'transition_fixed_to_unspecified');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_fixed_to_unspecified');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb);
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb)->'price'->>'kind')='fixed'),'transition_free_to_fixed');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='free'),'transition_free_to_free');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_free_to_free');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='negotiable'),'transition_free_to_negotiable');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_free_to_negotiable');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='unspecified'),'transition_free_to_unspecified');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_free_to_unspecified');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb);
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb)->'price'->>'kind')='fixed'),'transition_negotiable_to_fixed');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='free'),'transition_negotiable_to_free');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_negotiable_to_free');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='negotiable'),'transition_negotiable_to_negotiable');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_negotiable_to_negotiable');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='unspecified'),'transition_negotiable_to_unspecified');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_negotiable_to_unspecified');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb);
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"fixed","amount":"12","currency":"SEK"}'::jsonb)->'price'->>'kind')='fixed'),'transition_unspecified_to_fixed');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"free","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='free'),'transition_unspecified_to_free');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_unspecified_to_free');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"negotiable","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='negotiable'),'transition_unspecified_to_negotiable');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_unspecified_to_negotiable');
SELECT public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb);
SELECT price_test.ok(((public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',(SELECT price_revision::text FROM public.listings WHERE id=1001),'{"kind":"unspecified","amount":null,"currency":null}'::jsonb)->'price'->>'kind')='unspecified'),'transition_unspecified_to_unspecified');
SELECT price_test.ok(((SELECT price_amount IS NULL AND currency IS NULL FROM public.listings WHERE id=1001)),'no_hidden_money_unspecified_to_unspecified');
INSERT INTO price_test.snapshots VALUES ('A_before_error',(SELECT to_jsonb(l) FROM public.listings l WHERE id=1001));
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',(SELECT price_revision::text FROM public.listings WHERE id=1001),''{"kind":"fixed","amount":"1.001","currency":"EUR"}''::jsonb)','22023','writer_rejects_precision');
SELECT price_test.ok(((SELECT to_jsonb(l) FROM public.listings l WHERE id=1001)=(SELECT value FROM price_test.snapshots WHERE name='A_before_error')),'invalid_writer_no_partial_change');
DO $atomic$ BEGIN
  BEGIN
    UPDATE public.listings SET title='Should roll back' WHERE id=1001;
    PERFORM public.set_my_listing_price_core_v1('1001','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','0','{"kind":"fixed","amount":"1","currency":"EUR"}'::jsonb);
    RAISE EXCEPTION 'unexpected_success';
  EXCEPTION WHEN SQLSTATE '40001' THEN NULL;
  END;
END $atomic$;
SELECT price_test.ok(((SELECT to_jsonb(l) FROM public.listings l WHERE id=1001)=(SELECT value FROM price_test.snapshots WHERE name='A_before_error')),'enclosing_transaction_atomicity');
RESET ROLE; SET LOCAL request.jwt.claim.sub='22222222-2222-4222-8222-222222222222'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'',''0'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','wrong_account_denied');
RESET ROLE; SET LOCAL request.jwt.claim.sub=''; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''0'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','missing_auth_uid_denied');
RESET ROLE; SET LOCAL request.jwt.claim.sub='33333333-3333-4333-8333-333333333333'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.ok((public.set_my_listing_price_core_v1('1003','cccccccc-cccc-4ccc-8ccc-cccccccccccc','0','{"kind":"fixed","amount":"10","currency":"EUR"}'::jsonb)->>'changed'='true'),'active_business_member_allowed');
RESET ROLE; UPDATE public.business_members SET status='inactive' WHERE user_id='33333333-3333-4333-8333-333333333333';
RESET ROLE; SET LOCAL request.jwt.claim.sub='33333333-3333-4333-8333-333333333333'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1003'',''cccccccc-cccc-4ccc-8ccc-cccccccccccc'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','inactive_member_denied');
RESET ROLE; DELETE FROM public.business_members WHERE user_id='33333333-3333-4333-8333-333333333333';
RESET ROLE; SET LOCAL request.jwt.claim.sub='33333333-3333-4333-8333-333333333333'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1003'',''cccccccc-cccc-4ccc-8ccc-cccccccccccc'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','removed_member_denied');
RESET ROLE; UPDATE public.profiles SET active_identity_id='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee' WHERE id='11111111-1111-4111-8111-111111111111';
RESET ROLE; SET LOCAL request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','inactive_identity_denied');
RESET ROLE; UPDATE public.profiles SET active_identity_id='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb' WHERE id='11111111-1111-4111-8111-111111111111';
RESET ROLE; SET LOCAL request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1001'',''bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'',''1'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','42501','forged_inaccessible_active_identity_denied');
RESET ROLE; UPDATE public.profiles SET active_identity_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' WHERE id='11111111-1111-4111-8111-111111111111';
RESET ROLE; SET LOCAL request.jwt.claim.sub='22222222-2222-4222-8222-222222222222'; SET LOCAL request.jwt.claim.role='authenticated'; SET LOCAL ROLE authenticated;
UPDATE public.listings SET price='legacy changed',price_amount=8 WHERE id=1002;
SELECT price_test.ok(((SELECT price_revision=1 AND price_kind IS NULL AND currency IS NULL FROM public.listings WHERE id=1002)),'legacy_change_revision_bumped_no_inference');
SELECT price_test.error('SELECT public.set_my_listing_price_core_v1(''1002'',''bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'',''0'',''{"kind":"fixed","amount":"10","currency":"EUR"}''::jsonb)','40001','stale_snapshot_after_legacy_write');
RESET ROLE; SET LOCAL ROLE service_role;
SELECT price_test.error('UPDATE public.listings SET price_amount=999 WHERE id=1001','42501','service_bypassrls_not_price_authority');
SELECT price_test.error('TRUNCATE public.listings','42501','service_truncate_denied');
RESET ROLE;
INSERT INTO public.listings(id,user_id,identity_id,title,price_kind,price_amount,currency) VALUES(1005,'11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Typed creation','fixed',0,'JPY');
SELECT price_test.ok(((SELECT price='0 JPY' AND price_kind='fixed' AND price_revision=1 FROM public.listings WHERE id=1005)),'trusted_creation_zero_not_free');
SELECT price_test.error('INSERT INTO public.listings(id,user_id,identity_id,price_kind,price_amount,currency) VALUES(1006,''11111111-1111-4111-8111-111111111111'',''aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'',''free'',1,NULL)','22023','invalid_creation_rejected_atomically');
SELECT price_test.ok((NOT EXISTS(SELECT 1 FROM public.listings WHERE id=1006)),'no_partial_creation');
SELECT price_test.ok(((SELECT count(*)=5 FROM public.listings)),'only_expected_fixture_rows');
SELECT price_test.ok(((SELECT count(*)=0 FROM public.listing_images) AND (SELECT count(*)=0 FROM public.store_categories) AND (SELECT count(*)=0 FROM public.listing_store_categories)),'no_image_or_category_writes');
REVOKE ALL ON FUNCTION public.set_my_listing_price_core_v1(text,uuid,text,jsonb) FROM authenticated;
SELECT price_test.ok((NOT has_function_privilege('authenticated','public.set_my_listing_price_core_v1(text,uuid,text,jsonb)','EXECUTE')),'core_closed_again');
SELECT 'PRICE_CORE_SUITE=PASS';
