-- TEST ADAPTER ONLY, not a production schema change. Catalog on 2026-10-03 says
-- listings.id is bigint GENERATED BY DEFAULT AS IDENTITY. Prior 7-table fixture
-- intentionally omitted its identity sequence because earlier tests used explicit IDs.
DO $gate$ BEGIN
 IF current_database() <> 'selqiro_price_core_fixture' OR current_user <> 'postgres' THEN
  RAISE EXCEPTION 'listing_create_fixture_required';
 END IF;
END $gate$;
ALTER TABLE public.listings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 10000);
-- Explicit existing seed IDs are 1001..1004. Sequence state may advance on rollback;
-- gaps are expected, and are not a claim of leftover application rows.
