#!/usr/bin/env python3
"""Frozen listing currency registry -> TypeScript + closed SQL value candidate.
Default --check reads only. --write generates exactly the two declared outputs.
No network or database. The historical lab normalizer is retained byte-for-byte.
"""
import argparse
import hashlib
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path

REGISTRY = 'data/currency/listing-currency-registry.v1.json'
TS = 'src/shared/currency/listingCurrencies.generated.ts'
SQL = 'supabase/releases/listing-price-v1/price-value-contract.generated.sql'
CORE = 'supabase/labs/listing-price-core-v1/01_value_contract.sql'
CORE_SHA = '5f9d58db5d28a9ec6804e1f0b2c282d5dd812897165b0e07242b12524d56c29c'


def sha(data):
    return hashlib.sha256(data).hexdigest()


def plain(root, name):
    path = root / name
    if path.resolve(strict=True) != path or not path.is_file():
        raise ValueError('Expected a plain source file: ' + name)
    return path.read_bytes()


def read_registry(root):
    raw = plain(root, REGISTRY)
    reg = json.loads(raw)
    if reg['format'] != 'selqiro_listing_currency_registry_v1':
        raise ValueError('Unexpected registry format')
    source = reg['source']
    current = plain(root, source['current_path'])
    historical = plain(root, source['historical_path'])
    if sha(current) != source['current_sha256'] or sha(historical) != source['historical_sha256']:
        raise ValueError('Frozen ISO source bytes differ')
    for xml in (current, historical):
        if len(xml) > 2 * 1024 * 1024 or b'<!DOCTYPE' in xml.upper() or b'<!ENTITY' in xml.upper():
            raise ValueError('Unexpected XML declaration or size')
    tree = ET.fromstring(current)
    if tree.attrib.get('Pblshd') != source['current_published']:
        raise ValueError('Publication date differs')
    if ET.fromstring(historical).attrib.get('Pblshd') != source['historical_published']:
        raise ValueError('Historical publication date differs')
    rows = {}
    for row in tree.findall('./CcyTbl/CcyNtry'):
        code = (row.findtext('Ccy') or '').strip()
        if not code:
            continue  # Preserve all raw rows; no-currency territories are not invented codes.
        ccy_name = row.find('CcyNm')
        fund_text = ccy_name.attrib.get('IsFund') if ccy_name is not None else None
        if fund_text not in (None, 'true'):
            raise ValueError('Unreviewed IsFund marker')
        fund = True if fund_text == 'true' else None
        value = ((row.findtext('CcyNbr') or '').strip(),
                 (row.findtext('CcyMnrUnts') or '').strip(), fund)
        if code not in rows:
            rows[code] = {'values': set(), 'names': set()}
        rows[code]['values'].add(value)
        rows[code]['names'].add((row.findtext('CcyNm') or '').strip())
    entries = reg['entries']
    codes = [e['code'] for e in entries]
    if codes != sorted(rows) or len(codes) != len(set(codes)):
        raise ValueError('Registry must account for every current code exactly once')
    allowed = []
    for e in entries:
        code = e['code']
        if not re.fullmatch('[A-Z]{3}', code) or not re.fullmatch('[0-9]{3}', e['numeric_code']):
            raise ValueError('Code shape differs')
        observed = rows[code]
        if observed['values'] != {(e['numeric_code'], e['source_minor_units'], e['fund'])}:
            raise ValueError('Conflicting/source value: ' + code)
        if sorted(observed['names']) != e['names']:
            raise ValueError('Source names differ: ' + code)
        policy_allowed = e['fund'] is None and e['source_minor_units'] in ('0', '2', '3') and code != 'VED'
        if type(e['input_allowed']) is not bool or e['input_allowed'] != policy_allowed:
            raise ValueError('Input policy differs: ' + code)
        if policy_allowed:
            if type(e['minor_units']) is not int or str(e['minor_units']) != e['source_minor_units']:
                raise ValueError('Scale differs: ' + code)
            allowed.append(e)
        elif e['minor_units'] is not None:
            raise ValueError('Excluded code cannot have an input scale: ' + code)
    if len(entries) != 178 or len(allowed) != 154:
        raise ValueError('Frozen selection count differs; review a versioned change')
    if {n: sum(e['minor_units'] == n for e in allowed) for n in (0, 2, 3)} != {0: 16, 2: 131, 3: 7}:
        raise ValueError('Frozen precision distribution differs')
    return reg, allowed, sha(raw)


def generate(root):
    reg, entries, fingerprint = read_registry(root)
    q = lambda s: json.dumps(s, ensure_ascii=False)
    lines = ['/** GENERATED by scripts/currency/generate_listing_price_registry.py. Do not edit.',
             ' * New listing input only. No currency conversion, country or payment eligibility. */',
             'export const LISTING_CURRENCY_VERSION = ' + q(reg['version']) + ' as const;',
             'export const LISTING_CURRENCY_SOURCE_SHA256 = ' + q(fingerprint) + ' as const;',
             'const rows = [']
    for e in entries:
        lines.append('  [' + ', '.join((q(e['code']), q(e['names'][0]), q(e['numeric_code']), str(e['minor_units']))) + '],')
    lines += ['] as const;',
              'export type ListingCurrencyCode = (typeof rows)[number][0];',
              'export type ListingCurrency = Readonly<{ code: ListingCurrencyCode; name: string; numericCode: string; minorUnits: 0 | 2 | 3 }>;',
              'export const LISTING_CURRENCIES: readonly ListingCurrency[] = Object.freeze(',
              '  rows.map(([code, name, numericCode, minorUnits]) => Object.freeze({ code, name, numericCode, minorUnits }))',
              ');',
              'const byCode = new Map<string, ListingCurrency>(LISTING_CURRENCIES.map(row => [row.code, row]));',
              'export function getListingCurrency(code: unknown): ListingCurrency | null {',
              '  return typeof code === "string" ? byCode.get(code) ?? null : null;',
              '}', '']
    core = plain(root, CORE)
    if sha(core) != CORE_SHA:
        raise ValueError('Retained tested normalizer source changed')
    text = core.decode('utf-8')
    start = text.index('CREATE FUNCTION public.normalize_listing_price_v1(')
    # The closing dollar tag can follow END on the SAME line. A newline search
    # previously captured the following legacy helper as part of this function.
    opening = text.index('AS $fn$', start) + len('AS $fn$')
    end = text.index('$fn$;', opening) + len('$fn$;')
    normalizer = text[start:end]
    if (normalizer.count('CREATE FUNCTION ') != 1 or
            sha(normalizer.encode()) != '1a703a5757cbdc7648d881db2a3af2234b891db855d4789bd44b5f1d36b33d45'):
        raise ValueError('Exact retained normalizer statement differs')
    sql = ("-- GENERATED frozen release INPUT fragment, NOT a migration or deployment permission.\n"
           "-- Registry SHA256: " + fingerprint + "\n"
           "-- Retained normalizer SHA256: " + sha(normalizer.encode()) + "\n"
           "-- First installation only; no replacement of a live IMMUTABLE function.\n"
           "DO $gate$ BEGIN\n"
           "  IF current_database() <> 'selqiro_price_input_fixture' OR current_user <> 'postgres' THEN\n"
           "    RAISE EXCEPTION 'price_input_disposable_fixture_required';\n"
           "  END IF;\nEND $gate$;\n\n"
           "CREATE FUNCTION public.listing_price_currency_scale_v1(p_currency text)\n"
           "RETURNS integer LANGUAGE sql IMMUTABLE PARALLEL SAFE\n"
           "SET search_path = pg_catalog\nAS $fn$\n  SELECT CASE p_currency\n")
    sql += ''.join("    WHEN '" + e['code'] + "' THEN " + str(e['minor_units']) + '\n' for e in entries)
    sql += "    ELSE NULL END;\n$fn$;\n\n" + normalizer + '\n\n'
    sql += ("REVOKE ALL ON FUNCTION public.listing_price_currency_scale_v1(text),\n"
            " public.normalize_listing_price_v1(jsonb) FROM PUBLIC;\n")
    return {TS: '\n'.join(lines).encode(), SQL: sql.encode()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--check', action='store_true')
    modes.add_argument('--write', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).absolute().parents[2]
    try:
        expected = generate(root)
        for name, data in expected.items():
            target = root / name
            if args.write:
                target.parent.mkdir(parents=True, exist_ok=True)
                if target.resolve() != target or (target.exists() and not target.is_file()):
                    raise ValueError('Unsafe generation target')
                target.write_bytes(data)
            if plain(root, name) != data:
                raise ValueError('Generated file differs: ' + name)
        print('LISTING_CURRENCY_GENERATION=PASS')
        return 0
    except (ValueError, KeyError, TypeError, OSError, ET.ParseError) as error:
        print('LISTING_CURRENCY_GENERATION=STOP: ' + str(error))
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
